from django.urls import path

from .views import (
    AccountListView,
    AccountClassificationListView,
    AccountDetailView,
    AccountImportTemplateView,
    AccountImportGuideView,
    AccountImportPreviewView,
    AccountImportCommitView,
    StoreCopyPlaceholderView,
    AccountingCompleteSetupView,
    AccountingLifecycleLogListView,
    AccountingSettingsView,
    BankReconciliationMatchView,
    BankReconciliationView,
    BankStatementImportCommitView,
    BankStatementImportPreviewView,
    BankStatementListView,
    CashBankAccountListView,
    JournalEntryListCreateView,
    JournalExportView,
    JournalImportCommitView,
    JournalImportPreviewView,
    JournalEntryDetailView,
    SingleJournalEntryExportView,
    LedgerAccountDetailView,
    LedgerAccountExportView,
    LedgerAllAccountsDetailView,
    LedgerDetailExportView,
    LedgerSummaryExportView,
    LedgerSummaryView,
    OpeningBalanceSubmitView,
    PaymentMethodAuditLogView,
    PaymentMethodBulkUpdateAccountView,
    PaymentMethodListView,
    SettlementConfirmView,
    SettlementListView,
    TransferModalCreateView,
    TransferModalListView,
)

urlpatterns = [
    path("accounts/", AccountListView.as_view(), name="accounting-accounts"),
    path("accounts/<int:pk>/", AccountDetailView.as_view(), name="accounting-account-detail"),
    path("accounts/import/template/", AccountImportTemplateView.as_view(), name="accounting-accounts-import-template"),
    path("accounts/import/guide/", AccountImportGuideView.as_view(), name="accounting-accounts-import-guide"),
    path("accounts/import/preview/", AccountImportPreviewView.as_view(), name="accounting-accounts-import-preview"),
    path("accounts/import/commit/", AccountImportCommitView.as_view(), name="accounting-accounts-import-commit"),
    path("accounts/copy-store/", StoreCopyPlaceholderView.as_view(), name="accounting-accounts-copy-store"),
    path(
        "account-classifications/",
        AccountClassificationListView.as_view(),
        name="accounting-account-classifications",
    ),
    path("journal-entries/", JournalEntryListCreateView.as_view(), name="accounting-journal-entries"),
    path(
        "journal-entries/import/preview/",
        JournalImportPreviewView.as_view(),
        name="accounting-journal-import-preview",
    ),
    path(
        "journal-entries/import/commit/",
        JournalImportCommitView.as_view(),
        name="accounting-journal-import-commit",
    ),
    path("journal-entries/export/", JournalExportView.as_view(), name="accounting-journal-export"),
    path(
        "journal-entries/<str:entry_number>/export/",
        SingleJournalEntryExportView.as_view(),
        name="accounting-journal-entry-export",
    ),
    path("journal-entries/<str:entry_number>/", JournalEntryDetailView.as_view(), name="accounting-journal-entry-detail"),
    path("ledger/", LedgerSummaryView.as_view(), name="accounting-ledger"),
    path("ledger/export/", LedgerSummaryExportView.as_view(), name="accounting-ledger-export"),
    path("ledger/export-detail/", LedgerDetailExportView.as_view(), name="accounting-ledger-export-detail"),
    path("ledger/detail/", LedgerAllAccountsDetailView.as_view(), name="accounting-ledger-detail"),
    path("ledger/<int:account_id>/", LedgerAccountDetailView.as_view(), name="accounting-ledger-account"),
    path(
        "ledger/<int:account_id>/export/",
        LedgerAccountExportView.as_view(),
        name="accounting-ledger-account-export",
    ),
    path("payment-methods/", PaymentMethodListView.as_view(), name="accounting-payment-methods"),
    path(
        "payment-methods/bulk-update-account/",
        PaymentMethodBulkUpdateAccountView.as_view(),
        name="accounting-payment-methods-bulk-update",
    ),
    path(
        "payment-methods/<int:payment_method_id>/log/",
        PaymentMethodAuditLogView.as_view(),
        name="accounting-payment-methods-log",
    ),
    path("cash-bank-accounts/", CashBankAccountListView.as_view(), name="accounting-cash-bank-accounts"),
    path("bank-statement/", BankStatementListView.as_view(), name="accounting-bank-statement"),
    path(
        "bank-statement/import/preview/",
        BankStatementImportPreviewView.as_view(),
        name="accounting-bank-statement-import-preview",
    ),
    path(
        "bank-statement/import/commit/",
        BankStatementImportCommitView.as_view(),
        name="accounting-bank-statement-import-commit",
    ),
    path("bank-reconciliation/", BankReconciliationView.as_view(), name="accounting-bank-reconciliation"),
    path(
        "bank-reconciliation/match/",
        BankReconciliationMatchView.as_view(),
        name="accounting-bank-reconciliation-match",
    ),
    path("settlements/", SettlementListView.as_view(), name="accounting-settlements"),
    path("settlements/confirm/", SettlementConfirmView.as_view(), name="accounting-settlements-confirm"),
    path("transfer-modal/", TransferModalListView.as_view(), name="accounting-transfer-modal"),
    path("transfer-modal/create/", TransferModalCreateView.as_view(), name="accounting-transfer-modal-create"),
    path("opening-balances/", OpeningBalanceSubmitView.as_view(), name="accounting-opening-balances"),
    path("settings/", AccountingSettingsView.as_view(), name="accounting-settings"),
    path(
        "settings/complete-setup/",
        AccountingCompleteSetupView.as_view(),
        name="accounting-settings-complete-setup",
    ),
    path("lifecycle-logs/", AccountingLifecycleLogListView.as_view(), name="accounting-lifecycle-logs"),
]
