/**
 * Konfigurasi daftar laporan untuk tab "Laporan Penjualan".
 * Bentuk sama dengan reportList.js (Produk). Sebagian kolom masih placeholder —
 * akan disesuaikan per screenshot Olsera.
 */

// Kolom yang sering dipakai ulang.
const tgl = { key: 'tanggal', label: 'Tanggal' };
const total = { key: 'total', label: 'Total', align: 'right' };
const qty = { key: 'qty', label: 'Qty', align: 'right' };

// Toolbar default: tanggal + PDF + EXCEL.
const TB = { paket: false, cari: false };

export const PENJUALAN_REPORTS = [
  {
    id: 'keseluruhan',
    label: 'Laporan Keseluruhan Penjualan',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Penjualan', 'Pembayaran'],
      selectDefault: 'Penjualan',
    },
    linkList: [
      {
        label: 'Ringkasan Diskon',
        dataSource: 'ringkasan-diskon',
        summary: {
          title: 'Ringkasan',
          columns: [
            { key: 'sumber', label: 'Sumber Penjualan' },
            { key: 'kode_diskon', label: 'Kode Diskon' },
            { key: 'nama_diskon', label: 'Nama Diskon' },
            { key: 'jumlah_diskon', label: 'Jumlah Diskon', align: 'right' },
            { key: 'qty_pesanan', label: 'Qty Pesanan', align: 'right' },
          ],
        },
      },
      {
        // Terhubung: agregasi penebusan poin nyata dari transaksi POS
        // (POSSale.loyalty_redemption). Kolom "item gratis" tetap 0 karena opsi
        // penukaran saat ini hanya berupa diskon.
        label: 'Ringkasan Loyalti Point',
        dataSource: 'ringkasan-loyalti',
        summary: {
          title: 'Ringkasan',
          columns: [
            { key: 'nama_loyalty', label: 'Nama Loyalty Point' },
            { key: 'tebus_point', label: 'Tebus Point', align: 'right' },
            { key: 'tebus_diskon', label: 'Tebus Diskon', align: 'right' },
            { key: 'tebus_item_gratis', label: 'Tebus Item Gratis', align: 'right' },
            { key: 'qty_item_gratis', label: 'Qty Item Gratis', align: 'right' },
            { key: 'total_redeem', label: 'Total Redeem', align: 'right' },
          ],
        },
      },
      {
        label: 'Pesanan Dibatalkan',
        dataSource: 'pesanan-dibatalkan',
        summary: {
          title: 'Ringkasan',
          columns: [
            { key: 'sumber', label: 'Sumber Penjualan' },
            { key: 'total_pesanan', label: 'Total Pesanan', align: 'right' },
            { key: 'qty_pesanan', label: 'Qty Pesanan', align: 'right' },
          ],
        },
      },
      {
        label: 'Top Grup Produk',
        dataSource: 'kategori',
        summary: {
          columns: [
            { key: 'nama', label: 'Nama' },
            { key: 'qty', label: 'Qty', align: 'right' },
            { key: 'jumlah', label: 'Jumlah', align: 'right' },
          ],
        },
      },
      {
        label: 'Top Produk',
        dataSource: 'top-produk',
        summary: {
          columns: [
            { key: 'nama', label: 'Nama' },
            { key: 'qty', label: 'Qty', align: 'right' },
            { key: 'jumlah', label: 'Jumlah', align: 'right' },
          ],
        },
      },
      {
        label: 'Laba/Rugi',
        dataSource: 'laba-rugi',
        labaRugi: [
          {
            code: 'A',
            title: 'Pendapatan',
            total: '0,00',
            items: [
              { label: 'Pajak (exclude)', value: '0,00' },
              { label: 'Pajak (include)', value: '0,00' },
              { label: 'Pembulatan', value: '0,00' },
              { label: 'Pengembalian', value: '0,00' },
              { label: 'Total Deposit yang ditebus', value: '0,00' },
            ],
          },
          {
            code: 'B',
            title: 'Harga Pokok Penjualan',
            total: '0,00',
            items: [
              { label: 'Total Penjualan (Harga Modal)', value: '0,00' },
              { label: 'Total Pengembalian (Harga Modal)', value: '0,00' },
            ],
          },
          { code: 'C', title: 'Laba Kotor', total: '0,00', items: [] },
          { code: 'D', title: 'Pengeluaran', total: '0,00', empty: true, items: [] },
          {
            code: 'E',
            title: 'Stok',
            items: [
              { label: 'Stok Keluar', value: 'IDR 0' },
              { label: 'Opname Stok', value: 'IDR 0' },
            ],
          },
          {
            code: 'F',
            title: 'Pembelian',
            items: [
              { label: 'Diskon', value: '0,00' },
              { label: 'Pengiriman', value: '0,00' },
              { label: 'Pajak', value: '0,00' },
            ],
          },
          { code: 'G', title: 'Laba Bersih', total: '0,00', items: [] },
        ],
      },
      {
        label: 'Penjualan berdasarkan Kategori',
        dataSource: 'kategori',
        summary: {
          columns: [
            { key: 'nama', label: 'Nama' },
            { key: 'jumlah', label: 'Jumlah', align: 'right' },
            { key: 'qty', label: 'Qty', align: 'right' },
          ],
        },
      },
      {
        label: 'Ringkasan Metode Pembayaran',
        dataSource: 'ringkasan-metode',
        summary: {
          title: 'Ringkasan',
          columns: [
            { key: 'cara_pembayaran', label: 'Cara Pembayaran' },
            { key: 'akun_bank', label: 'Akun Bank' },
            { key: 'total_jual', label: 'Total Penjualan', align: 'right' },
          ],
        },
      },
      {
        label: 'Transaksi Tunai',
        dataSource: 'transaksi-tunai',
        summary: {
          columns: [
            { key: 'void_tunai', label: 'Void Tunai', align: 'right' },
            { key: 'kas_selisih', label: 'Kas Selisih', align: 'right' },
            { key: 'pengembalian_tunai', label: 'Pengembalian Tunai', align: 'right' },
            { key: 'pendapatan', label: 'Pendapatan', align: 'right' },
          ],
          rows: [
            {
              void_tunai: 'IDR 0,00',
              kas_selisih: 'IDR 0,00',
              pengembalian_tunai: 'IDR 0,00',
              pendapatan: 'IDR 0,00',
            },
          ],
        },
      },
    ],
  },
  {
    id: 'rincian-penjualan',
    dataSource: 'rincian-penjualan',
    label: 'Rincian Penjualan',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pembulatan', label: 'Total Pembulatan', align: 'right' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman', label: 'Pengiriman', align: 'right' },
        { key: 'pajak', label: 'Pajak', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'tambahan_pembayaran', label: 'Tambahan Pembayaran', align: 'right' },
        { key: 'diskon', label: 'Diskon', align: 'right' },
        { key: 'total_tebus_deposit', label: 'Total Tebus Deposit', align: 'right' },
        { key: 'total_pengunjung', label: 'Total Pengunjung', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'pembayaran', label: 'Pembayaran' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'dilayani_oleh', label: 'Dilayani Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'id_pelanggan', label: 'ID Pelanggan' },
      { key: 'pembulatan', label: 'Pembulatan', align: 'right' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'jumlah_ditebus', label: 'Jumlah Ditebus', align: 'right' },
      { key: 'pengiriman_pajak', label: 'PengirimanPajak', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
      { key: 'tambahan_pembayaran', label: 'Tambahan Pembayaran', align: 'right' },
      { key: 'diskon', label: 'Diskon', align: 'right' },
      { key: 'tebus_deposit', label: 'Tebus Deposit', align: 'right' },
      { key: 'pengunjung', label: 'Pengunjung', align: 'right' },
      { key: 'status', label: 'Status' },
      { key: 'keterangan', label: 'Keterangan' },
    ],
  },
  {
    id: 'rincian-backdate',
    label: 'Rincian Penjualan Backdate',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman_pajak', label: 'PengirimanPajak', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'diskon', label: 'Diskon', align: 'right' },
        { key: 'total_ditebus', label: 'Total ditebus', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'waktu_pembuatan', label: 'Waktu Pembuatan' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'id_pelanggan', label: 'ID Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'jumlah_ditebus', label: 'Jumlah Ditebus', align: 'right' },
      { key: 'pengiriman_pajak', label: 'PengirimanPajak', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
      { key: 'diskon', label: 'Diskon', align: 'right' },
      { key: 'total_ditebus', label: 'Total ditebus', align: 'right' },
    ],
  },
  {
    id: 'loyalti-point',
    label: 'Rincian Penggunaan Loyalti Point',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman_pajak', label: 'PengirimanPajak', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'diskon', label: 'Diskon', align: 'right' },
        { key: 'total_ditebus', label: 'Total ditebus', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'tanggal_pembayaran', label: 'Tanggal Pembayaran' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'id_pelanggan', label: 'ID Pelanggan' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'type_loyalti', label: 'Type Loyalti Point' },
      { key: 'tebus_point', label: 'Tebus Point', align: 'right' },
      { key: 'tebus_diskon', label: 'Tebus Diskon', align: 'right' },
      { key: 'tebus_item_gratis', label: 'Tebus Item gratis', align: 'right' },
      { key: 'qty_item_gratis', label: 'Qty Item Gratis', align: 'right' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'online-order',
    label: 'Rincian Penjualan - Online Order',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman_pajak', label: 'PengirimanPajak', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'diskon', label: 'Diskon', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_online_order', label: 'No. Online Order' },
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'pengiriman_pajak', label: 'Pengiriman+Pajak', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
      { key: 'diskon', label: 'Diskon', align: 'right' },
    ],
  },
  {
    id: 'marketplace',
    label: 'Rincian Penjualan Marketplace',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman_pajak', label: 'PengirimanPajak', align: 'right' },
        { key: 'pengiriman_marketplace', label: 'Pengiriman Marketplace', align: 'right' },
        { key: 'biaya_admin', label: 'Biaya admin', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'diskon', label: 'Diskon', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'nama_toko', label: 'Nama Toko' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'pengiriman_pajak', label: 'Pengiriman+Pajak', align: 'right' },
      { key: 'pengiriman_marketplace', label: 'Pengiriman Marketplace', align: 'right' },
      { key: 'biaya_admin', label: 'Biaya admin', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
      { key: 'diskon', label: 'Diskon', align: 'right' },
    ],
  },
  {
    id: 'pending-pos',
    label: 'Rincian Penjualan Pending POS',
    toolbar: TB,
    columns: [
      { key: 'catatan', label: 'Catatan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'dilayani_oleh', label: 'Dilayani oleh' },
      { key: 'pelanggan_id', label: 'Pelanggan ID' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'nomor_meja', label: 'Nomor Meja' },
      total,
    ],
  },
  {
    id: 'item-pending-pos',
    label: 'Rincian Penjualan Item Pending POS berdasarkan Tanggal',
    toolbar: TB,
    columns: [
      { key: 'catatan', label: 'Catatan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'pelanggan_id', label: 'Pelanggan ID' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'nomor_meja', label: 'Nomor Meja' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'no_seri', label: 'No. Seri' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'total_pesanan', label: 'Total Pesanan', align: 'right' },
    ],
  },
  {
    id: 'berdasarkan-jam',
    label: 'Rincian Penjualan berdasarkan Jam',
    dateMode: 'datetime',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman_pajak', label: 'Pengiriman + Pajak', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'diskon_penjualan', label: 'Diskon Penjualan', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'pengiriman_pajak', label: 'Pengiriman + Pajak', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
      { key: 'diskon_penjualan', label: 'Diskon Penjualan', align: 'right' },
    ],
  },
  {
    id: 'penjualan-deposit',
    label: 'Rincian penjualan deposit',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'total_transaksi', label: 'Total Transaksi', align: 'right' },
        { key: 'tebus_deposit', label: 'Tebus Deposit', align: 'right' },
        { key: 'total_harga_jual_deposit', label: 'Total Harga Jual Deposit', align: 'right' },
      ],
    },
    columns: [
      { key: 'id_pelanggan', label: 'Id Pelanggan' },
      { key: 'nama_pelanggan', label: 'Nama Pelanggan' },
      { key: 'email_pelanggan', label: 'Email Pelanggan' },
      { key: 'no_transaksi', label: 'No. Transaksi' },
      { key: 'tipe_transaksi', label: 'Tipe Transaksi' },
      { key: 'tgl_transaksi', label: 'Tgl Transaksi' },
      { key: 'tebus_deposit', label: 'Tebus Deposit', align: 'right' },
      { key: 'harga_jual_deposit', label: 'Harga Jual Deposit', align: 'right' },
    ],
  },
  {
    id: 'penjualan-tanggal',
    label: 'Penjualan berdasarkan Tanggal',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    paginate: true,
    summary: {
      title: 'Ringkasan',
      type: 'list',
      items: [
        { label: 'Jumlah', value: 'IDR 0,00' },
        { label: 'Sumber Penjualan', value: 'Pengembalian' },
      ],
    },
    columns: [tgl, { key: 'jumlah', label: 'Jumlah', align: 'right' }],
  },
  {
    id: 'item-penjualan-tanggal',
    dataSource: 'item-penjualan-tanggal',
    label: 'Item Penjualan berdasarkan Tanggal',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    filterBar: {
      select: ['Produk dan Varian', 'Pembeli', 'SKU'],
      searchPlaceholder: 'Cari produk atau varian',
    },
    summary: {
      type: 'grid',
      items: [
        { label: 'Qty', value: '0' },
        { label: 'Diskon Penjualan', value: 'IDR 0' },
        { label: 'Total Penjualan', value: 'IDR 0' },
        { label: 'Modal Produk', value: 'IDR 0' },
        { label: 'Total Laba', value: 'IDR 0' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'item', label: 'Item' },
      { key: 'no_seri', label: 'No. Seri' },
      { key: 'pelanggan', label: 'Pelanggan' },
      qty,
      { key: 'diskon', label: 'Diskon', align: 'right' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'komisi', label: 'Komisi', align: 'right' },
    ],
  },
  {
    id: 'item-brand',
    dataSource: 'item-brand',
    label: 'Item Penjualan Berdasarkan Brand',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    filterBar: { inputPlaceholder: 'Tambah Brand', submitLabel: 'Kirim' },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'total', label: 'Total', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'brand', label: 'Brand' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
    ],
  },
  {
    id: 'item-koleksi',
    label: 'Item Penjualan Berdasarkan Koleksi',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'total', label: 'Total', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'koleksi', label: 'Koleksi' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
    ],
  },
  {
    id: 'pelunasan-kredit',
    dataSource: 'pelunasan-kredit',
    label: 'Item Penjualan berdasarkan Pelunasan Kredit',
    toolbar: TB,
    paginate: false,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'total', label: 'Total', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'cara_pembayaran', label: 'Cara Pembayaran' },
      { key: 'jumlah_terbayar', label: 'Jumlah Terbayar', align: 'right' },
    ],
  },
  {
    id: 'pelunasan-non-kredit',
    label: 'Item Penjualan berdasarkan Pelunasan Non Kredit',
    toolbar: TB,
    paginate: false,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'total', label: 'Total', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'cara_pembayaran', label: 'Cara Pembayaran' },
      { key: 'jumlah_terbayar', label: 'Jumlah Terbayar', align: 'right' },
    ],
  },
  {
    id: 'diskon-item-tanggal',
    label: 'Diskon Item Penjualan berdasarkan Tanggal',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    paginate: false,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'jumlah_diskon', label: 'Jumlah Diskon', align: 'right' },
        { key: 'total', label: 'Total', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'jumlah', label: 'Jumlah', align: 'right' },
      { key: 'diskon', label: 'Diskon', align: 'right' },
      { key: 'total', label: 'Total', align: 'right' },
    ],
  },
  {
    id: 'addon-item-tanggal',
    label: 'Add-on Item Penjualan berdasarkan Tanggal',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    paginate: false,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'qty', label: 'Qty', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'addon', label: 'Add-On' },
      qty,
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'penjualan-pelanggan',
    label: 'Penjualan berdasarkan Pelanggan',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'biaya_pengiriman', label: 'Biaya Pengiriman', align: 'right' },
        { key: 'total_minus_pengiriman', label: 'Total Penjualan - Biaya Pengiriman', align: 'right' },
      ],
    },
    columns: [
      { key: 'sumber_penjualan', label: 'Sumber Penjualan' },
      { key: 'tipe_pelanggan', label: 'Tipe Pelanggan' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'biaya_pengiriman', label: 'Biaya Pengiriman', align: 'right' },
      { key: 'total_minus_pengiriman', label: 'Total Penjualan - Biaya Pengiriman', align: 'right' },
    ],
  },
  {
    id: 'penjualan-penjual',
    label: 'Penjualan berdasarkan Penjual',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    hideTable: true,
  },
  {
    id: 'penjualan-table',
    label: 'Penjualan berdasarkan nomor table',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    hideTable: true,
  },
  {
    id: 'komisi-pelayan',
    label: 'Komisi berdasarkan Pelayan',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    hideTable: true,
  },
  {
    id: 'komisi-staff',
    label: 'Komisi berdasarkan staff',
    toolbar: TB,
    hideTable: true,
  },
  {
    id: 'penjualan-perangkat',
    label: 'Penjualan berdasarkan Perangkat',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      ],
    },
    columns: [
      { key: 'sumber_penjualan', label: 'Sumber Penjualan' },
      { key: 'perangkat', label: 'Perangkat' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'item-pelanggan',
    label: 'Item Penjualan Berdasarkan Pelanggan',
    toolbar: TB,
    hideTable: true,
  },
  {
    id: 'kota-pelanggan',
    label: 'Penjualan berdasarkan Kota Pelanggan',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      ],
    },
    columns: [
      { key: 'sumber_penjualan', label: 'Sumber Penjualan' },
      { key: 'negara', label: 'Negara' },
      { key: 'propinsi', label: 'Propinsi' },
      { key: 'kota', label: 'Kota' },
      { key: 'kecamatan', label: 'Kecamatan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'kota-pengiriman',
    label: 'Penjualan berdasarkan Kota Pengiriman',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      ],
    },
    columns: [
      { key: 'sumber_penjualan', label: 'Sumber Penjualan' },
      { key: 'negara', label: 'Negara' },
      { key: 'propinsi', label: 'Propinsi' },
      { key: 'kota', label: 'Kota' },
      { key: 'kecamatan', label: 'Kecamatan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'ringkasan-diskon',
    label: 'Ringkasan Diskon',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_jumlah_diskon', label: 'Total Jumlah Diskon', align: 'right' },
        { key: 'total_qty', label: 'Total Qty', align: 'right' },
      ],
    },
    columns: [
      { key: 'sumber_penjualan', label: 'Sumber Penjualan' },
      { key: 'kode_diskon', label: 'Kode Diskon' },
      { key: 'nama_diskon', label: 'Nama Diskon' },
      { key: 'jumlah_diskon', label: 'Jumlah Diskon', align: 'right' },
      { key: 'qty_pesanan', label: 'Qty Pesanan', align: 'right' },
    ],
  },
  {
    id: 'pengeluaran-tanggal',
    label: 'Pengeluaran berdasarkan Tanggal',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pengeluaran', label: 'Total Pengeluaran', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_transaksi', label: 'No. Transaksi' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'tipe', label: 'Tipe' },
      { key: 'staff', label: 'Staff' },
      { key: 'deskripsi', label: 'Deskripsi' },
      { key: 'jumlah', label: 'Jumlah', align: 'right' },
    ],
  },
  {
    id: 'penjualan-pendapatan-pengeluaran',
    label: 'Penjualan + Pendapatan/Pengeluaran',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pendapatan', label: 'Total Pendapatan', align: 'right' },
        { key: 'total_pengeluaran', label: 'Total Pengeluaran', align: 'right' },
        { key: 'jumlah', label: 'Jumlah', align: 'right' },
      ],
    },
    columns: [
      { key: 'no', label: 'No' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'tipe', label: 'Tipe' },
      { key: 'pendapatan', label: 'Pendapatan', align: 'right' },
      { key: 'pengeluaran', label: 'Pengeluaran', align: 'right' },
      { key: 'total', label: 'Total', align: 'right' },
    ],
  },
  {
    id: 'penjualan-kredit',
    label: 'Rincian Penjualan Kredit',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman_pajak', label: 'Pengiriman + Pajak', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'diskon', label: 'Diskon', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'pengiriman_pajak', label: 'Pengiriman + Pajak', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
      { key: 'diskon', label: 'Diskon', align: 'right' },
    ],
  },
  {
    id: 'pelunasan-kredit-2',
    label: 'Pelunasan Kredit',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pembayaran', label: 'Total Pembayaran', align: 'right' },
      ],
    },
    columns: [
      { key: 'diterima_oleh', label: 'Diterima Oleh' },
      { key: 'tanggal_pembayaran', label: 'Tanggal Pembayaran' },
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'cara_pembayaran', label: 'Cara Pembayaran' },
      { key: 'total_pembayaran', label: 'Total Pembayaran', align: 'right' },
    ],
  },
  {
    id: 'laba-rugi',
    // Terhubung ke backend: /reports/laba-rugi/ mengembalikan seksi `labaRugi`
    // terhitung dari data nyata. Definisi `labaRugi` statis di bawah tetap
    // dipakai sebagai fallback bila fetch gagal / belum termuat.
    dataSource: 'laba-rugi',
    label: 'Laba/Rugi',
    toolbar: {
      paket: false,
      cari: false,
    },
    labaRugi: [
      {
        code: 'A',
        title: 'Pendapatan',
        total: '0,00',
        items: [
          { label: 'Pajak (exclude)', value: '0,00' },
          { label: 'Pajak (include)', value: '0,00' },
          { label: 'Pengembalian', value: '0,00' },
          { label: 'Total Deposit yang ditebus', value: '0,00' },
        ],
      },
      {
        code: 'B',
        title: 'Harga Pokok Penjualan',
        total: '0',
        items: [
          { label: 'Total Penjualan (Harga Modal)', value: '0,00' },
          { label: 'Total Pengembalian (Harga Modal)', value: '0,00' },
        ],
      },
      { code: 'C', title: 'Laba Kotor - (Pengiriman + Pajak)', total: '0,00', items: [] },
      { code: 'D', title: 'Pengeluaran', total: '0,00', empty: true, items: [] },
      {
        code: 'E',
        title: 'Selisih Stok',
        items: [
          { label: 'Stok Keluar', value: 'IDR 0' },
          { label: 'Stok Opname', value: 'IDR 0' },
        ],
      },
      {
        code: 'F',
        title: 'Pembelian',
        total: '0,00',
        items: [
          { label: 'Diskon', value: '0,00' },
          { label: 'Pengiriman', value: '0,00' },
          { label: 'Pajak', value: '0,00' },
        ],
      },
      { code: 'H', title: 'Laba Bersih', total: '0,00', items: [] },
      {
        code: 'I',
        title: 'Info Stok Produk',
        items: [
          { label: 'Stok Masuk', value: '0' },
          { label: 'Sisa Stok Produk saat ini', value: '0' },
        ],
      },
    ],
  },
  {
    id: 'pembatalan-penjualan',
    label: 'Rincian Pembatalan Penjualan',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'jumlah', label: 'Jumlah', align: 'right' },
      { key: 'catatan', label: 'Catatan' },
    ],
  },
  {
    id: 'pos-batal-belum-bayar',
    label: 'Detail pos yang batal belum dibayar',
    toolbar: TB,
    columns: [
      { key: 'catatan', label: 'Catatan' },
      { key: 'perangkat', label: 'Perangkat' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'id_pelanggan', label: 'ID Pelanggan' },
      { key: 'nama_pelanggan', label: 'Nama Pelanggan' },
      { key: 'no_table', label: 'No. Table' },
      { key: 'dilayani_oleh', label: 'Dilayani Oleh' },
      { key: 'no_seri', label: 'No. Seri' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'total_pesanan', label: 'Total Pesanan', align: 'right' },
    ],
  },
  {
    id: 'rincian-pengembalian',
    label: 'Rincian Pengembalian',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pengembalian', label: 'Total Pengembalian', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_pengembalian', label: 'Tanggal Pengembalian' },
      { key: 'diproses_oleh', label: 'Diproses Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'jumlah', label: 'Jumlah', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'catatan', label: 'Catatan' },
    ],
  },
  {
    id: 'pengembalian-tanggal',
    label: 'Pengembalian berdasarkan Tanggal',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pengembalian', label: 'Total Pengembalian', align: 'right' },
      ],
    },
    columns: [
      { key: 'tanggal_pengembalian', label: 'Tanggal Pengembalian' },
      { key: 'jumlah_pengembalian', label: 'Jumlah Pengembalian', align: 'right' },
    ],
  },
  {
    id: 'pengembalian-pelanggan',
    label: 'Pengembalian berdasarkan Pelanggan',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pengembalian', label: 'Total Pengembalian', align: 'right' },
      ],
    },
    columns: [
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'email', label: 'Email' },
      { key: 'jumlah_pengembalian', label: 'Jumlah Pengembalian', align: 'right' },
    ],
  },
  {
    id: 'item-dibatalkan',
    label: 'Item Dibatalkan',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Telah Bayar', '+Belum Bayar'],
      selectDefault: 'Telah Bayar',
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_pesanan', label: 'Total Pesanan', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'total_pesanan', label: 'Total Pesanan', align: 'right' },
    ],
  },
  {
    id: 'log-item-pos-batal',
    label: 'Log Item POS Dibatalkan',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'total_item', label: 'Total Item', align: 'right' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      ],
    },
    columns: [
      { key: 'tanggal_penjualan', label: 'Tanggal Penjualan' },
      { key: 'tanggal_batal', label: 'Tanggal Batal' },
      { key: 'type_order', label: 'Type Order' },
      { key: 'type_log', label: 'Type Log' },
      { key: 'no_pesanan', label: 'No.Pesanan' },
      { key: 'nomor_meja', label: 'Nomor Meja' },
      { key: 'dibatalkan_oleh', label: 'Dibatalkan oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'catatan_order', label: 'Catatan Order' },
      { key: 'catatan_item', label: 'Catatan Item' },
    ],
  },
  {
    id: 'item-dikembalikan',
    label: 'Item Dikembalikan',
    toolbar: TB,
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'qty', label: 'Qty', align: 'right' },
        { key: 'total_pengembalian', label: 'Total Pengembalian', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_pengembalian', label: 'No. Pengembalian' },
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_pengembalian', label: 'Tanggal Pengembalian' },
      { key: 'diproses_oleh', label: 'Diproses Oleh' },
      { key: 'item', label: 'Item' },
      qty,
      { key: 'jumlah_pengembalian', label: 'Jumlah Pengembalian', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
    ],
  },
  {
    id: 'sisa-deposit',
    label: 'Sisa deposit',
    toolbar: TB,
    filterBar: { searchPlaceholder: 'Cari id atau nama' },
    columns: [
      { key: 'id_pelanggan', label: 'Id Pelanggan' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'email', label: 'Email' },
      { key: 'sisa_deposit', label: 'Sisa deposit', align: 'right' },
      { key: 'deposit_tertahan', label: 'Deposit tertahan', align: 'right' },
    ],
  },
  {
    id: 'penjualan-qpon',
    label: 'Rincian Penjualan QPon',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['CASH', 'QPON QRIS'],
      extraSelects: [{ label: 'Telah Bayar', options: ['Telah Bayar', '+Belum Bayar'] }],
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'mata_uang', label: 'Mata Uang' },
        { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
        { key: 'pengiriman_pajak', label: 'PengirimanPajak', align: 'right' },
        { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
        { key: 'laba', label: 'Laba', align: 'right' },
        { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
        { key: 'diskon', label: 'Diskon', align: 'right' },
        { key: 'nominal_kupon', label: 'Nominal Kupon', align: 'right' },
      ],
    },
    columns: [
      { key: 'no_online_order', label: 'No. Online Order' },
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'penjualan_oleh', label: 'Penjualan Oleh' },
      { key: 'pelanggan', label: 'Pelanggan' },
      { key: 'total_penjualan', label: 'Total Penjualan', align: 'right' },
      { key: 'pengiriman_pajak', label: 'Pengiriman+Pajak', align: 'right' },
      { key: 'modal_produk', label: 'Modal Produk', align: 'right' },
      { key: 'laba', label: 'Laba', align: 'right' },
      { key: 'biaya_layanan', label: 'Biaya Layanan', align: 'right' },
      { key: 'diskon', label: 'Diskon', align: 'right' },
      { key: 'nominal_kupon', label: 'Nominal Kupon', align: 'right' },
    ],
  },
];

export default PENJUALAN_REPORTS;
