# Generated by Django 5.0.14 on 2026-05-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organization_admin', models.BooleanField(default=False, help_text='Jika True, user memiliki akses penuh setara Owner.')),
                ('has_production_access', models.BooleanField(default=True, help_text='Akses ke modul Produksi (Order, Job Board).')),
                ('has_finance_access', models.BooleanField(default=False, help_text='Akses ke laporan keuangan dan data omset.')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Timestamp terakhir user aktif (diupdate middleware).', null=True)),
                ('date_of_joining', models.DateField(blank=True, help_text='Tanggal mulai bergabung.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil User',
                'verbose_name_plural': 'Profil User',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_input', models.CharField(blank=True, default='', max_length=150)),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Berhasil'), ('LOGIN_FAILED', 'Login Gagal'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Refresh Token'), ('TOKEN_REVOKED', 'Token Dicabut'), ('PASSWORD_CHANGED', 'Ganti Password'), ('PERMISSION_DENIED', 'Akses Ditolak'), ('USER_CREATED', 'User Baru Dibuat'), ('USER_DEACTIVATED', 'User Dinonaktifkan')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('keterangan', models.TextField(blank=True, default='')),
                ('berhasil', models.BooleanField(db_index=True, default=True)),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null saat login gagal (user tidak diketahui).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'db_table': 'security_audit_log',
                'ordering': ['-waktu'],
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(db_index=True, help_text='JWT ID (jti claim) — digunakan untuk identifikasi & revoke.', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_name', models.CharField(blank=True, default='', help_text='Label device, misal: Chrome di Windows 10.', max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Token',
                'verbose_name_plural': 'Session Tokens',
                'db_table': 'session_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
