# Generated by Django 5.0.14 on 2026-05-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_karyawan',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('cuti', 'Cuti'), ('nonaktif', 'Non-Aktif')], default='aktif', help_text='Status aktif, cuti, atau non-aktif.', max_length=20),
        ),
    ]
