# Generated by Django 5.0.14 on 2026-05-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_status_karyawan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status_karyawan',
        ),
    ]
