# Generated by Django 5.2.16 on 2026-07-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_status_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditlog',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Berhasil'), ('LOGIN_FAILED', 'Login Gagal'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Refresh Token'), ('TOKEN_REVOKED', 'Token Dicabut'), ('PASSWORD_CHANGED', 'Ganti Password'), ('PASSWORD_RESET_REQUESTED', 'Reset Password Diminta'), ('PASSWORD_RESET_FAILED', 'Reset Password Gagal'), ('PASSWORD_RESET_SUCCEEDED', 'Reset Password Berhasil'), ('PERMISSION_DENIED', 'Akses Ditolak'), ('USER_CREATED', 'User Baru Dibuat'), ('USER_DEACTIVATED', 'User Dinonaktifkan')], db_index=True, max_length=30),
        ),
    ]
