# Generated by Django 5.2.17 on 2026-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_securityauditlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='refresh_jti',
            field=models.CharField(blank=True, db_index=True, default='', help_text='JTI refresh token yang menerbitkan access token ini. Dipakai SessionRevokeView utk memblokir OutstandingToken terkait supaya sesi benar-benar berhenti (bukan cuma menandai baris ini tidak aktif) -- access token yang sudah terlanjur terbit tetap sah sampai kedaluwarsa alami (maks. 1 jam), refresh berikutnya baru ditolak. Baris lama (sebelum kolom ini ada) kosong -- tidak bisa dicabut instan.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sessiontoken',
            name='token_jti',
            field=models.CharField(db_index=True, help_text='JWT ID (jti claim) dari ACCESS token — dipakai utk identifikasi baris ini.', max_length=255, unique=True),
        ),
    ]
