// Katalog Pusat Bantuan (2026-10-05).
//
// Satu entri = satu layanan: tata cara, halaman, endpoint API yang dipakai
// halaman itu, peran yang boleh memakai, dan skenario UAT terkait. Pusat
// Bantuan hanya menampilkan layanan milik peran pengguna yang sedang login.
//
// Nama menu/tombol diambil dari kode (Sidebar.jsx, permissions.js, dan
// komponen tiap halaman). Endpoint = yang dipanggil halaman tersebut; endpoint
// jembatan antar aplikasi (/api/bridge/...) sengaja TIDAK dicantumkan.
// Ubah entri di sini bila menu/tombol berubah.
//
// Peran: owner, manager, admin, kasir, staff, spv, kordiv, admin_finance,
// spv_finance. '*' = semua peran.

export const URL_HR = 'https://hr.starphotoadvertising.com';
export const URL_CRM = 'https://crm.starphotoadvertising.com';

export const URUTAN_MODUL = [
  'Akun & Login',
  'Absensi',
  'Kasir & Shift',
  'Pesanan & Produksi',
  'Bahan Baku',
  'Produk & Inventori',
  'Pelanggan & Supplier',
  'Keuangan',
  'Laporan & Dashboard',
  'Pengaturan',
  'HR & CRM',
];

const OWNER_MANAGER = ['owner', 'manager'];
const KEUANGAN = ['owner', 'manager', 'admin_finance', 'spv_finance'];
const PRODUKSI = ['staff', 'spv', 'kordiv'];
const KASIR = ['kasir', 'admin'];

export const KATALOG_LAYANAN = [
  // ───────────────────────────── Akun & Login
  {
    id: 'login',
    modul: 'Akun & Login',
    judul: 'Masuk dan keluar aplikasi',
    ringkas: 'Login dengan username dan sandi yang sama untuk ERP, HR/mobile, dan CRM.',
    peran: ['*'],
    kataKunci: ['login', 'masuk', 'logout', 'keluar', 'terkunci', 'otp', 'username'],
    langkah: [
      'Buka halaman login, isi Username dan Password, tekan MASUK.',
      'Bila login dari jaringan/perangkat baru, kode OTP dikirim ke email akun. Isi kode lalu tekan VERIFIKASI & MASUK.',
      'Salah sandi 3 kali berturut-turut membuat akun terkunci 10 menit. Tunggu, atau minta kode OTP pembuka kunci dari email.',
      'Untuk keluar, tekan Logout di bawah sidebar. Sesi juga berakhir otomatis setelah 30 menit tanpa aktivitas.',
    ],
    halaman: '/login',
    endpoint: ['POST /api/auth/login/', 'POST /api/auth/verify-login/', 'POST /api/auth/login/unlock-otp/', 'POST /api/auth/logout/'],
    uat: ['PRE-04', 'AKS-03'],
  },
  {
    id: 'lupa-sandi',
    modul: 'Akun & Login',
    judul: 'Lupa kata sandi',
    ringkas: 'Membuat sandi baru lewat kode OTP yang dikirim ke email akun.',
    peran: ['*'],
    kataKunci: ['lupa', 'password', 'sandi', 'reset', 'otp'],
    langkah: [
      'Di halaman login tekan Lupa Password?.',
      'Isi username, tekan KIRIM KODE OTP. Kode dikirim ke email akun (kirim ulang baru bisa setelah 15 menit).',
      'Isi kode OTP dan sandi baru: minimal 8 karakter, ada huruf dan angka, tidak memuat username.',
      'Simpan, lalu login dengan sandi baru. Sandi baru juga berlaku di HR/mobile dan CRM.',
    ],
    halaman: '/login',
    endpoint: ['POST /api/auth/forgot-password/request/', 'POST /api/auth/forgot-password/verify/'],
    uat: ['AKS-05'],
  },
  {
    id: 'ganti-sandi',
    modul: 'Akun & Login',
    judul: 'Ganti kata sandi',
    ringkas: 'Mengganti sandi saat masih ingat sandi lama.',
    peran: ['owner', 'manager', 'admin'],
    kataKunci: ['ganti', 'ubah', 'password', 'sandi'],
    langkah: [
      'Buka Pengaturan > Toko, tab Akun Saya.',
      'Isi Password Lama, Password Baru, dan Konfirmasi Password Baru, lalu simpan.',
      'Sandi baru otomatis berlaku juga di HR/mobile dan CRM.',
    ],
    halaman: '/settings/toko',
    endpoint: ['POST /api/auth/change-password/'],
    uat: ['AKS-05'],
    catatan: 'Peran lain: pakai Lupa kata sandi di halaman login, atau ganti sandi lewat aplikasi HR.',
  },
  {
    id: 'profil',
    modul: 'Akun & Login',
    judul: 'Ubah profil dan foto',
    ringkas: 'Memperbarui data diri dan foto profil.',
    peran: ['*'],
    kataKunci: ['profil', 'foto', 'avatar', 'bio', 'nomor hp'],
    langkah: [
      'Buka menu Profil.',
      'Tekan Edit Profil untuk mengubah data, lalu simpan.',
      'Tekan Ubah Foto untuk mengganti foto. Foto ikut berganti di HR/mobile dan CRM.',
    ],
    halaman: '/profile',
    endpoint: ['GET /api/users/me/', 'PATCH /api/users/me/'],
    uat: ['SEC-05'],
  },

  // ───────────────────────────── Absensi
  {
    id: 'mulai-kerja',
    modul: 'Absensi',
    judul: 'Mulai Kerja dan pulang (absen)',
    ringkas: 'Absen masuk sebelum bekerja; syarat membuka Papan Kerja dan transaksi kasir.',
    peran: ['kasir', 'staff', 'spv', 'kordiv'],
    kataKunci: ['absen', 'mulai kerja', 'clock in', 'pulang', 'masuk kerja'],
    langkah: [
      'Buka Dashboard.',
      'Tekan Mulai Kerja. Kasir: buka shift dulu (Shift & Kas > Buka Shift Sekarang) lalu tekan Mulai Kerja.',
      'Saat selesai bekerja, tekan tombol pulang di Dashboard.',
      'Absen juga bisa lewat aplikasi mobile HR.',
    ],
    halaman: { kasir: '/kasir/dashboard', staff: '/staff-dashboard', spv: '/staff-dashboard', kordiv: '/staff-dashboard' },
    endpoint: ['GET /api/hr/dashboard/staff/', 'POST /api/hr/absensi/clock-in/', 'POST /api/hr/absensi/clock-out/'],
    uat: ['E2E-05'],
  },
  {
    id: 'pantau-absensi',
    modul: 'Absensi',
    judul: 'Pantau dan koreksi absensi karyawan',
    ringkas: 'Melihat kehadiran, keterangan, dan jadwal karyawan.',
    peran: OWNER_MANAGER,
    kataKunci: ['absensi', 'kehadiran', 'telat', 'jadwal', 'export absensi'],
    langkah: [
      'Buka HR & Kepegawaian > Absensi.',
      'Pilih tanggal. Tekan Detail untuk rincian, Jadwal untuk jadwal kerja, atau isi keterangan lalu simpan.',
      'Unduh rekap lewat tombol export.',
    ],
    halaman: '/attendance',
    endpoint: ['GET /api/hr/absensi/', 'PATCH /api/hr/absensi/{id}/', 'GET /api/export/absensi/'],
    uat: ['E2E-05', 'E2E-06'],
  },

  // ───────────────────────────── Kasir & Shift
  {
    id: 'buka-shift',
    modul: 'Kasir & Shift',
    judul: 'Buka shift kasir',
    ringkas: 'Membuka shift dengan saldo awal sebelum mulai transaksi.',
    peran: KASIR,
    kataKunci: ['shift', 'buka shift', 'saldo awal', 'modal'],
    langkah: [
      'Buka Shift & Kas (atau tekan Buka Shift Sekarang di layar Kasir).',
      'Isi saldo awal laci kas lalu simpan.',
      'Kembali ke Dashboard Kasir dan tekan Mulai Kerja.',
    ],
    halaman: '/kasir/shift',
    endpoint: ['POST /api/saldo-kas-harian/'],
    uat: ['E2E-01'],
  },
  {
    id: 'jual-pos',
    modul: 'Kasir & Shift',
    judul: 'Transaksi penjualan di Kasir (POS)',
    ringkas: 'Menjual produk langsung, bayar, lalu cetak atau kirim nota.',
    peran: KASIR,
    kataKunci: ['jual', 'pos', 'kasir', 'bayar', 'nota', 'struk', 'cetak', 'kembalian', 'transaksi'],
    langkah: [
      'Buka Kasir (POS). Pilih produk dari katalog; produk masuk panel pesanan.',
      'Pilih pelanggan lewat Tampil Daftar Pelanggan, atau Tambah Customer Baru.',
      'Tekan Bayar, pilih Bayar Lunas atau DP / Uang Muka, pilih metode (mis. CASH), isi uang diterima, tekan Bayar.',
      'Di layar sukses: cetak nota, kirim resi WhatsApp, atau Terbitkan SPK bila perlu dikerjakan produksi.',
    ],
    halaman: '/kasir/terminal',
    endpoint: ['GET /api/products/', 'GET /api/customers/', 'POST /api/customers/', 'POST /api/pos/sales/'],
    uat: ['PRE-07', 'MST-01', 'E2E-01'],
    catatan: 'Produk dengan stok kosong ditolak bila aturan blokir jual stok kosong aktif (Pengaturan > Point Of Sale).',
  },
  {
    id: 'terbitkan-spk',
    modul: 'Kasir & Shift',
    judul: 'Terbitkan SPK ke produksi',
    ringkas: 'Mengirim pesanan ke divisi produksi sebagai surat perintah kerja.',
    peran: KASIR,
    kataKunci: ['spk', 'terbitkan', 'produksi', 'divisi', 'editor', 'operator'],
    langkah: [
      'Setelah pembayaran tersimpan, tekan Terbitkan SPK (di layar sukses, Riwayat Transaksi, atau detail pesanan).',
      'Pilih divisi tujuan. Hanya divisi milik unit bisnis Anda yang muncul.',
      'Tekan Terbitkan SPK. Pekerjaan muncul di Antrean Global Divisi staff.',
    ],
    halaman: '/kasir/riwayat',
    endpoint: ['GET /api/divisi/', 'GET /api/tahap-proses/', 'POST /api/pos/sales/{id}/terbitkan-spk/', 'POST /api/orders/{id}/assign/'],
    uat: ['E2E-01', 'E2E-08'],
    catatan: 'Insentif hanya bisa ditentukan Owner/Manager/Admin; kasir mengirim tanpa insentif.',
  },
  {
    id: 'antrean-online',
    modul: 'Kasir & Shift',
    judul: 'Proses pesanan dari WhatsApp dan staff',
    ringkas: 'Memeriksa pesanan bot WA / Buat Order staff, menerima pembayaran, lalu kirim ke produksi.',
    peran: KASIR,
    kataKunci: ['antrean', 'wa', 'whatsapp', 'online', 'bot', 'verifikasi nota', 'order sales'],
    langkah: [
      'Buka Antrean Online & Offline, pilih pesanan.',
      'Periksa item. Perbaiki lewat pencarian produk atau Add Item bila harga/produk dari bot belum tepat.',
      'Tekan Terima Pembayaran bila pelanggan sudah membayar (cek bukti transfer).',
      'Tekan Simpan & Verifikasi Nota / Verifikasi Nota & Kirim ke Antrean Produksi, lalu Terbitkan SPK.',
    ],
    halaman: '/kasir/antrean-wa',
    endpoint: ['GET /api/orders/', 'PATCH /api/orders/{id}/', 'POST /api/order-items/', 'PATCH /api/order-items/{id}/', 'POST /api/orders/{id}/assign/'],
    uat: ['PRE-06', 'E2E-02', 'E2E-03'],
    catatan: 'Stok baru terpotong saat nota disimpan, bukan saat bot membuat pesanan.',
  },
  {
    id: 'pelunasan',
    modul: 'Kasir & Shift',
    judul: 'Pelunasan pesanan (DP dan sisa tagihan)',
    ringkas: 'Membayar sebagian atau seluruh sisa tagihan pesanan.',
    peran: KASIR,
    kataKunci: ['lunas', 'pelunasan', 'dp', 'uang muka', 'sisa', 'tagihan', 'piutang', 'cicil'],
    langkah: [
      'Buka Riwayat Transaksi atau daftar Pesanan Produksi, pilih pesanan yang belum lunas.',
      'Tekan pelunasan, isi nominal (sebagian atau penuh), pilih metode, tekan bayar.',
      'Cetak Faktur atau kirim tagihan/nota lewat WhatsApp bila perlu.',
    ],
    halaman: '/kasir/riwayat',
    endpoint: ['POST /api/orders/{id}/bayar/', 'POST /api/orders/{id}/invoice-whatsapp/'],
    uat: ['E2E-07'],
  },
  {
    id: 'sudah-diambil',
    modul: 'Kasir & Shift',
    judul: 'Serahkan pesanan (Sudah Diambil)',
    ringkas: 'Menandai pesanan produksi yang sudah selesai dan diserahkan ke pelanggan.',
    peran: KASIR,
    kataKunci: ['diambil', 'serah', 'siap diambil', 'selesai', 'ambil'],
    langkah: [
      'Di Dashboard Kasir tekan kartu Pesanan Produksi > Buka daftar. Notifikasi siap diambil muncul sekitar 20 detik setelah produksi selesai.',
      'Pastikan pesanan sudah lunas.',
      'Tekan Sudah Diambil, lalu Ya, Sudah Diambil.',
    ],
    halaman: '/kasir/pesanan',
    endpoint: ['GET /api/pos/sales/produksi/', 'POST /api/orders/{id}/selesaikan/', 'POST /api/pos/sales/{id}/selesaikan/'],
    uat: ['E2E-01'],
  },
  {
    id: 'void',
    modul: 'Kasir & Shift',
    judul: 'Batalkan pesanan (Void / Refund)',
    ringkas: 'Membatalkan pesanan dengan alasan dan persetujuan OTP Owner.',
    peran: KASIR,
    kataKunci: ['void', 'batal', 'refund', 'pembatalan', 'retur', 'otp owner'],
    langkah: [
      'Buka pesanan di panel pesanan atau Riwayat Transaksi, tekan Void Pesanan.',
      'Isi alasan dan kondisi barang, tekan Lakukan Void / Refund.',
      'Tekan Kirim Permintaan OTP ke Owner. Owner memberi kode; kasir mengisinya dan mengonfirmasi.',
      'SPK pesanan ditarik dari papan kerja dan jurnal pembalik dibuat otomatis.',
    ],
    halaman: '/kasir/riwayat',
    endpoint: ['POST /api/pos/sales/{id}/minta-otp-void/', 'POST /api/pos/sales/{id}/void/', 'POST /api/orders/{id}/minta-otp-void/', 'POST /api/orders/{id}/batalkan/'],
    uat: ['E2E-09'],
    catatan: 'Pesanan yang sudah Sudah Diambil tidak bisa di-void.',
  },
  {
    id: 'setujui-void',
    modul: 'Kasir & Shift',
    judul: 'Setujui pembatalan (void) dari kasir',
    ringkas: 'Owner/Manager memeriksa permintaan void kasir lalu menyetujui atau menolaknya.',
    peran: OWNER_MANAGER,
    kataKunci: ['void', 'batal', 'refund', 'otp', 'persetujuan', 'approve'],
    langkah: [
      'Buka Dashboard, tab Operasional, bagian antrean permintaan void.',
      'Periksa alasan dan nominalnya, lalu tekan Setujui atau Tolak.',
      'Alternatif: kasir meminta kode OTP yang dikirim ke email Owner; berikan kode itu bila disetujui.',
    ],
    halaman: '/dashboard-eksekutif/operasional',
    endpoint: ['GET /api/pos-void-requests/', 'POST /api/pos-void-requests/{id}/setujui/', 'POST /api/pos-void-requests/{id}/tolak/'],
    uat: ['E2E-09'],
  },
  {
    id: 'kas-masuk-keluar',
    modul: 'Kasir & Shift',
    judul: 'Catat kas masuk dan kas keluar',
    ringkas: 'Mencatat uang masuk/keluar laci di luar penjualan selama shift.',
    peran: KASIR,
    kataKunci: ['kas masuk', 'kas keluar', 'pengeluaran', 'kas kecil', 'laci'],
    langkah: [
      'Buka Shift & Kas.',
      'Tekan tombol + (Catat Kas Masuk / Keluar), pilih Kas Masuk atau Kas Keluar.',
      'Isi jenis, nominal, dan keterangan, lalu simpan.',
    ],
    halaman: '/kasir/shift',
    endpoint: ['GET /api/cash-transaction-types/', 'POST /api/cash-transactions/'],
    uat: ['E2E-01'],
  },
  {
    id: 'tutup-shift',
    modul: 'Kasir & Shift',
    judul: 'Tutup shift (Akhiri Shift)',
    ringkas: 'Menghitung saldo akhir laci; selisih tercatat untuk diverifikasi Admin Finance.',
    peran: KASIR,
    kataKunci: ['tutup shift', 'akhiri shift', 'saldo akhir', 'setoran', 'selisih'],
    langkah: [
      'Buka Shift & Kas, tekan Akhiri Shift.',
      'Hitung uang di laci, isi saldo akhir, konfirmasi.',
      'Setoran shift masuk antrean verifikasi Admin Finance.',
    ],
    halaman: '/kasir/shift',
    endpoint: ['GET /api/pos/sales/rekap-harian/', 'POST /api/saldo-kas-harian/{id}/close/'],
    uat: ['E2E-01'],
  },
  {
    id: 'riwayat-transaksi',
    modul: 'Kasir & Shift',
    judul: 'Riwayat transaksi dan kirim ulang nota',
    ringkas: 'Mencari transaksi lama, cetak ulang, kirim resi, dan melihat log aktivitas transaksi.',
    peran: KASIR,
    kataKunci: ['riwayat', 'histori', 'cetak ulang', 'resi', 'log aktivitas'],
    langkah: [
      'Buka Riwayat Transaksi, cari dengan nomor nota atau nama pelanggan.',
      'Pilih transaksi untuk cetak ulang, kirim resi WhatsApp/email, atau buka Log Aktivitas Transaksi.',
    ],
    halaman: '/kasir/riwayat',
    endpoint: ['GET /api/pos/sales/', 'POST /api/pos/sales/{id}/whatsapp-resi/', 'POST /api/pos/sales/{id}/email-resi/'],
    uat: ['INT-05', 'INT-06'],
  },

  // ───────────────────────────── Pesanan & Produksi
  {
    id: 'klaim-spk',
    modul: 'Pesanan & Produksi',
    judul: 'Ambil pekerjaan (Klaim SPK)',
    ringkas: 'Mengambil SPK dari antrean divisi sebelum dikerjakan.',
    peran: PRODUKSI,
    kataKunci: ['klaim', 'ambil', 'spk', 'antrean', 'pekerjaan'],
    langkah: [
      'Pastikan sudah Mulai Kerja (absen masuk).',
      'Buka Papan Kerja (SPK) > Antrean Global Divisi.',
      'Tekan Klaim Pekerjaan (atau Klaim Semua untuk satu pesanan berisi beberapa item).',
    ],
    halaman: '/produksi',
    endpoint: ['GET /api/jobs/', 'POST /api/jobs/{id}/claim/'],
    uat: ['E2E-01'],
  },
  {
    id: 'kerjakan-spk',
    modul: 'Pesanan & Produksi',
    judul: 'Kerjakan, teruskan, atau selesaikan SPK',
    ringkas: 'Memulai pekerjaan lalu meneruskan ke tahap berikutnya atau menutupnya.',
    peran: PRODUKSI,
    kataKunci: ['mulai spk', 'kerjakan', 'teruskan', 'finalisasi', 'selesai', 'operator', 'editor', 'mesin'],
    langkah: [
      'Buka Papan Kerja (SPK) > Pekerjaan Saya, tekan Mulai SPK pada kartu.',
      'Setelah selesai tekan Finalisasi & Teruskan.',
      'Pilih Teruskan (pilih tahap tujuan dan PIC) atau Selesai (Tutup Job). Isi penggunaan mesin/bahan bila diminta.',
      'Bila semua item selesai, pesanan otomatis menjadi Siap Diambil dan kasir mendapat notifikasi.',
    ],
    halaman: '/produksi',
    endpoint: ['POST /api/jobs/{id}/start/', 'POST /api/jobs/{job_id}/forward/', 'POST /api/jobs/{id}/complete/', 'GET /api/penggunaan-mesin/'],
    uat: ['E2E-01', 'E2E-04'],
    catatan: 'Job dengan kendala mesin wajib ditandai Gagal, tidak bisa diteruskan.',
  },
  {
    id: 'kembalikan-spk',
    modul: 'Pesanan & Produksi',
    judul: 'Kembalikan SPK ke tahap sebelumnya (revisi)',
    ringkas: 'Menolak hasil tahap sebelumnya dengan alasan supaya diperbaiki.',
    peran: PRODUKSI,
    kataKunci: ['kembalikan', 'revisi', 'tolak hasil', 'perbaiki', 'salah cetak'],
    langkah: [
      'Di Pekerjaan Saya buka kartu SPK, pilih Kembalikan ke Tahap Sebelumnya.',
      'Isi alasan, lalu konfirmasi.',
      'Staff tahap sebelumnya memutuskan Terima atau Tolak; bila diterima, SPK kembali ke antreannya untuk diperbaiki.',
    ],
    halaman: '/produksi',
    endpoint: ['POST /api/jobs/{job_id}/kembalikan/', 'GET /api/pengembalian-job/', 'POST /api/pengembalian-job/{pk}/terima/', 'POST /api/pengembalian-job/{pk}/tolak/'],
    uat: ['E2E-08'],
  },
  {
    id: 'buat-order-staff',
    modul: 'Pesanan & Produksi',
    judul: 'Buat Order (oleh staff)',
    ringkas: 'Mencatat pesanan pelanggan yang dilayani staff; kasir yang menerima pembayarannya.',
    peran: PRODUKSI,
    kataKunci: ['buat order', 'order', 'pesanan baru', 'konsumen'],
    langkah: [
      'Buka Buat Order.',
      'Pilih atau tambah pelanggan, tambahkan item pesanan, lalu simpan.',
      'Pesanan masuk Antrean Online & Offline kasir untuk dibayar dan diterbitkan SPK-nya.',
    ],
    halaman: '/buat-order',
    endpoint: ['GET /api/contacts/production-lite/', 'POST /api/orders/', 'POST /api/order-items/'],
    uat: ['E2E-03'],
  },
  {
    id: 'ringkasan-tim',
    modul: 'Pesanan & Produksi',
    judul: 'Pantau pekerjaan tim',
    ringkas: 'Melihat beban dan status pekerjaan anggota tim divisi.',
    peran: ['spv', 'kordiv'],
    kataKunci: ['ringkasan tim', 'tim', 'pantau', 'kinerja'],
    langkah: [
      'Buka Ringkasan Tim.',
      'Lihat SPK yang sedang dikerjakan, antre, dan yang tertunda per anggota.',
    ],
    halaman: '/ringkasan-tim',
    endpoint: ['GET /api/jobs/ringkasan-tim/'],
    uat: ['E2E-08'],
  },
  {
    id: 'papan-kerja-global',
    modul: 'Pesanan & Produksi',
    judul: 'Pantau papan kerja dan atur insentif',
    ringkas: 'Melihat semua SPK lintas divisi dan menyesuaikan insentif pekerjaan.',
    peran: ['owner', 'manager', 'admin'],
    kataKunci: ['papan kerja', 'kanban', 'insentif', 'list order global', 'spk'],
    langkah: [
      'Buka Papan Kerja (SPK). Lihat List Order Global atau papan per divisi.',
      'Buka kartu SPK > Edit untuk mengubah nominal insentif atau menambah baris insentif.',
      'Insentif standar otomatis terisi dari Pengaturan > Jenis Insentif sesuai divisi.',
    ],
    halaman: '/produksi',
    endpoint: ['GET /api/jobs/', 'POST /api/jobs/{job_id}/insentif/', 'PATCH /api/insentif-pekerjaan/{pk}/'],
    uat: ['MD-13'],
  },
  {
    id: 'daftar-pesanan',
    modul: 'Pesanan & Produksi',
    judul: 'Daftar pesanan dan status',
    ringkas: 'Mencari pesanan, melihat status pembayaran dan produksi.',
    peran: OWNER_MANAGER,
    kataKunci: ['pesanan', 'order', 'status', 'cari order'],
    langkah: [
      'Buka Operasional > Pesanan.',
      'Cari nomor pesanan atau nama pelanggan; buka detail untuk melihat item, pembayaran, dan riwayat SPK.',
    ],
    halaman: '/orders',
    endpoint: ['GET /api/orders/', 'GET /api/orders/stats/'],
    uat: ['E2E-03', 'INT-02'],
  },
  {
    id: 'komplain',
    modul: 'Pesanan & Produksi',
    judul: 'Komplain dan garansi',
    ringkas: 'Mencatat dan menindaklanjuti komplain pelanggan.',
    peran: OWNER_MANAGER,
    kataKunci: ['komplain', 'garansi', 'keluhan'],
    langkah: ['Buka Operasional > Komplain & Garansi.', 'Tambah atau buka tiket, perbarui status penyelesaiannya.'],
    halaman: '/komplain',
    endpoint: ['GET /api/komplain/', 'POST /api/komplain/'],
    uat: [],
  },
  {
    id: 'nota-human-error',
    modul: 'Pesanan & Produksi',
    judul: 'Nota Human Error',
    ringkas: 'Melihat catatan kesalahan kerja yang berdampak potongan.',
    peran: ['*'],
    kataKunci: ['human error', 'kesalahan', 'potongan'],
    langkah: ['Buka Nota Human Error.', 'Lihat daftar catatan dan statusnya (sudah dipotong atau belum).'],
    halaman: '/nota-human-error',
    endpoint: ['GET /api/nota-human-error/'],
    uat: [],
  },

  // ───────────────────────────── Bahan Baku
  {
    id: 'permintaan-bahan',
    modul: 'Bahan Baku',
    judul: 'Permintaan bahan baku',
    ringkas: 'Alur Ajukan, Setujui, Siapkan, Terima untuk kebutuhan bahan divisi.',
    peran: ['spv', 'kordiv', 'admin', 'spv_finance'],
    kataKunci: ['bahan', 'permintaan', 'ajukan', 'setujui', 'siapkan', 'terima', 'requisition'],
    langkah: [
      'Kordiv/SPV: buka Permintaan Bahan, tekan Ajukan, Tambah bahan, isi jumlah, kirim.',
      'SPV: Setujui (atau Tolak dengan alasan).',
      'Admin / SPV Finance: Siapkan jumlah yang diberikan.',
      'Pengaju: Terima saat bahan sudah diserahkan.',
    ],
    halaman: '/permintaan-bahan',
    endpoint: ['GET /api/material-requisitions/', 'POST /api/material-requisitions/', 'POST /api/material-requisitions/{id}/setujui/', 'POST /api/material-requisitions/{id}/siapkan/', 'POST /api/material-requisitions/{id}/terima/'],
    uat: ['E2E-04'],
    catatan: 'Dokumen ini tidak mengubah stok; stok berkurang saat bahan dipakai produksi.',
  },

  // ───────────────────────────── Produk & Inventori
  {
    id: 'produk',
    modul: 'Produk & Inventori',
    judul: 'Tambah dan ubah produk',
    ringkas: 'Membuat produk, mengubah harga, dan mengatur ketersediaan jual.',
    peran: KEUANGAN,
    kataKunci: ['produk', 'harga', 'tambah produk', 'nonaktif', 'ketersediaan', 'stok minimum'],
    langkah: [
      'Buka Produk & Inventori > Produk, tekan Tambah Produk.',
      'Isi Nama Produk, Kategori, Satuan, Harga Beli, Harga Jual di Toko, lalu simpan.',
      'Ubah: menu baris > Detail > Ubah. Atur Stok Minimum di sini juga.',
      'Hentikan penjualan: menu baris > Ubah ketersediaan.',
    ],
    halaman: '/product-inventory/product/products',
    endpoint: ['GET /api/products/', 'POST /api/products/', 'PATCH /api/products/{id}/'],
    uat: ['MST-01', 'MST-10', 'INV-06'],
  },
  {
    id: 'kategori-varian',
    modul: 'Produk & Inventori',
    judul: 'Kategori, satuan, dan varian',
    ringkas: 'Mengatur pengelompokan produk dan pilihan varian (ukuran, warna).',
    peran: KEUANGAN,
    kataKunci: ['kategori', 'satuan', 'varian', 'variant', 'ukuran'],
    langkah: [
      'Kategori: Produk & Inventori > Produk, tab Kategori, tambah lalu Simpan.',
      'Satuan: Detail produk > tab Satuan > Tambah.',
      'Varian: Detail produk > tab Variant, atau Manage Variant di daftar; tambah Tipe Variant dan nilainya, Konfirmasi.',
    ],
    halaman: '/product-inventory/product/categories',
    endpoint: ['GET /api/product-categories/', 'POST /api/product-categories/', 'POST /api/product-variants/'],
    uat: ['MST-02', 'MST-05'],
  },
  {
    id: 'resep-bom',
    modul: 'Produk & Inventori',
    judul: 'Resep bahan baku produk (BoM)',
    ringkas: 'Mengatur bahan yang otomatis terpotong saat produk dikerjakan.',
    peran: KEUANGAN,
    kataKunci: ['bom', 'resep', 'bahan baku', 'bill of materials', 'komposisi'],
    langkah: [
      'Buka Produk & Inventori > Produk, buka Detail produk, tab Bahan/Resep.',
      'Tambah bahan dan jumlah pemakaiannya per satu produk, lalu simpan.',
      'Untuk banyak produk sekaligus: menu titik tiga > Import Bahan / Resep.',
    ],
    halaman: '/product-inventory/product/products',
    endpoint: ['GET /api/bom/', 'POST /api/bom/get-or-create-for-product/', 'POST /api/bom-items/create-from-product/', 'POST /api/products/import-recipes/'],
    uat: ['E2E-04'],
  },
  {
    id: 'impor-produk',
    modul: 'Produk & Inventori',
    judul: 'Impor produk dari CSV',
    ringkas: 'Memasukkan banyak produk sekaligus dari berkas CSV.',
    peran: KEUANGAN,
    kataKunci: ['impor', 'import', 'csv', 'migrasi', 'template'],
    langkah: [
      'Buka Produk & Inventori > Produk, tekan menu titik tiga > Import Produk.',
      'Tekan Download Template bila perlu, isi, lalu pilih berkas CSV.',
      'Periksa ringkasan (Total Baris CSV, Akan Dibuat, Akan Diperbarui), tekan Import Sekarang.',
      'Bahan/resep: menu yang sama > Import Bahan / Resep.',
    ],
    halaman: '/product-inventory/product/products',
    endpoint: ['POST /api/products/import-products/'],
    uat: ['MIG-01', 'MIG-02', 'MIG-04'],
  },
  {
    id: 'stok-masuk',
    modul: 'Produk & Inventori',
    judul: 'Stok masuk dan terima barang pembelian',
    ringkas: 'Mencatat barang datang, termasuk penerimaan sebagian.',
    peran: KEUANGAN,
    kataKunci: ['stok masuk', 'terima', 'penerimaan', 'parsial', 'sebagian', 'restock'],
    langkah: [
      'Buka Produk & Inventori > Inventori, tab Stok Masuk, tekan Tambah.',
      'Pilih Terima dari Pembelian (untuk barang yang dipesan) atau Tambah Stok Masuk.',
      'Ubah qty bila barang datang kurang; sisanya diterima kemudian lewat Terima Sisa di dokumen pembelian.',
      'Simpan dan posting.',
    ],
    halaman: '/product-inventory/inventory/stock-in',
    endpoint: ['GET /api/stock-in-documents/', 'POST /api/stock-in-documents/', 'GET /api/purchases/'],
    uat: ['INV-05', 'E2E-04'],
  },
  {
    id: 'stok-keluar',
    modul: 'Produk & Inventori',
    judul: 'Stok keluar (rusak, kedaluwarsa, transfer)',
    ringkas: 'Mengurangi stok di luar penjualan dengan alasan.',
    peran: KEUANGAN,
    kataKunci: ['stok keluar', 'rusak', 'kadaluarsa', 'transfer'],
    langkah: [
      'Buka Inventori, tab Stok Keluar, tekan Tambah > Tambah Stok Keluar (atau Transfer ke Toko).',
      'Pilih produk, qty, dan alasan (Rusak, Kadaluarsa, dan lainnya), lalu simpan dan posting.',
    ],
    halaman: '/product-inventory/inventory/stock-out',
    endpoint: ['POST /api/stock-out-documents/'],
    uat: ['INV-06', 'INV-08'],
    catatan: 'Qty melebihi stok ditolak dengan pesan "Stok tidak cukup".',
  },
  {
    id: 'stok-opname',
    modul: 'Produk & Inventori',
    judul: 'Stok opname (hitung fisik)',
    ringkas: 'Menyesuaikan stok sistem dengan hasil hitung fisik beserta alasannya.',
    peran: KEUANGAN,
    kataKunci: ['opname', 'hitung fisik', 'penyesuaian', 'selisih'],
    langkah: [
      'Buka Inventori, tab Stok Opname, tekan Tambah.',
      'Pilih produk, isi qty hasil hitung fisik, isi Catatan sebagai alasan.',
      'Tekan Draf untuk simpan sementara atau Posting Sekarang untuk menerapkan.',
    ],
    halaman: '/product-inventory/inventory/stock-opname',
    endpoint: ['GET /api/stock-opname-documents/', 'POST /api/stock-opname-documents/'],
    uat: ['INV-09', 'GLV-06'],
  },
  {
    id: 'pergerakan-stok',
    modul: 'Produk & Inventori',
    judul: 'Riwayat pergerakan stok',
    ringkas: 'Menelusuri stok masuk, keluar, dan penyesuaian per produk atau bahan.',
    peran: KEUANGAN,
    kataKunci: ['pergerakan', 'mutasi', 'riwayat stok', 'kartu stok', 'bahan baku'],
    langkah: [
      'Buka Inventori, tab Pergerakan Stok. Pilih sub-tab Produk atau Bahan Baku dan rentang tanggal.',
      'Tekan ikon riwayat pada baris untuk melihat siapa, kapan, dan keterangannya.',
      'Unduh dengan Download Excel.',
    ],
    halaman: '/product-inventory/inventory/stock-movement',
    endpoint: ['GET /api/product-stock-movements/', 'GET /api/export/stock-movement/'],
    uat: ['INV-01', 'INV-10'],
  },
  {
    id: 'peringatan-stok',
    modul: 'Produk & Inventori',
    judul: 'Peringatan stok minimum',
    ringkas: 'Mengatur penerima email dan melihat produk di bawah stok minimum.',
    peran: KEUANGAN,
    kataKunci: ['stok minimum', 'menipis', 'peringatan', 'email stok', 'habis'],
    langkah: [
      'Atur Stok Minimum di Detail produk.',
      'Buka Inventori, tab Email Peringatan Stok untuk menambah/menghapus email penerima.',
      'Peringatan juga muncul di ikon lonceng dan di Dashboard.',
    ],
    halaman: '/product-inventory/inventory/stock-alert',
    endpoint: ['GET /api/notifikasi-stok/', 'PATCH /api/products/{id}/'],
    uat: ['INV-06', 'PRE-08'],
  },

  // ───────────────────────────── Pelanggan & Supplier
  {
    id: 'pelanggan',
    modul: 'Pelanggan & Supplier',
    judul: 'Data pelanggan',
    ringkas: 'Menambah, mengubah, dan mencari pelanggan.',
    peran: KEUANGAN,
    kataKunci: ['pelanggan', 'customer', 'konsumen', 'tipe pelanggan', 'dobel', 'duplikat', 'nomor wa'],
    langkah: [
      'Buka Pelanggan & Supplier, tab pelanggan, tekan tambah.',
      'Isi Nama dan Nomor WhatsApp (wajib). Satu nomor WA hanya untuk satu pelanggan; nomor yang sudah terdaftar ditolak. Email opsional.',
      'Simpan. Ubah lewat menu baris > Edit.',
    ],
    halaman: '/customer-supplier',
    endpoint: ['GET /api/customers/', 'POST /api/customers/', 'PATCH /api/customers/{id}/'],
    uat: ['PRE-03', 'SEC-04'],
  },
  {
    id: 'supplier',
    modul: 'Pelanggan & Supplier',
    judul: 'Data supplier',
    ringkas: 'Mengelola pemasok untuk pembelian.',
    peran: KEUANGAN,
    kataKunci: ['supplier', 'pemasok', 'vendor'],
    langkah: ['Buka Pelanggan & Supplier, tab supplier.', 'Tambah atau ubah data supplier, lalu simpan.'],
    halaman: '/customer-supplier',
    endpoint: ['GET /api/suppliers/', 'POST /api/suppliers/'],
    uat: [],
  },

  // ───────────────────────────── Keuangan
  {
    id: 'pembelian',
    modul: 'Keuangan',
    judul: 'Pembelian ke supplier',
    ringkas: 'Membuat pembelian, lalu menerima barangnya ke stok.',
    peran: KEUANGAN,
    kataKunci: ['pembelian', 'beli', 'purchase', 'pengadaan', 'hutang'],
    langkah: [
      'Buka Transaksi & Pembayaran > Pembelian, tekan Tambah.',
      'Pilih supplier, produk, qty, dan harga, lalu simpan.',
      'Saat barang datang buka dokumen pembelian > Info Penerimaan > Terima (atau Terima Sisa).',
    ],
    halaman: '/transaksi/pembelian',
    endpoint: ['GET /api/purchases/', 'POST /api/purchases/', 'POST /api/purchases/{pk}/workflow/{action}/'],
    uat: ['INV-05', 'E2E-04'],
  },
  {
    id: 'pendapatan-pengeluaran',
    modul: 'Keuangan',
    judul: 'Pendapatan dan pengeluaran',
    ringkas: 'Mencatat pemasukan/pengeluaran di luar penjualan.',
    peran: KEUANGAN,
    kataKunci: ['pengeluaran', 'pendapatan', 'biaya', 'kas'],
    langkah: ['Buka Transaksi & Pembayaran > Pendapatan/Pengeluaran, tekan Tambah.', 'Pilih jenis, akun, nominal, dan keterangan, lalu simpan.'],
    halaman: '/transaksi/pendapatan-pengeluaran',
    endpoint: ['GET /api/cash-transactions/', 'POST /api/cash-transactions/'],
    uat: [],
  },
  {
    id: 'verifikasi-setoran',
    modul: 'Keuangan',
    judul: 'Verifikasi setoran shift dan kas',
    ringkas: 'Memeriksa setoran kasir per shift dan pengeluaran kas kecil.',
    peran: ['admin_finance'],
    kataKunci: ['verifikasi', 'setoran', 'shift', 'pertanyakan', 'kas kecil'],
    langkah: [
      'Buka Dashboard (Finance), bagian Antrean Setoran Kas Shift.',
      'Cocokkan setoran dengan uang yang diterima, tekan verifikasi. Bila janggal, tekan pertanyakan dan isi catatan.',
      'Verifikasi juga pengeluaran/kas kecil yang masuk antrean.',
    ],
    halaman: '/finance-dashboard',
    endpoint: ['GET /api/finance/dashboard-admin-finance/', 'POST /api/ringkasan-shift/{id}/verifikasi/', 'POST /api/ringkasan-shift/{id}/pertanyakan/', 'POST /api/cash-transactions/{id}/verifikasi-admin-finance/'],
    uat: ['E2E-01'],
  },
  {
    id: 'rekap-shift',
    modul: 'Keuangan',
    judul: 'Rekap penjualan harian dan ringkasan shift',
    ringkas: 'Melihat rekap penjualan hari sebelumnya dan kas tiap shift.',
    peran: ['admin_finance', 'spv_finance'],
    kataKunci: ['rekap', 'harian', 'ringkasan shift', 'penjualan harian'],
    langkah: ['Buka Laporan & Rekap > Rekap Penjualan Harian atau Ringkasan Shift.', 'Pilih tanggal; buka baris untuk detail.'],
    halaman: '/rekap-harian',
    endpoint: ['GET /api/pos/sales/rekap-harian/', 'GET /api/ringkasan-shift/'],
    uat: ['E2E-01'],
  },
  {
    id: 'piutang',
    modul: 'Keuangan',
    judul: 'Daftar piutang pelanggan',
    ringkas: 'Melihat pesanan yang belum lunas beserta sisa tagihannya.',
    peran: ['owner', 'manager', 'admin', 'spv_finance'],
    kataKunci: ['piutang', 'belum lunas', 'sisa tagihan', 'jatuh tempo'],
    langkah: ['Buka Akuntansi Internal, menu Piutang > Semua Piutang.', 'Atur rentang tanggal; buka baris untuk detail pembayaran.'],
    halaman: '/accounting-internal',
    endpoint: ['GET /api/orders/?confirmed=true'],
    uat: ['E2E-07'],
  },
  {
    id: 'laporan-akuntansi',
    modul: 'Keuangan',
    judul: 'Laba rugi, neraca, arus kas, jurnal',
    ringkas: 'Membaca laporan keuangan dan jurnal yang terbentuk otomatis.',
    peran: ['owner', 'manager', 'admin', 'spv_finance'],
    kataKunci: ['laba rugi', 'neraca', 'arus kas', 'jurnal', 'buku besar', 'log jurnal', 'akuntansi'],
    langkah: [
      'Buka Akuntansi Internal.',
      'Pilih menu Laporan Akuntansi (Laba Rugi, Neraca, Perubahan Modal, Arus Kas), atau Jurnal & Buku Besar.',
      'Log Jurnal mencatat siapa mengubah jurnal dan kapan.',
    ],
    halaman: '/accounting-internal',
    endpoint: ['GET /api/accounting/reports/income-statement/', 'GET /api/accounting/reports/balance-sheet/', 'GET /api/accounting/reports/cash-flow/', 'GET /api/accounting/journal-entries/', 'GET /api/accounting/ledger/', 'GET /api/accounting/journal-audit-logs/'],
    uat: ['E2E-01', 'E2E-09', 'INT-05'],
  },
  {
    id: 'posting-gaji',
    modul: 'Keuangan',
    judul: 'Posting dan bayar gaji',
    ringkas: 'Membukukan slip gaji yang sudah dikonfirmasi HR, lalu membayarnya.',
    peran: OWNER_MANAGER,
    kataKunci: ['gaji', 'payroll', 'posting gaji', 'slip', 'hutang gaji'],
    langkah: [
      'HR mengonfirmasi slip gaji di aplikasi HR.',
      'Buka Akuntansi Internal > Jurnal & Buku Besar > Posting Gaji.',
      'Tekan pratinjau, periksa angka, posting, lalu bayar.',
      'Jurnal Biaya gaji dan Hutang gaji terbentuk otomatis.',
    ],
    halaman: '/accounting-internal',
    endpoint: ['GET /api/accounting/payroll/pratinjau/', 'POST /api/accounting/payroll/posting/', 'POST /api/accounting/payroll/bayar/', 'GET /api/accounting/payroll/riwayat/'],
    uat: ['E2E-05'],
    catatan: 'Potongan BPJS belum ikut Posting Gaji.',
  },

  // ───────────────────────────── Laporan & Dashboard
  {
    id: 'dashboard-eksekutif',
    modul: 'Laporan & Dashboard',
    judul: 'Dashboard dan AI Business Analyst',
    ringkas: 'Ringkasan penjualan, produksi, HR, dan CRM; tanya jawab analisis bisnis.',
    peran: OWNER_MANAGER,
    kataKunci: ['dashboard', 'ringkasan', 'ai', 'analisis', 'eksekutif'],
    langkah: [
      'Buka Dashboard. Tab Ringkasan berisi angka utama, tab Operasional berisi absensi, persetujuan void, dan komplain.',
      'Tab AI Business Analyst: tanya analisis kesehatan atau strategi perusahaan.',
    ],
    halaman: '/dashboard-eksekutif',
    endpoint: ['GET /api/insights/combined/', 'POST /api/ai-business-analyst/chat/'],
    uat: ['E2E-10', 'AIA-09', 'PRF-01'],
  },
  {
    id: 'survei-kepuasan',
    modul: 'Pelanggan & Supplier',
    judul: 'Struk online dan survei kepuasan',
    ringkas: 'Pelanggan membuka struk online dari WhatsApp dan memberi nilai bintang; hasilnya direkap di sini.',
    peran: OWNER_MANAGER,
    kataKunci: ['survei', 'kepuasan', 'rating', 'bintang', 'struk online', 'e-receipt', 'resi'],
    langkah: [
      'Resi kasir dan invoice pesanan yang dikirim lewat WhatsApp otomatis membawa tautan struk online.',
      'Pelanggan membuka tautan, melihat rincian transaksi, lalu memberi nilai 1-5 per aspek (sekali per transaksi).',
      'Buka Pelanggan & Supplier > tab Kepuasan Pelanggan untuk melihat rata-rata per aspek dan daftar tanggapan; saring per tanggal.',
      'Atur aspek penilaian di kotak Aspek Penilaian: tambah, nonaktifkan, atau hapus aspek yang belum pernah dinilai.',
    ],
    halaman: '/customer-supplier/satisfaction',
    endpoint: ['GET /api/survei-kepuasan/', 'GET /api/aspek-survei/'],
    uat: [],
  },
  {
    id: 'laporan-penjualan',
    modul: 'Laporan & Dashboard',
    judul: 'Laporan penjualan',
    ringkas: 'Laporan penjualan, produk terlaris, dan rincian transaksi.',
    peran: KEUANGAN,
    kataKunci: ['laporan', 'penjualan', 'export', 'excel'],
    langkah: ['Buka Laporan dan Pembukuan > Laporan (Finance: Laporan & Rekap > Laporan Penjualan).', 'Pilih jenis laporan dan periode; unduh bila perlu.'],
    halaman: '/laporan/laporan',
    endpoint: ['GET /api/reports/{report_id}/', 'GET /api/reports/{report_id}/export/'],
    uat: ['E2E-02'],
  },

  // ───────────────────────────── Pengaturan
  {
    id: 'akun-karyawan',
    modul: 'Pengaturan',
    judul: 'Akun karyawan dan hak akses',
    ringkas: 'Melihat akun, mengubah peran, dan mengatur hak akses menu.',
    peran: OWNER_MANAGER,
    kataKunci: ['karyawan', 'akun', 'role', 'peran', 'hak akses', 'user'],
    langkah: [
      'Buka Pengaturan > Toko, tab Karyawan untuk daftar akun. Hanya Owner yang dapat mengubah role akun.',
      'Tab Hak Akses untuk mengatur menu tiap peran, lalu Simpan Hak Akses.',
      'Karyawan baru sebaiknya dibuat di aplikasi HR supaya akunnya terhubung ke semua aplikasi.',
    ],
    halaman: '/settings/toko',
    endpoint: ['GET /api/users/', 'PATCH /api/users/{id}/'],
    uat: ['AKS-14', 'PRE-04', 'GLV-07'],
  },
  {
    id: 'jenis-insentif',
    modul: 'Pengaturan',
    judul: 'Jenis insentif',
    ringkas: 'Master insentif standar per divisi yang otomatis masuk ke SPK.',
    peran: ['owner', 'manager', 'admin'],
    kataKunci: ['insentif', 'bonus', 'jenis insentif'],
    langkah: ['Buka Pengaturan > Jenis Insentif, tekan Tambah Jenis.', 'Isi Nama, Nominal standar, centang Divisi target dan Aktif, lalu Simpan.'],
    halaman: '/settings/insentif',
    endpoint: ['GET /api/jenis-insentif/', 'POST /api/jenis-insentif/'],
    uat: ['MD-07'],
  },
  {
    id: 'divisi-tahap',
    modul: 'Pengaturan',
    judul: 'Divisi dan tahap proses',
    ringkas: 'Melihat divisi dan urutan tahap produksi (berasal dari HR).',
    peran: OWNER_MANAGER,
    kataKunci: ['divisi', 'tahap', 'departemen', 'alur produksi'],
    langkah: [
      'Buka HR & Kepegawaian > Divisi & Tahap.',
      'Divisi berasal dari Departemen HR, tahap dari Peran di Jabatan HR. Ubah di HR supaya ikut tersinkron.',
    ],
    halaman: '/divisi',
    endpoint: ['GET /api/divisi/', 'GET /api/tahap-proses/'],
    uat: ['MD-02', 'MD-04'],
  },
  {
    id: 'pengaturan-pos',
    modul: 'Pengaturan',
    judul: 'Pengaturan Point Of Sale',
    ringkas: 'Aturan kasir: metode bayar, blokir jual stok kosong, dan lainnya.',
    peran: ['owner', 'manager', 'admin', 'spv_finance'],
    kataKunci: ['pos', 'pengaturan kasir', 'metode bayar', 'blokir', 'stok kosong'],
    langkah: ['Buka Pengaturan > Point Of Sale.', 'Nyalakan/matikan aturan yang diperlukan, lalu simpan.'],
    halaman: '/settings/point-of-sale',
    endpoint: ['GET /api/business-settings/', 'GET /api/pos-payment-methods/'],
    uat: ['INV-08', 'MST-10'],
  },
  {
    id: 'notifikasi',
    modul: 'Pengaturan',
    judul: 'Pengaturan notifikasi',
    ringkas: 'Menyalakan atau mematikan notifikasi WhatsApp dan email otomatis.',
    peran: ['owner', 'manager', 'admin'],
    kataKunci: ['notifikasi', 'whatsapp', 'email', 'pemberitahuan'],
    langkah: ['Buka Pengaturan > Notifikasi.', 'Atur saklar tiap notifikasi, lalu simpan.'],
    halaman: '/settings/notifikasi',
    endpoint: ['GET /api/business-settings/'],
    uat: ['PRE-08'],
  },
  {
    id: 'wa-bot',
    modul: 'Pengaturan',
    judul: 'Pengaturan WA Bot',
    ringkas: 'Statistik, koneksi WhatsApp, AI, FAQ, dan pricelist bot pelanggan.',
    peran: ['manager'],
    kataKunci: ['bot', 'wa bot', 'whatsapp', 'faq', 'pricelist', 'prompt'],
    langkah: ['Buka Pengaturan WA Bot.', 'Pilih tab: Statistik, WhatsApp Gateway, Koneksi AI, Prompt AI, Tools, FAQ, atau Pricelist.'],
    halaman: '/pengaturan-wa-bot',
    endpoint: ['GET /api/wa-pricelist/', 'GET /api/faq/'],
    uat: ['PRE-06', 'PRF-05'],
  },

  // ───────────────────────────── HR & CRM (aplikasi lain)
  {
    id: 'hr-karyawan',
    modul: 'HR & CRM',
    judul: 'Data karyawan, cuti, lembur, slip gaji (HR)',
    ringkas: 'Urusan kepegawaian ada di aplikasi HR; akun ERP ikut otomatis.',
    peran: ['*'],
    kataKunci: ['hr', 'karyawan', 'cuti', 'lembur', 'slip gaji', 'kontrak', 'mobile'],
    langkah: [
      'Buka aplikasi HR di browser atau aplikasi mobile HR, login dengan akun yang sama.',
      'Karyawan: ajukan cuti/lembur dan lihat slip gaji. Atasan: setujui pengajuan.',
      'Admin HR: tambah/ubah karyawan; akun ERP/CRM, divisi, dan tahap ikut otomatis.',
    ],
    halamanLuar: URL_HR,
    endpoint: [],
    uat: ['E2E-05', 'E2E-06', 'PRE-05'],
  },
  {
    id: 'crm-prospek',
    modul: 'HR & CRM',
    judul: 'Prospek dan campaign (CRM)',
    ringkas: 'Penjualan dan pemasaran dikelola di aplikasi CRM.',
    peran: OWNER_MANAGER,
    kataKunci: ['crm', 'prospek', 'lead', 'campaign', 'sales'],
    langkah: [
      'Buka aplikasi CRM, login dengan akun yang sama.',
      'Catat prospek dan follow-up; ubah prospek menjadi pesanan.',
      'Pesanan masuk Antrean Online & Offline kasir di ERP.',
    ],
    halamanLuar: URL_CRM,
    endpoint: [],
    uat: ['E2E-03'],
  },
];

export function bolehUntukPeran(layanan, peran) {
  return layanan.peran.includes('*') || layanan.peran.includes(peran);
}

export function halamanUntukPeran(layanan, peran) {
  if (!layanan.halaman) return null;
  return typeof layanan.halaman === 'string' ? layanan.halaman : layanan.halaman[peran] || null;
}

const normal = (t) => String(t || '').toLowerCase();

export function cariLayanan(daftar, kata) {
  const q = normal(kata).trim();
  if (!q) return daftar;
  const potongan = q.split(/\s+/);
  return daftar
    .map((l) => {
      const judul = normal(l.judul);
      const teks = [l.judul, l.ringkas, l.modul, ...(l.kataKunci || []), ...(l.uat || []), ...(l.langkah || [])]
        .map(normal)
        .join(' ');
      if (!potongan.every((p) => teks.includes(p))) return null;
      const skor = potongan.reduce((s, p) => s + (judul.includes(p) ? 3 : 0) + ((l.kataKunci || []).some((k) => normal(k).includes(p)) ? 2 : 0), 0);
      return { l, skor };
    })
    .filter(Boolean)
    .sort((a, b) => b.skor - a.skor)
    .map((x) => x.l);
}
