# Generated by Django 5.2.16 on 2026-07-24 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_start_date', models.DateField(help_text='Tanggal mulai akuntansi berlaku. Entry sebelum tanggal ini tidak diperbolehkan.')),
                ('default_payment_due_days', models.PositiveIntegerField(default=0, help_text='Jatuh tempo pembayaran default (hari) untuk Piutang/Hutang baru.')),
                ('reminder_days_before_due', models.PositiveIntegerField(default=0, help_text='Kirim pengingat berapa hari sebelum jatuh tempo.')),
                ('send_ar_due_email', models.BooleanField(default=False, help_text='Kirim email otomatis saat piutang jatuh tempo.')),
                ('is_ppn_active', models.BooleanField(default=False, help_text='Aktifkan pemungutan pajak PPN.')),
                ('ppn_rate_percent', models.DecimalField(decimal_places=2, default=0, help_text='Tarif PPN (%), dipakai kalau is_ppn_active aktif.', max_digits=5)),
                ('show_inventory_in_profit_loss', models.BooleanField(default=True, help_text='Tampilkan nilai inventori di laporan Laba Rugi.')),
                ('calculate_coa_from_this_year', models.BooleanField(default=False, help_text='Hitung saldo Chart of Accounts mulai dari tahun berjalan saja.')),
                ('enable_ojek_online_fee', models.BooleanField(default=False)),
                ('enable_marketplace_sales', models.BooleanField(default=False)),
                ('enable_mdr_fee', models.BooleanField(default=False)),
                ('enable_sales_commission', models.BooleanField(default=False)),
                ('enable_multi_branch_closing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Akuntansi',
                'verbose_name_plural': 'Pengaturan Akuntansi',
                'db_table': 'accounting_settings',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Misal: 1-1000, 4-1000', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('asset', 'Aset'), ('liability', 'Kewajiban'), ('equity', 'Ekuitas'), ('revenue', 'Pendapatan'), ('expense', 'Beban')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Akun',
                'verbose_name_plural': 'Daftar Akun',
                'db_table': 'accounting_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Terbuka'), ('closed', 'Ditutup')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_periods_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Periode Akuntansi',
                'verbose_name_plural': 'Periode Akuntansi',
                'db_table': 'accounting_period',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='CashBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('cash', 'Kas'), ('bank', 'Bank')], max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_bank_account', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Akun Kas & Bank',
                'verbose_name_plural': 'Kas & Bank',
                'db_table': 'accounting_cash_bank_account',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('pos_sale', 'Penjualan POS'), ('purchase', 'Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('cash_transaction', 'Transaksi Kas'), ('capital_transfer', 'Transfer Modal')], default='manual', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='ID dokumen sumber, sesuai source_type.', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Terposting'), ('void', 'Dibatalkan')], default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL)),
                ('reversed_entry', models.ForeignKey(blank=True, help_text='Diisi kalau entry ini adalah jurnal koreksi/pembalik dari entry lain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnal Umum',
                'db_table': 'accounting_journal_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Dibuat'), ('posted', 'Diposting'), ('voided', 'Dibatalkan'), ('reversed', 'Dijurnal-balik')], max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Log Jurnal',
                'verbose_name_plural': 'Log Jurnal',
                'db_table': 'accounting_journal_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('kredit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Baris Jurnal',
                'verbose_name_plural': 'Baris Jurnal',
                'db_table': 'accounting_journal_entry_line',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mdr_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('cash_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='accounting.cashbankaccount')),
            ],
            options={
                'verbose_name': 'Cara Pembayaran',
                'verbose_name_plural': 'Cara Pembayaran',
                'db_table': 'accounting_payment_method',
            },
        ),
        migrations.CreateModel(
            name='ProductAccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Grup Akun Produk',
                'verbose_name_plural': 'Grup Akun Produk',
                'db_table': 'accounting_product_account_group',
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='idx_je_date'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='idx_je_source'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='idx_jel_account'),
        ),
    ]
