# Generated by Django 5.2.16 on 2026-07-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='accountingsettings',
            name='stopped_at',
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='enable_product_account_group',
            field=models.BooleanField(default=False, help_text='Aktifkan pengelompokan akun berdasarkan grup produk (ProductAccountGroup).'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='enable_transfer_between_stores_as_sale',
            field=models.BooleanField(default=False, help_text='Catat transfer stok antar toko sebagai transaksi penjualan.'),
        ),
        migrations.CreateModel(
            name='AccountingLifecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Start/Stop Akuntansi',
                'verbose_name_plural': 'Log Start/Stop Akuntansi',
                'db_table': 'accounting_lifecycle_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
