# Generated by Django 5.2.16 on 2026-07-24 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_accountingsettings_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('asset', 'Aset'), ('liability', 'Kewajiban'), ('equity', 'Ekuitas'), ('revenue', 'Pendapatan'), ('expense', 'Beban')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil di laporan.')),
            ],
            options={
                'verbose_name': 'Klasifikasi Akun',
                'verbose_name_plural': 'Klasifikasi Akun',
                'db_table': 'accounting_account_classification',
                'ordering': ['account_type', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='Misal: 11101, 41000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountclassification'),
        ),
    ]
