# Generated by Django 5.2.16 on 2026-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountclassification_alter_account_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_contra',
            field=models.BooleanField(default=False, help_text='Akun kontra (saldo normal kebalikan dari account_type) — mis. Akumulasi Penyusutan (kontra-Aset), Prive (kontra-Ekuitas), Retur/Potongan Penjualan (kontra-Pendapatan).'),
        ),
    ]
