# Generated by Django 5.2.16 on 2026-07-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Catatan/keterangan akun — kapan dipakai, aturan khusus, dll.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='opening_balance_equity_account',
            field=models.ForeignKey(blank=True, help_text="Akun penyeimbang otomatis saat mengisi Saldo Awal di Daftar Akun (menu gerigi 'Sesuaikan Saldo Awal'). Default: akun 'Saldo Awal' bawaan — ganti di sini kalau mau diarahkan ke akun lain, tidak perlu ubah kode.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
