# Generated by Django 5.2.16 on 2026-07-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_account_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclassification',
            name='code_range_end',
            field=models.PositiveIntegerField(blank=True, help_text='Batas atas kode akun yang valid untuk klasifikasi ini.', null=True),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='code_range_start',
            field=models.PositiveIntegerField(blank=True, help_text='Batas bawah kode akun yang valid untuk klasifikasi ini.', null=True),
        ),
    ]
