# Generated by Django 5.2.16 on 2026-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountclassification_code_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(blank=True, help_text="Nomor jurnal otomatis, mis. JU-202607-0001. Dicari lewat 'Cari No. Transaksi'.", max_length=30, unique=True),
        ),
    ]
