# Generated by Django 5.2.16 on 2026-07-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_journalentry_entry_number'),
        ('api', '0085_order_metode_diskon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
                'db_table': 'accounting_department',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='external_document_no',
            field=models.CharField(blank=True, default='', help_text='No. Dokumen — nomor referensi bukti fisik (nota/kuitansi/invoice), opsional.', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.customer'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.supplier'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.department'),
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_kredit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Nama Jurnal',
                'verbose_name_plural': 'Nama Jurnal',
                'db_table': 'accounting_journal_template',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.journaltemplate'),
        ),
    ]
