# Generated by Django 5.2.16 on 2026-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_department_journalentry_external_document_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='external_document_no',
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='external_document_no',
            field=models.CharField(blank=True, default='', help_text='No. Dokumen — nomor referensi bukti fisik (nota/kuitansi/invoice) untuk baris ini.', max_length=50),
        ),
    ]
