# Generated by Django 5.2.16 on 2026-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_paymentmethod_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(help_text="Nama pengenal, mis. 'Marketplace Tokopedia'.", max_length=100, unique=True),
        ),
    ]
