# Generated by Django 5.2.16 on 2026-07-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_paymentmethod_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbankaccount',
            name='kind',
            field=models.CharField(blank=True, choices=[('cash', 'Kas'), ('bank', 'Bank'), ('other', 'Lainnya')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('mutation_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('mutation_type', models.CharField(choices=[('debit', 'Debit (uang keluar)'), ('kredit', 'Kredit (uang masuk)')], max_length=10)),
                ('bank_saldo', models.DecimalField(decimal_places=0, help_text='Saldo berjalan versi bank (dari file statement), bukan hasil hitung sistem.', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_lines', to='accounting.account')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matched_journal_entry', models.ForeignKey(blank=True, help_text='Diisi saat rekonsiliasi menemukan/membuat entry yang cocok.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Baris Bank Statement',
                'verbose_name_plural': 'Bank Statement',
                'db_table': 'accounting_bank_statement_line',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'date'], name='idx_bsl_account_date')],
            },
        ),
    ]
