# Generated by Django 5.2.16 on 2026-07-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_cashbankaccount_kind_bankstatementline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatementline',
            name='matched_journal_entry',
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_journal_entry_line',
            field=models.ForeignKey(blank=True, help_text='Baris jurnal spesifik yang cocok — bukan FK ke entry, karena 1 entry (Multi Jurnal) bisa punya beberapa baris ke akun yang sama.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentryline'),
        ),
    ]
