# Generated by Django 5.2.16 on 2026-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='initial_setup_completed_at',
            field=models.DateTimeField(blank=True, help_text="Diisi otomatis saat wizard 'Pengaturan Awal' selesai (tombol Mulai di step Ringkasan). Null berarti belum pernah setup — halaman Pengaturan Akuntansi menampilkan empty state 'Atur Sekarang' sampai field ini terisi.", null=True),
        ),
    ]
