# Generated by Django 5.2.16 on 2026-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_backfill_initial_setup_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ignore_minus_closing',
            field=models.BooleanField(default=False),
        ),
    ]
