# Generated by Django 5.2.16 on 2026-07-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_account_ignore_minus_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_ppn_output_account',
            field=models.ForeignKey(blank=True, help_text='Akun PPN Keluaran default untuk penjualan POS.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_sales_revenue_account',
            field=models.ForeignKey(blank=True, help_text='Akun pendapatan default untuk penjualan POS.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_cash',
            field=models.BooleanField(default=False, help_text='True bila ini adalah pembayaran kas/tunai fisik (tidak melalui batch settlement).'),
        ),
    ]
