# Generated by Django 5.2.16 on 2026-07-28 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_order_payment_journal_support'),
        ('api', '0089_order_referensi_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='settlement_status',
            field=models.CharField(choices=[('not_applicable', 'Tidak berlaku'), ('unsettled', 'Belum settle'), ('settled', 'Sudah settle'), ('void', 'Dibatalkan')], default='not_applicable', max_length=20),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account', 'settlement_status'], name='idx_jel_settlement'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'date'), name='uniq_je_source_date'),
        ),
    ]
