# Generated by Django 5.2.16 on 2026-07-30 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='komisi_penjualan_debit_account',
            field=models.ForeignKey(blank=True, help_text='Akun debit default untuk posting komisi penjualan (mis. Beban Komisi).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='komisi_penjualan_kredit_account',
            field=models.ForeignKey(blank=True, help_text='Akun kredit default untuk posting komisi penjualan (mis. Hutang ke Brand).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
