# Generated by Django 5.0.14 on 2026-07-30 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_accountingsettings_komisi_penjualan_debit_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=0, max_digits=15)),
                ('residual_value', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('is_opening_balance', models.BooleanField(default=False)),
                ('external_document_no', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('disposed', 'Dilepas')], default='active', max_length=12)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_accumulated_depreciation', to='accounting.account')),
                ('acquisition_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_acquisition', to='accounting.journalentry')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account')),
                ('counter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_counter_entries', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.department')),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_expenses', to='accounting.account')),
                ('journal_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.journaltemplate')),
            ],
            options={
                'db_table': 'accounting_fixed_asset',
                'ordering': ['-acquisition_date', '-id'],
                'indexes': [models.Index(fields=['acquisition_date'], name='idx_asset_acquisition_date'), models.Index(fields=['status'], name='idx_asset_status')],
            },
        ),
    ]
