# Generated by Django 5.2.16 on 2026-07-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_fixed_asset_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Dibuat'), ('posted', 'Diposting'), ('voided', 'Dibatalkan'), ('reversed', 'Dijurnal-balik'), ('deleted', 'Dihapus')], max_length=10),
        ),
    ]
