# Generated by Django 5.2.16 on 2026-07-31 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_journal_audit_log_deleted_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='closing_account',
            field=models.ForeignKey(blank=True, help_text="Akun Closing (Laba Ditahan) — akun ekuitas tujuan laba/rugi periode berjalan. Dipakai untuk memberi label akun nyata pada baris 'Pendapatan periode ini' di laporan Neraca. Tidak membuat jurnal penutup baru — laporan tetap dihitung langsung dari jurnal posted per rentang tanggal (lihat get_balance_sheet), supaya laporan periode lama tidak berubah setelah tutup buku.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
