# Generated by Django 5.2.16 on 2026-08-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_accountingsettings_closing_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_cogs_expense_account',
            field=models.ForeignKey(blank=True, help_text='Akun Harga Pokok Penjualan (HPP) untuk penjualan POS produk berlacak inventori (T-107).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_inventory_account',
            field=models.ForeignKey(blank=True, help_text='Akun Persediaan yang dikurangi (kredit) saat HPP penjualan POS diposting (T-107).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
