# Generated by Django 5.2.16 on 2026-08-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_accountingsettings_pos_cogs_expense_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='order_hpp_expense_account',
            field=models.ForeignKey(blank=True, help_text='Akun HPP untuk bahan baku Order yang terpakai via JobBoard, diposting saat Order diselesaikan (T-204). Boleh diarahkan ke akun sama dengan pos_cogs_expense_account kalau COA tidak membedakan HPP produk jadi vs bahan baku produksi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='order_material_inventory_account',
            field=models.ForeignKey(blank=True, help_text='Akun Persediaan Bahan Baku yang dikurangi (kredit) saat HPP Order diposting (T-204).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset'), ('order_material_hpp', 'HPP Bahan Baku Order (T-204)')], default='manual', max_length=20),
        ),
    ]
