# Generated by Django 6.0 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0035_accountingsettings_order_hpp_expense_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="purchase_advance_account",
            field=models.ForeignKey(blank=True, help_text="Akun Uang Muka Pembelian untuk DP sebelum barang diterima.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="accounting.account"),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="purchase_inventory_account",
            field=models.ForeignKey(blank=True, help_text="Akun Persediaan yang didebit saat Stok Masuk dari Pembelian diposting.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="accounting.account"),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="purchase_payable_account",
            field=models.ForeignKey(blank=True, help_text="Akun Hutang Dagang yang dikredit saat Stok Masuk dari Pembelian diposting.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="accounting.account"),
        ),
    ]
