# Generated by Django 5.2.17 on 2026-09-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_purchase_account_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsettings',
            name='closing_account',
            field=models.ForeignKey(blank=True, help_text='Akun Closing (Laba Ditahan) — akun ekuitas tujuan laba/rugi periode berjalan. WAJIB diisi sebelum Tutup Buku bisa diproses: setiap kali periode ditutup, sistem memposting Jurnal Penutup tradisional yang menge-nol-kan seluruh akun Pendapatan & Beban dan memindahkan selisihnya (laba/rugi bersih) ke akun ini (lihat accounting/services/period.py::post_closing_entries). Laporan Laba Rugi per periode lama tetap akurat karena jurnal penutup dikecualikan dari perhitungannya.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset'), ('order_material_hpp', 'HPP Bahan Baku Order (T-204)'), ('period_close', 'Tutup Buku (Jurnal Penutup)')], default='manual', max_length=20),
        ),
    ]
