# Generated by Django 5.2.17 on 2026-09-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_period_close_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Umur manfaat (bulan) untuk penyusutan garis lurus. Kosongkan untuk aset yang tidak disusutkan (mis. tanah) -- accounting/services/depreciation.py melewati aset yang field ini kosong atau 0.', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset'), ('asset_depreciation', 'Penyusutan Aset'), ('order_material_hpp', 'HPP Bahan Baku Order (T-204)'), ('period_close', 'Tutup Buku (Jurnal Penutup)')], default='manual', max_length=20),
        ),
    ]
