# Generated by Django 5.2.17 on 2026-09-09 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_asset_disposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='shift_cash_variance_account',
            field=models.ForeignKey(blank=True, help_text="Akun Selisih Kas (pola 'Cash Over/Short') -- dikredit (pendapatan lain) kalau kas fisik LEBIH dari sistem saat tutup shift, didebit (beban lain) kalau kas fisik KURANG.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='shift_cash_variance_auto_post_enabled',
            field=models.BooleanField(default=False, help_text='Posting otomatis selisih kas kasir (kas fisik vs sistem) ke jurnal saat shift ditutup. Butuh shift_cash_variance_account terisi -- kalau tidak, posting dilewati walau sakelar ini aktif.'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset'), ('asset_depreciation', 'Penyusutan Aset'), ('asset_disposal', 'Pelepasan Aset'), ('order_material_hpp', 'HPP Bahan Baku Order (T-204)'), ('period_close', 'Tutup Buku (Jurnal Penutup)'), ('shift_cash_variance', 'Selisih Kas Shift')], default='manual', max_length=20),
        ),
    ]
