# Generated by Django 5.2.17 on 2026-09-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_accountingsettings_shift_cash_variance_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='order_customer_deposit_account',
            field=models.ForeignKey(blank=True, help_text="Akun Uang Muka Pelanggan (kewajiban) — dikredit saat pelanggan bayar DP SEBELUM Order berstatus 'Selesai' (belum boleh diakui sebagai pendapatan, barang/jasa belum diserahkan). Saat Order selesai, saldo ini dipindah (didebit) untuk mengurangi Piutang Usaha yang baru dicatat. Wajib diisi supaya pembayaran sebelum 'Selesai' bisa diposting.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='order_receivable_account',
            field=models.ForeignKey(blank=True, help_text="Akun Piutang Usaha — didebit penuh (bersama order_sales_revenue_account dikredit) saat Order berstatus 'Selesai', lalu dikredit setiap pembayaran/cicilan setelahnya sampai lunas. Wajib diisi supaya posting Order accrual berjalan.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='order_sales_revenue_account',
            field=models.ForeignKey(blank=True, help_text="Akun pendapatan default untuk Order — diakui PENUH saat Order berstatus 'Selesai' (accrual basis, keputusan finance 2026-09-09), bukan lagi saat DP/pelunasan diterima. Berbeda dari akun pendapatan POS — admin dapat mengarahkan ke akun COA yang sama jika ingin menyatukan omzet Order dan POS dalam satu akun.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset'), ('asset_depreciation', 'Penyusutan Aset'), ('asset_disposal', 'Pelepasan Aset'), ('order_material_hpp', 'HPP Bahan Baku Order (T-204)'), ('period_close', 'Tutup Buku (Jurnal Penutup)'), ('shift_cash_variance', 'Selisih Kas Shift'), ('order_completion', 'Pengakuan Pendapatan Order (Selesai)')], default='manual', max_length=20),
        ),
    ]
