# Generated by Django 5.2.17 on 2026-09-21 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_accountingsettings_order_customer_deposit_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='payroll_employer_contribution_expense_account',
            field=models.ForeignKey(blank=True, help_text='Akun Beban iuran perusahaan (mis. BPJS) -- hanya wajib bila ada iuran perusahaan.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='payroll_expense_account',
            field=models.ForeignKey(blank=True, help_text='Akun Biaya gaji yang didebit saat gaji diakui.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='payroll_payable_account',
            field=models.ForeignKey(blank=True, help_text='Akun Hutang gaji yang dikredit saat gaji diakui dan didebit saat dibayar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('payroll_payment', 'Pembayaran Gaji'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset'), ('asset_depreciation', 'Penyusutan Aset'), ('asset_disposal', 'Pelepasan Aset'), ('order_material_hpp', 'HPP Bahan Baku Order (T-204)'), ('period_close', 'Tutup Buku (Jurnal Penutup)'), ('shift_cash_variance', 'Selisih Kas Shift'), ('order_completion', 'Pengakuan Pendapatan Order (Selesai)')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollComponentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, unique=True)),
                ('jenis', models.CharField(choices=[('kewajiban', 'Kewajiban ke pihak ketiga (mis. BPJS, pajak)'), ('piutang', 'Piutang karyawan (mis. kasbon/cicilan)'), ('pengurang_beban', 'Pengurang biaya gaji (mis. denda telat)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('akun', models.ForeignKey(blank=True, help_text="Akun yang dikredit untuk potongan ini. Kosong hanya untuk 'pengurang beban'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('akun_iuran_perusahaan', models.ForeignKey(blank=True, help_text='Akun hutang yang dikredit untuk iuran perusahaan atas komponen ini (jika ada).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'ordering': ['judul'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('versi', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('dibalik', 'Dibalik (dikoreksi)')], default='aktif', max_length=10)),
                ('payload_hash', models.CharField(help_text='Sidik jari data HR saat diposting.', max_length=64)),
                ('payload', models.JSONField(help_text='Snapshot data HR yang diposting (audit).')),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=16)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('dibalik_pada', models.DateTimeField(blank=True, null=True)),
                ('dibayar_pada', models.DateTimeField(blank=True, null=True)),
                ('dibalik_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dibayar_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('payment_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tahun', '-bulan', '-versi'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'aktif')), fields=('tahun', 'bulan'), name='uniq_payroll_posting_aktif_per_periode'), models.UniqueConstraint(fields=('tahun', 'bulan', 'versi'), name='uniq_payroll_posting_versi')],
            },
        ),
    ]
