# Generated by Django 5.2.17 on 2026-09-25 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_payroll_posting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifikasiKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunci', models.CharField(max_length=120, unique=True)),
                ('jenis', models.CharField(choices=[('payroll_final', 'Gaji siap diposting'), ('reimbursement', 'Reimbursement disetujui')], max_length=30)),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField(blank=True, default='')),
                ('tautan', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('dibaca_oleh', models.ManyToManyField(blank=True, related_name='notifikasi_keuangan_dibaca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat', '-id'],
            },
        ),
    ]
