# Generated by Django 5.2.17 on 2026-09-26 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_notifikasi_keuangan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='payroll_batas_otorisasi_owner',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total gaji bersih di atas nominal ini wajib diotorisasi Owner (Manager tidak cukup). Kosong = Owner maupun Manager boleh berapa pun.', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='payroll_batas_selisih_persen',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Total gaji bersih berubah lebih dari persen ini dibanding periode sebelumnya = ditandai saat verifikasi.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='notifikasikeuangan',
            name='jenis',
            field=models.CharField(choices=[('payroll_final', 'Gaji siap diposting'), ('reimbursement', 'Reimbursement disetujui'), ('persetujuan_gaji', 'Persetujuan pencairan gaji')], max_length=30),
        ),
        migrations.CreateModel(
            name='PengajuanGaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('menunggu_verifikasi', 'Menunggu verifikasi SPV Finance'), ('menunggu_otorisasi', 'Menunggu otorisasi Owner/Manager'), ('siap_dibayar', 'Siap dibayar'), ('dibayar', 'Dibayar'), ('ditolak', 'Ditolak'), ('digantikan', 'Digantikan data HR yang lebih baru')], default='menunggu_verifikasi', max_length=24)),
                ('hash_hr', models.CharField(help_text='Sidik jari data slip HR yang diajukan.', max_length=64)),
                ('ringkasan', models.JSONField(blank=True, default=dict)),
                ('cek', models.JSONField(blank=True, default=list, help_text='Hasil pemeriksaan otomatis (peringatan).')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diverifikasi_pada', models.DateTimeField(blank=True, null=True)),
                ('diotorisasi_pada', models.DateTimeField(blank=True, null=True)),
                ('dibayar_pada', models.DateTimeField(blank=True, null=True)),
                ('bukti_transfer', models.FileField(blank=True, null=True, upload_to='payroll/bukti_transfer/')),
                ('ditolak_pada', models.DateTimeField(blank=True, null=True)),
                ('alasan_tolak', models.TextField(blank=True, default='')),
                ('sinkron_hr', models.CharField(blank=True, default='', help_text='Hasil memberi tahu HR (dibayar/ditolak).', max_length=200)),
                ('dibayar_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diotorisasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ditolak_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengajuan', to='accounting.payrollposting')),
            ],
            options={
                'ordering': ['-tahun', '-bulan', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanGajiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('diajukan', 'Diajukan HR'), ('diverifikasi', 'Diverifikasi SPV Finance'), ('diotorisasi', 'Diotorisasi'), ('dibayar', 'Dibayar'), ('ditolak', 'Ditolak'), ('digantikan', 'Digantikan')], max_length=20)),
                ('pada', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, default='')),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='accounting.pengajuangaji')),
            ],
            options={
                'ordering': ['pada', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pengajuangaji',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['menunggu_verifikasi', 'menunggu_otorisasi', 'siap_dibayar'])), fields=('tahun', 'bulan'), name='uniq_pengajuan_gaji_terbuka_per_periode'),
        ),
    ]
