# Generated by Django 5.2.17 on 2026-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_persetujuan_gaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening_balance', 'Saldo Awal'), ('pos_sale', 'Penjualan POS'), ('order_payment', 'Pembayaran Order'), ('purchase', 'Pembelian'), ('purchase_payment', 'Pembayaran Pembelian'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_opname', 'Opname Stok'), ('production', 'Produksi'), ('payroll', 'Penggajian'), ('payroll_payment', 'Pembayaran Gaji'), ('cash_transaction', 'Transaksi Kas'), ('cash_transfer', 'Transfer Kas'), ('capital_transfer', 'Transfer Modal'), ('settlement', 'Konfirmasi Settlement'), ('asset_acquisition', 'Perolehan Aset'), ('asset_depreciation', 'Penyusutan Aset'), ('asset_disposal', 'Pelepasan Aset'), ('order_material_hpp', 'HPP Bahan Baku Order (T-204)'), ('period_close', 'Tutup Buku (Jurnal Penutup)'), ('shift_cash_variance', 'Selisih Kas Shift'), ('order_completion', 'Pengakuan Pendapatan Order (Selesai)'), ('order_stock_hpp', 'HPP Penjualan Order')], default='manual', max_length=20),
        ),
    ]
