/**
 * Konfigurasi daftar laporan untuk tab "Laporan Produk".
 *
 * Setiap entri mendeskripsikan satu jenis laporan yang muncul di panel
 * "Daftar Laporan" (kiri). `columns` dipakai untuk merender header tabel di
 * panel detail (kanan). Data masih kosong pada tahap kerangka UI ini —
 * penyambungan ke endpoint dilakukan bertahap per laporan.
 *
 * Bentuk kolom: { key, label, align?: 'left'|'center'|'right', sortable?: bool }
 */

// Kolom yang sering dipakai ulang antar laporan produk.
const COL = {
  produk: { key: 'produk', label: 'Produk', sortable: true },
  namaAlt: { key: 'nama_alt', label: 'Nama Produk Alternatif', sortable: true },
  variant: { key: 'variant', label: 'Variant' },
  grup: { key: 'grup', label: 'Grup', sortable: true },
  sku: { key: 'sku', label: 'SKU', sortable: true },
  barcode: { key: 'barcode', label: 'Barcode', sortable: true },
  kategori: { key: 'kategori', label: 'Kategori', sortable: true },
  brand: { key: 'brand', label: 'Brand', sortable: true },
  koleksi: { key: 'koleksi', label: 'Koleksi', sortable: true },
  satuan: { key: 'satuan', label: 'Satuan (UOM)' },
  qtyJual: { key: 'qty_jual', label: 'Qty Terjual', align: 'right', sortable: true },
  qtyMasuk: { key: 'qty_masuk', label: 'Qty Masuk', align: 'right', sortable: true },
  qtyKeluar: { key: 'qty_keluar', label: 'Qty Keluar', align: 'right', sortable: true },
  sisaStok: { key: 'sisa_stok', label: 'Sisa Stok', align: 'right', sortable: true },
  totalJual: { key: 'total_jual', label: 'Total Penjualan', align: 'right', sortable: true },
  laba: { key: 'laba', label: 'Laba', align: 'right', sortable: true },
  hpp: { key: 'hpp', label: 'HPP', align: 'right', sortable: true },
  harga: { key: 'harga', label: 'Harga', align: 'right', sortable: true },
  tanggal: { key: 'tanggal', label: 'Tanggal', sortable: true },
};

export const PRODUK_REPORTS = [
  {
    id: 'sku',
    dataSource: 'sku',
    label: 'Penjualan berdasarkan SKU',
    columns: [COL.produk, COL.namaAlt, COL.variant, COL.grup, COL.sku, COL.barcode, COL.qtyJual, COL.totalJual, COL.laba],
  },
  {
    id: 'kategori',
    dataSource: 'kategori',
    label: 'Penjualan berdasarkan Kategori',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Grup', 'Sort By: Qty', 'Sort By: Total Penjualan'],
    },
    columns: [COL.kategori, COL.qtyJual, COL.totalJual],
  },
  {
    id: 'sku-makanan',
    unavailable: 'Sistem tidak memiliki data pengiriman makanan (integrasi food delivery).',
    label: 'Penjualan berdasarkan SKU Pengiriman Makanan',
    toolbar: { paket: false, cari: false },
    columns: [
      { key: 'grup', label: 'Group' },
      { key: 'produk', label: 'Produk' },
      { key: 'variant', label: 'Variant' },
      { key: 'brand', label: 'Brand' },
      { key: 'qty_jual', label: 'Qty Terjual', align: 'right' },
      { key: 'total_jual', label: 'Total Penjualan', align: 'right' },
      { key: 'total_makanan', label: 'Total Penjualan Pengiriman Makanan', align: 'right' },
    ],
  },
  {
    id: 'brand',
    dataSource: 'brand',
    label: 'Penjualan produk berdasarkan Brand',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama', 'Sort By: Qty'],
    },
    columns: [
      { key: 'brand', label: 'Brand', sortable: true },
      { key: 'qty_jual', label: 'Qty Terjual', align: 'right', sortable: true },
      { key: 'total_jual', label: 'Total Penjualan', align: 'right', sortable: true },
      { key: 'komisi', label: 'Komisi', align: 'right', sortable: true },
      { key: 'laba', label: 'Laba', align: 'right', sortable: true },
    ],
  },
  {
    id: 'koleksi',
    dataSource: 'koleksi',
    label: 'Penjualan berdasarkan Koleksi',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama', 'Sort By: Qty'],
    },
    columns: [COL.koleksi, COL.qtyJual, COL.totalJual],
  },
  {
    id: 'addon',
    unavailable: 'Penjualan add-on tidak pernah dicatat pada baris penjualan — yang ada hanya master Add-On.',
    label: 'Penjualan Add-On Per Item',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama', 'Sort By: Qty'],
    },
    columns: [
      { key: 'addon', label: 'Add-Ons' },
      { key: 'total_qty', label: 'Total Qty', align: 'right' },
      { key: 'total_jual', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'material',
    dataSource: 'material',
    label: 'Produk Material',
    toolbar: { paket: false, cari: false },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'sku', label: 'SKU' },
      { key: 'bahan', label: 'Bahan / Resep' },
      { key: 'qty', label: 'Qty', align: 'right' },
      { key: 'unit', label: 'Unit Pengukuran' },
      { key: 'nilai_konversi', label: 'Nilai Konversi - Unit Pengukuran' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'harga_beli_material', label: 'Harga Beli Material', align: 'right' },
    ],
  },
  {
    id: 'qty-terjual',
    dataSource: 'qty-terjual',
    label: 'Qty Produk Terjual',
    toolbar: { paket: false, cari: false },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_jual', label: 'Qty Terjual' },
        { key: 'total_harga_beli', label: 'Total Harga Beli', align: 'right' },
        { key: 'total_jual_online', label: 'Total Harga Jual Online', align: 'right' },
        { key: 'total_jual_toko', label: 'Total Harga Jual di Toko', align: 'right' },
      ],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'qty_jual', label: 'Qty Terjual', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
      { key: 'harga_jual_online', label: 'Harga Jual Online', align: 'right' },
      { key: 'harga_jual_toko', label: 'Harga Jual di Toko', align: 'right' },
    ],
  },
  {
    id: 'qty-stok-tanggal',
    dataSource: 'qty-stok-tanggal',
    label: 'Qty stok berdasarkan tanggal',
    dateMode: 'single',
    toolbar: { paket: false, cari: false },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_stok', label: 'Qty Stok' },
        { key: 'harga_beli', label: 'Harga Beli' },
        { key: 'ols_harga_jual', label: 'OLS - Harga Jual' },
        { key: 'pos_harga_jual', label: 'POS - Harga Jual' },
      ],
    },
    columns: [
      { key: 'nama_produk', label: 'Nama Produk' },
      { key: 'brand', label: 'Brand' },
      { key: 'grup', label: 'Grup' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'ols_harga_jual', label: 'OLS - Harga Jual', align: 'right' },
      { key: 'pos_harga_jual', label: 'POS - Harga Jual', align: 'right' },
      { key: 'total', label: 'Total', align: 'right' },
    ],
  },
  {
    id: 'qty-stok-syncron',
    dataSource: 'qty-stok-syncron',
    label: 'Qty stok per tanggal manual syncron',
    dateMode: 'single',
    toolbar: { paket: false, cari: 'left', sync: true },
    notice: {
      text: 'Pastikan sudah di syncron sampai kemarin dan report di ambil pagi sebelum ada pergerakan hari ini, untuk memastikan akurat',
      summaryButton: true,
    },
    columns: [
      { key: 'nama_produk', label: 'Nama Produk' },
      { key: 'brand', label: 'Brand' },
      { key: 'grup', label: 'Grup' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'ols_harga_jual', label: 'OLS - Harga Jual', align: 'right' },
      { key: 'pos_harga_jual', label: 'POS - Harga Jual', align: 'right' },
      { key: 'total', label: 'Total', align: 'right' },
    ],
  },
  {
    id: 'tidak-laku',
    dataSource: 'tidak-laku',
    label: 'Produk Tidak Laku',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Grup', 'Sort By: Nama'],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'varian', label: 'Varian' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right', sortable: true },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'harga_jual_online', label: 'Harga Jual Online', align: 'right' },
      { key: 'harga_jual_toko', label: 'Harga Jual di Toko', align: 'right' },
    ],
  },
  {
    id: 'sisa-uom',
    dataSource: 'sisa-uom',
    label: 'Sisa stok berdasarkan satuan (UOM)',
    dateMode: 'none',
    toolbar: { paket: false, cari: false },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty', label: 'Qty' },
        { key: 'total_harga_beli', label: 'Total Harga Beli', align: 'right' },
        { key: 'total_jual_online', label: 'Total Harga Jual Online', align: 'right' },
        { key: 'total_jual_toko', label: 'Total Harga Jual Toko', align: 'right' },
      ],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'uom', label: 'UOM' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
      { key: 'harga_jual_online', label: 'Harga Jual Online', align: 'right' },
      { key: 'harga_jual_toko', label: 'Harga Jual Toko', align: 'right' },
    ],
  },
  {
    id: 'sisa-grup',
    dataSource: 'sisa-grup',
    label: 'Sisa Stok Grup Produk',
    dateMode: 'none',
    toolbar: { paket: false, cari: false },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_stok', label: 'Qty Stok' },
        { key: 'total', label: 'Total', align: 'right' },
      ],
    },
    columns: [
      { key: 'kategori', label: 'Kategori' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'total_jual', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'produk-status',
    dataSource: 'produk-status',
    label: 'Produk Status',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: all', 'Sort By: Fast moving', 'Sort By: Slow moving', 'Sort By: Dead stok'],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'harga_jual_online', label: 'Harga Jual Online', align: 'right' },
      { key: 'harga_jual_toko', label: 'Harga Jual di Toko', align: 'right' },
      { key: 'status', label: 'Status', align: 'center' },
    ],
  },
  {
    id: 'sisa-produk',
    dataSource: 'sisa-produk',
    label: 'Sisa Stok Produk',
    dateMode: 'none',
    toolbar: {
      paket: false,
      cari: false,
      groupFilter: true,
      sortByOptions: [
        'Sort By: Nama',
        'Sort By: Kategori',
        'Sort By: Qty Asc',
        'Sort By: Qty Desc',
        'Sort By: Harga jual',
      ],
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_stok', label: 'Qty Stok' },
        { key: 'total_harga_beli', label: 'Total Harga Beli', align: 'right' },
        { key: 'total_jual_online', label: 'Total Harga Jual Online', align: 'right' },
        { key: 'total_jual_toko', label: 'Total Harga Jual di Toko', align: 'right' },
      ],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'variant', label: 'Variant' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
      { key: 'harga_jual_online', label: 'Harga Jual Online', align: 'right' },
      { key: 'harga_jual_toko', label: 'Harga Jual di Toko', align: 'right' },
    ],
  },
  {
    id: 'stok-masuk',
    dataSource: 'stok-masuk',
    label: 'Stok Masuk',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama Produk', 'Sort By: No. Transaksi', 'Sort By: Supplier'],
    },
    summary: {
      title: 'Ringkasan',
      type: 'list',
      items: [{ label: 'Total Produk' }, { label: 'Jumlah' }],
    },
    columns: [
      { key: 'no_transaksi', label: 'No. Transaksi' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'produk', label: 'Produk' },
      { key: 'variant', label: 'Variant' },
      { key: 'seri', label: 'Seri' },
      { key: 'supplier', label: 'Supplier' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'rata_harga_beli', label: 'Rata-rata Harga Beli', align: 'right' },
      { key: 'harga_jual', label: 'Harga Jual', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
      { key: 'qty', label: 'Qty', align: 'right' },
    ],
  },
  {
    id: 'stok-keluar',
    dataSource: 'stok-keluar',
    label: 'Stok Keluar',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama Produk', 'Sort By: No. Transaksi'],
      extraSelects: [
        {
          label: 'Alasan',
          options: [
            'Semua data',
            'Rusak',
            'Kadaluarsa',
            'Pengembalian dana (Refund)',
            'Jumlah stock kelebihan',
            'Alasan lainnya',
          ],
        },
      ],
    },
    summary: {
      title: 'Ringkasan',
      type: 'list',
      items: [{ label: 'Total Produk' }, { label: 'Jumlah' }],
    },
    columns: [
      { key: 'no_transaksi', label: 'No. Transaksi' },
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'produk', label: 'Produk' },
      { key: 'seri', label: 'Seri' },
      { key: 'catatan', label: 'Catatan' },
      { key: 'alasan', label: 'Alasan' },
      { key: 'qty', label: 'Qty', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
    ],
  },
  {
    id: 'qty-keluar',
    dataSource: 'qty-keluar',
    label: 'Qty Produk Keluar',
    toolbar: { paket: false, cari: false },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_jual', label: 'Qty Terjual' },
        { key: 'total_jual', label: 'Total Penjualan', align: 'right' },
      ],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'variant', label: 'Variant' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'qty', label: 'Qty', align: 'right' },
      { key: 'harga', label: 'Harga', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
    ],
  },
  {
    id: 'usia-stok',
    dataSource: 'usia-stok',
    label: 'Usia Stok Produk',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['all report', 'with stock alert'],
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_stok', label: 'Qty Stok' },
        { key: 'total_sales_qty', label: 'Total Sales Qty', align: 'right' },
      ],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'variant', label: 'Variant' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'total_sales_qty', label: 'Total Sales Qty', align: 'right' },
      { key: 'avg_sales_qty', label: 'Avg Sales Qty', align: 'right' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'stock_age', label: 'Stock Age' },
    ],
  },
  {
    id: 'peringatan-stok',
    dataSource: 'peringatan-stok',
    label: 'Peringatan Sisa Stok',
    dateMode: 'none',
    toolbar: {
      paket: false,
      cari: false,
      sortByOptions: [
        'Sort By: Nama',
        'Sort By: Kategori',
        'Sort By: Qty Asc',
        'Sort By: Qty Desc',
        'Sort By: Harga jual',
        'Sort By: Harga beli',
      ],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'supplier', label: 'Supplier' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
    ],
  },
  {
    id: 'tingkatan-harga',
    dataSource: 'tingkatan-harga',
    label: 'Tingkatan Harga',
    dateMode: 'none',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama Produk', 'Sort By: Tipe Pelanggan'],
    },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'sku', label: 'SKU' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'tipe_pelanggan', label: 'Tipe Pelanggan' },
      { key: 'qty_mulai', label: 'Qty Mulai', align: 'right' },
      { key: 'harga_jual', label: 'Harga Jual', align: 'right' },
    ],
  },
  {
    id: 'penjualan-paket',
    unavailable: 'Baris penjualan tidak menyimpan referensi paket, sehingga penjualan paket tidak dapat dihitung.',
    label: 'Penjualan Paket',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama', 'Sort By: Qty'],
    },
    columns: [
      { key: 'nama', label: 'Nama' },
      { key: 'qty_jual', label: 'Qty Terjual', align: 'right' },
      { key: 'total_jual', label: 'Total Penjualan', align: 'right' },
    ],
  },
  {
    id: 'rincian-paket',
    unavailable: 'Baris penjualan tidak menyimpan referensi paket, sehingga rincian penjualan paket tidak tersedia.',
    label: 'Rincian Penjualan Paket',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: No. Pesanan', 'Sort By: Nama'],
    },
    columns: [
      { key: 'no_pesanan', label: 'No. Pesanan' },
      { key: 'tanggal_jual', label: 'Tanggal Jual' },
      { key: 'pelayan_pos', label: 'Pelayan (POS)' },
      { key: 'nama_paket', label: 'Nama Paket Produk' },
      { key: 'qty', label: 'Qty', align: 'right' },
      { key: 'jumlah', label: 'Jumlah', align: 'right' },
    ],
  },
  {
    id: 'sisa-paket',
    unavailable: 'Stok paket tidak dilacak tersendiri; yang punya stok hanya produk komponennya.',
    label: 'Sisa Stok Paket',
    dateMode: 'none',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: ['Sort By: Nama', 'Sort By: Qty Stok'],
    },
    columns: [
      { key: 'nama', label: 'Nama' },
      { key: 'qty', label: 'Qty', align: 'right' },
    ],
  },
  {
    id: 'pergerakan-stok',
    dataSource: 'pergerakan-stok',
    label: 'Pergerakan Stok',
    toolbar: { paket: false, cariPlaceholder: 'No. Ref' },
    columns: [
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'ref_no', label: 'Ref No.' },
      { key: 'produk', label: 'Produk' },
      { key: 'sku', label: 'SKU' },
      { key: 'awal', label: 'Awal', align: 'right' },
      { key: 'masuk', label: 'Masuk', align: 'right' },
      { key: 'keluar', label: 'Keluar', align: 'right' },
      { key: 'sisa', label: 'Sisa', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
    ],
  },
  {
    id: 'value-pergerakan',
    dataSource: 'value-pergerakan',
    label: 'Value Pergerakan berdasarkan tanggal',
    toolbar: { paket: false, cari: false, pdf: false },
    columns: [
      { key: 'tanggal', label: 'Tanggal' },
      { key: 'masuk', label: 'Masuk', align: 'right' },
      { key: 'keluar', label: 'Keluar', align: 'right' },
    ],
  },
  {
    id: 'produk-dihapus',
    unavailable: 'Produk dihapus permanen dari database (tidak ada soft-delete), sehingga tidak bisa dilaporkan.',
    label: 'Produk dihapus',
    toolbar: { paket: false },
    columns: [
      { key: 'produk', label: 'Produk', sortable: true },
      { key: 'items', label: 'Items', sortable: true },
      { key: 'sku', label: 'SKU', sortable: true },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right', sortable: true },
      { key: 'harga_jual_online', label: 'Harga Jual Online', align: 'right', sortable: true },
      { key: 'harga_jual_toko', label: 'Harga Jual di Toko', align: 'right', sortable: true },
      { key: 'diubah_oleh', label: 'Diubah oleh', sortable: true },
      { key: 'waktu_diubah', label: 'Waktu diubah', sortable: true },
      { key: 'diubah_dari', label: 'Diubah dari', sortable: true },
    ],
  },
  {
    id: 'stok-kedaluwarsa',
    dataSource: 'stok-kedaluwarsa',
    label: 'Stok Kedaluwarsa',
    toolbar: {
      paket: false,
      cari: 'left',
      cariPlaceholder: 'Cari produk',
      pdf: false,
      excel: false,
      exportButton: true,
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_stok', label: 'QTY Stok' },
        { key: 'total_harga_beli', label: 'Total Harga Beli', align: 'right' },
      ],
    },
    columns: [
      { key: 'tanggal_kedaluwarsa', label: 'Tanggal Kedaluwarsa', sortable: true },
      { key: 'produk', label: 'Produk', sortable: true },
      { key: 'sku', label: 'SKU', sortable: true },
      { key: 'masuk', label: 'Masuk', align: 'right', sortable: true },
      { key: 'keluar', label: 'Keluar', align: 'right', sortable: true },
      { key: 'sisa', label: 'Sisa', align: 'right', sortable: true },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right', sortable: true },
      { key: 'rak', label: 'Rak', sortable: true },
    ],
  },
  {
    id: 'stok-fifo',
    dataSource: 'stok-fifo',
    label: 'Stok FIFO',
    toolbar: {
      paket: false,
      cari: 'left',
      cariPlaceholder: 'Cari produk',
      pdf: false,
      excel: false,
      exportButton: true,
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_stok', label: 'QTY Stok' },
        { key: 'total_harga_beli', label: 'Total Harga Beli', align: 'right' },
      ],
    },
    columns: [
      { key: 'tanggal_masuk', label: 'Tanggal Masuk', sortable: true },
      { key: 'produk', label: 'Produk', sortable: true },
      { key: 'sku', label: 'SKU', sortable: true },
      { key: 'masuk', label: 'Masuk', align: 'right', sortable: true },
      { key: 'keluar', label: 'Keluar', align: 'right', sortable: true },
      { key: 'sisa', label: 'Sisa', align: 'right', sortable: true },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right', sortable: true },
      { key: 'rak', label: 'Rak', sortable: true },
    ],
  },
  {
    id: 'pergerakan-fifo',
    dataSource: 'pergerakan-fifo',
    label: 'Pergerakan Stok Kedaluwarsa & FIFO',
    toolbar: {
      paket: 'select',
      selectOptions: ['Produk', 'No. Transaksi'],
      cariPlaceholder: 'Cari No. Transaksi',
      pdf: false,
      excel: false,
      exportButton: true,
      layout: ['paket', 'cari', 'date', 'export'],
    },
    columns: [
      { key: 'tanggal', label: 'Tanggal', sortable: true },
      { key: 'produk', label: 'Produk' },
      { key: 'no_transaksi', label: 'No. Transaksi' },
      { key: 'awal', label: 'Awal', align: 'right' },
      { key: 'masuk', label: 'Masuk', align: 'right' },
      { key: 'keluar', label: 'Keluar', align: 'right' },
      { key: 'sisa', label: 'Sisa', align: 'right' },
    ],
  },
  {
    id: 'banding-fifo',
    dataSource: 'banding-fifo',
    label: 'Perbandingan Stok & Stok FIFO',
    dateMode: 'none',
    toolbar: { paket: false, cari: 'left', cariPlaceholder: 'Cari produk' },
    columns: [
      { key: 'produk', label: 'Produk' },
      { key: 'stok', label: 'Stok', align: 'right' },
      { key: 'stok_fifo', label: 'Stok FIFO', align: 'right' },
      { key: 'selisih', label: 'Selisih', align: 'right' },
    ],
  },
  {
    id: 'serial-stok',
    unavailable: 'Nomor seri tersimpan sebagai daftar bebas pada produk dan tidak tertaut ke stok maupun penjualan.',
    label: 'Product dan Serial stok',
    dateMode: 'none',
    toolbar: {
      paket: 'select',
      cari: false,
      selectOptions: [
        'Sort By: Nama',
        'Sort By: Kategori',
        'Sort By: Qty Asc',
        'Sort By: Qty Desc',
        'Sort By: Harga jual',
        'Sort By: Harga beli',
      ],
    },
    summary: {
      title: 'Ringkasan',
      columns: [
        { key: 'qty_stok', label: 'Qty Stok' },
        { key: 'total_harga_beli', label: 'Total Harga Beli', align: 'right' },
        { key: 'total_jual_online', label: 'Total Harga Jual Online', align: 'right' },
        { key: 'total_jual_toko', label: 'Total Harga Jual di Toko', align: 'right' },
      ],
    },
    columns: [
      { key: 'toko', label: 'Toko' },
      { key: 'produk', label: 'Produk' },
      { key: 'varian', label: 'Varian' },
      { key: 'kategori', label: 'Kategori' },
      { key: 'qty_stok', label: 'Qty Stok', align: 'right' },
      { key: 'harga_beli', label: 'Harga Beli', align: 'right' },
      { key: 'subtotal', label: 'Subtotal', align: 'right' },
      { key: 'harga_jual_online', label: 'Harga Jual Online', align: 'right' },
      { key: 'harga_jual_toko', label: 'Harga Jual di Toko', align: 'right' },
    ],
  },
  {
    id: 'kiosk-produk',
    unavailable: 'Fitur Kiosk belum ada di sistem.',
    label: 'Rincian Produk Kiosk',
    toolbar: {
      paket: false,
      cari: false,
      extraSelects: [
        { label: 'Semua', disabled: false },
        { label: 'Status', options: ['Semua', 'Diambil', 'Belum diambil'] },
      ],
      layout: ['extraSelects', 'date', 'pdf', 'excel'],
    },
    columns: [
      { key: 'kategori', label: 'Kategori', sortable: true },
      { key: 'produk', label: 'Produk', sortable: true },
      { key: 'jumlah_dipesan', label: 'Jumlah dipesan', align: 'right', sortable: true },
      { key: 'jumlah_diambil', label: 'Jumlah diambil', align: 'right', sortable: true },
      { key: 'jumlah_belum', label: 'Jumlah belum diambil', align: 'right', sortable: true },
    ],
  },
  {
    id: 'perubahan-harga',
    unavailable: 'Riwayat harga hanya tersimpan sebagai teks bebas di log aktivitas, tanpa kolom harga lama/baru terstruktur.',
    label: 'Perubahan Harga',
    toolbar: { paket: false, cari: false },
    groups: [
      { key: 'produk', label: 'Produk' },
      { key: 'sku', label: 'SKU' },
      {
        label: 'Harga beli',
        children: [
          { key: 'hb_lama', label: 'Harga lama' },
          { key: 'hb_baru', label: 'Harga Baru' },
        ],
      },
      {
        label: 'Harga toko',
        children: [
          { key: 'ht_lama', label: 'Harga lama' },
          { key: 'ht_baru', label: 'Harga Baru' },
        ],
      },
      {
        label: 'Harga Online',
        children: [
          { key: 'ho_lama', label: 'Harga lama' },
          { key: 'ho_baru', label: 'Harga Baru' },
        ],
      },
      {
        label: 'Harga Pasar',
        children: [
          { key: 'hp_lama', label: 'Harga lama' },
          { key: 'hp_baru', label: 'Harga Baru' },
        ],
      },
    ],
  },
  {
    id: 'kiosk-pelanggan',
    unavailable: 'Fitur Kiosk belum ada di sistem.',
    label: 'Rincian Pelanggan Kiosk',
    toolbar: {
      paket: false,
      cari: false,
      extraSelects: [{ label: 'Status', options: ['Semua', 'Diambil', 'Belum diambil'] }],
      layout: ['extraSelects', 'date', 'pdf', 'excel'],
    },
    columns: [
      { key: 'nama_pelanggan', label: 'Nama Pelanggan', sortable: true },
      { key: 'total_dipesan', label: 'Total Product dipesan', align: 'right', sortable: true },
      { key: 'product_diambil', label: 'Jumlah product diambil', align: 'right', sortable: true },
      { key: 'product_belum', label: 'Jumlah product belum diambil', align: 'right', sortable: true },
    ],
  },
];

export default PRODUK_REPORTS;
