# Generated by Django 5.0.14 on 2026-05-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_contact_keterangan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kontrak', models.CharField(max_length=50, unique=True)),
                ('tipe', models.CharField(choices=[('tetap', 'Karyawan Tetap'), ('kontrak', 'Kontrak'), ('magang', 'Magang'), ('freelance', 'Freelance'), ('harian', 'Harian Lepas')], max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_berakhir', models.DateField(blank=True, help_text='Kosong = tidak ada batas waktu (karyawan tetap).', null=True)),
                ('gaji_pokok', models.IntegerField(default=0, help_text='Dalam Rupiah.')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('berakhir', 'Berakhir'), ('diputus', 'Diputus')], default='aktif', max_length=15)),
                ('dokumen', models.FileField(blank=True, help_text='Upload PDF kontrak.', null=True, upload_to='kontrak/%Y/')),
                ('catatan', models.TextField(blank=True, default='')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontrak_dibuat', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontrak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontrak',
                'verbose_name_plural': 'Kontrak',
                'db_table': 'kontrak',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='StaffAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('target', models.CharField(choices=[('semua', 'Semua Staff'), ('divisi', 'Per Divisi'), ('personal', 'Personal')], default='semua', max_length=10)),
                ('aktif_sampai', models.DateField(blank=True, help_text='Kosong = tidak ada batas tampil.', null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumuman_dibuat', to=settings.AUTH_USER_MODEL)),
                ('divisi', models.ForeignKey(blank=True, help_text="Wajib diisi jika target = 'divisi'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.divisi')),
                ('staff_personal', models.ForeignKey(blank=True, help_text="Wajib diisi jika target = 'personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengumuman_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'db_table': 'staff_announcement',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('jam_masuk', models.DateTimeField(blank=True, help_text='Clock-in — diisi saat staff klik tombol masuk.', null=True)),
                ('jam_keluar', models.DateTimeField(blank=True, help_text='Clock-out — diisi saat staff klik tombol keluar.', null=True)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha'), ('wfh', 'Work From Home')], default='hadir', max_length=10)),
                ('catatan', models.TextField(blank=True, default='')),
                ('diverifikasi', models.BooleanField(default=False, help_text='Manager menandai kehadiran sudah diverifikasi.')),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi_absensi', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['staff', 'manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'db_table': 'absensi',
                'ordering': ['-tanggal'],
                'unique_together': {('staff', 'tanggal')},
            },
        ),
    ]
