# Generated by Django 5.0.14 on 2026-05-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True, unique=True)),
                ('waktu_mulai', models.DateTimeField(help_text='Kapan absensi mulai dibuka.')),
                ('batas_maksimal', models.DateTimeField(help_text='Batas akhir waktu absen sebelum akun terkunci.')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah sesi hari ini sedang berlangsung.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dihidupkan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesi_absensi_dihidupkan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesi Absensi Harian',
                'verbose_name_plural': 'Sesi Absensi Harian',
                'db_table': 'daily_attendance_session',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='UnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.TextField(help_text='Alasan terlambat atau tidak absen.')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('waktu_request', models.DateTimeField(auto_now_add=True)),
                ('waktu_respon', models.DateTimeField(blank=True, null=True)),
                ('direspon_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_requests_direspon', to=settings.AUTH_USER_MODEL)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='hr.dailyattendancesession')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permintaan Buka Akses',
                'verbose_name_plural': 'Permintaan Buka Akses',
                'db_table': 'unlock_request',
                'ordering': ['-waktu_request'],
            },
        ),
    ]
