# Generated by Django 5.0.14 on 2026-05-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_dailyattendancesession_unlockrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(help_text='Misal: 1-100, 4-200', max_length=20, unique=True)),
                ('nama_akun', models.CharField(help_text='Misal: Kas Besar, Pendapatan Jasa', max_length=100)),
                ('kategori', models.CharField(help_text='Misal: Aset, Kewajiban, Ekuitas, Pendapatan, Beban', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiBukuBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('no_referensi', models.CharField(blank=True, help_text='Bisa diisi ID Order atau Nomor Kwitansi', max_length=50, null=True)),
                ('keterangan', models.TextField()),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('kredit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('waktu_input', models.DateTimeField(auto_now_add=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='hr.akun')),
            ],
            options={
                'ordering': ['tanggal', 'waktu_input'],
            },
        ),
    ]
