# Generated by Django 5.0.14 on 2026-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_akun_transaksibukubesar'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='workspace_unlocked',
            field=models.BooleanField(
                default=False,
                help_text="Bypass checkout/lock status, owner mengizinkan staff mengakses papan kerja meskipun sudah checkout."
            ),
        ),
    ]
