# Generated by Django 5.0.14 on 2026-05-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_absensi_workspace_unlocked'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaksibukubesar',
            index=models.Index(fields=['tanggal', 'waktu_input'], name='idx_tx_tanggal_waktu'),
        ),
        migrations.AddIndex(
            model_name='transaksibukubesar',
            index=models.Index(fields=['akun', 'tanggal'], name='idx_tx_akun_tanggal'),
        ),
        migrations.AddIndex(
            model_name='transaksibukubesar',
            index=models.Index(fields=['no_referensi'], name='idx_tx_no_referensi'),
        ),
    ]
