# Generated by Django 5.0.14 on 2026-06-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_transaksibukubesar_idx_tx_tanggal_waktu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlipGaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField(help_text='Bulan (1-12)')),
                ('tahun', models.IntegerField(help_text='Tahun (misal: 2026)')),
                ('gaji_pokok', models.IntegerField(default=0, help_text='Diambil dari Kontrak saat itu')),
                ('total_insentif', models.IntegerField(default=0, help_text='Total insentif dari JobBoard')),
                ('total_biaya_desain', models.IntegerField(default=0, help_text='Total biaya desain dari JobBoard')),
                ('potongan_terlambat', models.IntegerField(default=0, help_text='Potongan karena keterlambatan absen')),
                ('total_gaji_bersih', models.IntegerField(default=0, help_text='Total gaji bersih yang dibayarkan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Sudah Dibayar')], default='draft', max_length=15)),
                ('catatan', models.TextField(blank=True, default='')),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('waktu_dibayar', models.DateTimeField(blank=True, null=True)),
                ('dibayar_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slip_gaji_dibayar', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_gaji', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slip_gaji',
                'ordering': ['-tahun', '-bulan', 'staff'],
                'unique_together': {('staff', 'bulan', 'tahun')},
            },
        ),
    ]
