# Generated by Django 5.0.14 on 2026-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_slipgaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='status',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha'), ('wfh', 'Work From Home')], default='hadir', max_length=10),
        ),
    ]
