# Generated by Django 5.0.14 on 2026-05-16 15:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('nomor_wa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('total_order', models.IntegerField(default=0)),
                ('total_spent', models.IntegerField(default=0)),
                ('last_order', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('pertanyaan', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('jawaban', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.FloatField(default=0.0)),
                ('satuan', models.CharField(max_length=20)),
                ('kategori', models.CharField(max_length=50)),
                ('min_stok', models.FloatField(default=0.0)),
                ('cost_per_unit', models.FloatField(default=0.0)),
                ('supplier', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('nomor_wa', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('status_global', models.CharField(choices=[('review', 'Menunggu Review Manager'), ('proses', 'Dalam Proses Produksi'), ('selesai', 'Selesai Seluruhnya'), ('batal', 'Dibatalkan / Cancel')], default='review', max_length=30)),
                ('catatan_pelanggan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('owner', 'Owner / Boss'), ('manager', 'Manager'), ('staff', 'Staff Produksi')], default='staff', max_length=20)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('kota', models.CharField(blank=True, max_length=50, null=True)),
                ('negara', models.CharField(default='Indonesia', max_length=50)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('divisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.divisi')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_produk', models.CharField(max_length=100)),
                ('detail', models.JSONField(blank=True, default=list, help_text='Spesifikasi awal dari customer dalam format Tabel/JSON', null=True)),
                ('qty', models.IntegerField(default=1)),
                ('harga_jual', models.IntegerField(default=0)),
                ('biaya_bahan', models.IntegerField(default=0)),
                ('estimasi', models.CharField(default='-', max_length=50)),
                ('gdrive_customer_link', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='TahapProses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('urutan', models.IntegerField(default=1, help_text='Urutan jalannya proses (angka kecil didahului, misal 1: Desain, 2: Cetak)')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahapan', to='api.divisi')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pekerjaan', models.CharField(choices=[('antrean', 'Dalam Antrean'), ('dikerjakan', 'Sedang Dikerjakan'), ('selesai', 'Selesai Sukses'), ('gagal', 'Gagal Produksi / Rusak'), ('batal', 'Dibatalkan di Tengah Jalan'), ('kendala', 'Ada Kendala / Pending')], default='antrean', max_length=20)),
                ('catatan_staff', models.JSONField(blank=True, default=list, help_text='Keterangan staff berformat Tabel/Excel (JSON)', null=True)),
                ('gdrive_output_link', models.URLField(blank=True, help_text='Link file hasil kerja staff di Google Drive', max_length=500, null=True)),
                ('insentif', models.IntegerField(default=0, help_text='Insentif yang ditentukan oleh Manager untuk tugas ini')),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('pic_staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tasks', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.orderitem')),
                ('tahap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.tahapproses')),
            ],
        ),
    ]
