# Generated by Django 5.0.14 on 2026-05-17 08:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.CharField(default=api.models._generate_inv_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
