# Generated by Django 5.0.14 on 2026-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inventoryitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_profil',
            field=models.URLField(blank=True, help_text='Link Google Drive foto profil', max_length=500, null=True),
        ),
    ]
