# Generated by Django 5.0.14 on 2026-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, help_text='Foto Profil Lokal', null=True, upload_to='avatars/'),
        ),
    ]
