# Generated by Django 5.0.14 on 2026-05-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_foto_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='keterangan',
            field=models.TextField(blank=True, help_text='Catatan/keterangan tentang pelanggan ini', null=True),
        ),
    ]
