# Generated by Django 5.0.14 on 2026-05-23 08:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fix_contact_last_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bpjs_kes',
            field=models.CharField(blank=True, help_text='Nomor BPJS Kesehatan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='file_pkwt',
            field=models.FileField(blank=True, help_text='File Kontrak PKWT', null=True, upload_to='dokumen_hr/pkwt/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jenis_kontrak',
            field=models.CharField(default='tetap', help_text='tetap, kontrak, magang, freelance', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kontrak_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kontrak_selesai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_kpj',
            field=models.CharField(blank=True, help_text='Nomor Kartu Peserta Jamsostek / BPJS Ketenagakerjaan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_karyawan',
            field=models.CharField(default='aktif', help_text='aktif, cuti, nonaktif', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=api.models._generate_order_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
