# Generated by Django 5.0.14 on 2026-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_bpjs_kes_customuser_file_pkwt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diskon_persen',
            field=models.FloatField(default=0.0, help_text='Diskon nota dalam persen, 0-100'),
        ),
        migrations.AddField(
            model_name='order',
            name='dp_dibayar',
            field=models.IntegerField(default=0, help_text='Uang muka yang sudah dibayar'),
        ),
        migrations.AddField(
            model_name='order',
            name='sisa_tagihan',
            field=models.IntegerField(default=0, help_text='total_harga dikurangi dp_dibayar'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_harga',
            field=models.IntegerField(default=0, help_text='Total harga keseluruhan setelah diskon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bahan',
            field=models.CharField(blank=True, help_text='Misal: Flexi Korea, Vinyl, dll', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='harga_per_m2',
            field=models.IntegerField(default=0, help_text='Harga satuan bahan per m2'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='lebar',
            field=models.FloatField(default=0.0, help_text='Lebar cetakan dalam meter'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='luas',
            field=models.FloatField(default=0.0, help_text='Otomatis dihitung: panjang x lebar'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='panjang',
            field=models.FloatField(default=0.0, help_text='Panjang cetakan dalam meter'),
        ),
    ]
