# Generated by Django 5.0.14 on 2026-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_jobboard_alasan_gagal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboard',
            name='alasan_gagal',
            field=models.TextField(blank=True, help_text='Alasan kenapa pengerjaan job ini gagal atau dibatalkan', null=True),
        ),
    ]
