# Generated by Django 5.0.14 on 2026-05-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_jobboard_alasan_gagal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Boss'), ('manager', 'Manager'), ('admin', 'Admin'), ('staff', 'Staff Produksi')], default='staff', max_length=20),
        ),
    ]
