# Generated by Django 5.0.14 on 2026-05-29 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nama',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Boss'), ('manager', 'Manager'), ('admin', 'Admin'), ('staff', 'Staff Produksi')], db_index=True, default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='kategori',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='nama',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(db_index=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobboard',
            name='status_pekerjaan',
            field=models.CharField(choices=[('antrean', 'Dalam Antrean'), ('dikerjakan', 'Sedang Dikerjakan'), ('selesai', 'Selesai Sukses'), ('gagal', 'Gagal Produksi / Rusak'), ('batal', 'Dibatalkan di Tengah Jalan'), ('kendala', 'Ada Kendala / Pending')], db_index=True, default='antrean', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobboard',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='nama',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='nomor_wa',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_global',
            field=models.CharField(choices=[('review', 'Menunggu Review Manager'), ('desain', 'Proses Desain'), ('proses', 'Dalam Proses Produksi'), ('ready', 'Siap Diambil / Selesai Produksi'), ('selesai', 'Selesai Seluruhnya'), ('batal', 'Dibatalkan / Cancel')], db_index=True, default='review', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='waktu',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='jenis_produk',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='kategori',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='nama_produk',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_type',
            field=models.CharField(db_index=True, default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='restockhistory',
            name='waktu',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-last_order'], name='idx_contact_last_order'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-total_spent'], name='idx_contact_total_spent'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['kategori', 'nama'], name='idx_inv_kategori_nama'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['stok', 'min_stok'], name='idx_inv_stok_min'),
        ),
        migrations.AddIndex(
            model_name='jobboard',
            index=models.Index(fields=['pic_staff', 'status_pekerjaan'], name='idx_job_staff_status'),
        ),
        migrations.AddIndex(
            model_name='jobboard',
            index=models.Index(fields=['pic_staff', 'waktu_selesai'], name='idx_job_staff_selesai'),
        ),
        migrations.AddIndex(
            model_name='jobboard',
            index=models.Index(fields=['tahap', 'status_pekerjaan'], name='idx_job_tahap_status'),
        ),
        migrations.AddIndex(
            model_name='jobboard',
            index=models.Index(fields=['order_item'], name='idx_job_orderitem'),
        ),
        migrations.AddIndex(
            model_name='jobboard',
            index=models.Index(fields=['otp_requested', 'otp_sent'], name='idx_job_otp_flags'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_orderitem_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['jenis_produk'], name='idx_orderitem_jenis'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['kategori', 'nama_produk'], name='idx_price_kat_produk'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['kategori', 'material'], name='idx_price_kat_material'),
        ),
        migrations.AddIndex(
            model_name='restockhistory',
            index=models.Index(fields=['item', '-waktu'], name='idx_restock_item_waktu'),
        ),
        migrations.AddIndex(
            model_name='restockhistory',
            index=models.Index(fields=['user', '-waktu'], name='idx_restock_user_waktu'),
        ),
        migrations.AddIndex(
            model_name='tahapproses',
            index=models.Index(fields=['divisi', 'urutan'], name='idx_tahap_divisi_urutan'),
        ),
    ]
