# Generated by Django 5.0.14 on 2026-05-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_contact_nama_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nip',
            field=models.CharField(blank=True, help_text='Nomor Induk Pegawai / Staff ID (contoh: STF-2026-001)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobboard',
            name='biaya_desain',
            field=models.IntegerField(default=0, help_text='Biaya tambahan desain untuk tugas ini'),
        ),
    ]
