# Generated by Django 5.0.14 on 2026-06-02 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customuser_nip_jobboard_biaya_desain'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tindakan', models.CharField(help_text='Jenis tindakan, misal: CREATE_ORDER, UPDATE_ORDER, dll.', max_length=100)),
                ('keterangan', models.TextField(help_text='Deskripsi lengkap mengenai riwayat perubahan.')),
                ('waktu', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='api.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
                'indexes': [models.Index(fields=['order', '-waktu'], name='idx_order_log_waktu')],
            },
        ),
    ]
