# Generated by Django 5.0.14 on 2026-06-02 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_orderactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomplainOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_komplain', models.CharField(choices=[('salah_ukuran', 'Salah Ukuran'), ('warna_pudar', 'Warna Pudar / Buram'), ('salah_desain', 'Salah Desain / File'), ('sobek_rusak', 'Sobek / Rusak Saat Produksi'), ('pemasangan', 'Masalah Pemasangan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=30)),
                ('deskripsi', models.TextField(help_text='Penjelasan detail komplain dari pelanggan')),
                ('status', models.CharField(choices=[('masuk', 'Komplain Masuk'), ('diproses', 'Sedang Diproses'), ('cetak_ulang', 'Dijadwalkan Cetak Ulang'), ('selesai', 'Selesai / Resolved'), ('ditolak', 'Ditolak / Tidak Valid')], db_index=True, default='masuk', max_length=20)),
                ('resolusi', models.CharField(blank=True, choices=[('cetak_ulang_gratis', 'Cetak Ulang Gratis (Garansi)'), ('cetak_ulang_bayar', 'Cetak Ulang Biaya Customer'), ('diskon_kompensasi', 'Diskon / Kompensasi'), ('ditolak', 'Ditolak')], max_length=30, null=True)),
                ('catatan_resolusi', models.TextField(blank=True, help_text='Catatan penyelesaian dari manager', null=True)),
                ('perlu_cetak_ulang', models.BooleanField(default=False)),
                ('foto_bukti', models.URLField(blank=True, help_text='Link foto/bukti komplain (Google Drive/URL)', max_length=500, null=True)),
                ('waktu_masuk', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('dicatat_oleh', models.ForeignKey(blank=True, help_text='Staff/Kasir yang menerima komplain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komplain_dicatat', to=settings.AUTH_USER_MODEL)),
                ('ditangani_oleh', models.ForeignKey(blank=True, help_text='Manager yang menangani resolusi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komplain_ditangani', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order yang dikomplain oleh pelanggan', on_delete=django.db.models.deletion.CASCADE, related_name='komplain', to='api.order')),
            ],
            options={
                'ordering': ['-waktu_masuk'],
            },
        ),
        migrations.CreateModel(
            name='KomplainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_baru', models.CharField(max_length=20)),
                ('catatan', models.TextField(blank=True, default='')),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('komplain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.komplainorder')),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
        migrations.AddIndex(
            model_name='komplainorder',
            index=models.Index(fields=['status', '-waktu_masuk'], name='idx_komplain_status_waktu'),
        ),
        migrations.AddIndex(
            model_name='komplainorder',
            index=models.Index(fields=['order'], name='idx_komplain_order'),
        ),
    ]
