# Generated by Django 5.0.14 on 2026-06-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_komplain_garansi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_global',
            field=models.CharField(choices=[('draft', 'Draft Penawaran'), ('quotation', 'Kirim Penawaran'), ('review', 'Menunggu Review Manager'), ('desain', 'Proses Desain'), ('proses', 'Dalam Proses Produksi'), ('ready', 'Siap Diambil / Selesai Produksi'), ('selesai', 'Selesai Seluruhnya'), ('batal', 'Dibatalkan / Cancel')], db_index=True, default='review', max_length=30),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(help_text='Produk yang dirujuk', on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='api.productprice')),
            ],
        ),
        migrations.CreateModel(
            name='BoMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_required_per_unit', models.FloatField(default=1.0, help_text='Jumlah bahan baku per unit / m2 produk jadi')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.billofmaterials')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('call', 'Telepon'), ('whatsapp', 'Kirim WhatsApp'), ('design_check', 'Konfirmasi Desain'), ('payment_followup', 'Follow-up Pembayaran'), ('other', 'Lainnya')], default='other', max_length=25)),
                ('keterangan', models.TextField(help_text='Detail aktivitas/follow-up')),
                ('waktu_jatuh_tempo', models.DateField(db_index=True)),
                ('selesai', models.BooleanField(db_index=True, default=False)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.order')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['waktu_jatuh_tempo'],
            },
        ),
    ]
