# Generated by Django 5.0.14 on 2026-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_order_status_global_billofmaterials_bomitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='desain_susulan',
            field=models.BooleanField(default=False, help_text='Apakah file desain ini dikirim susulan oleh customer'),
        ),
    ]
