# Generated by Django 5.0.14 on 2026-06-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_seed_custom_bot_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('komisi_persen', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('key', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('klasifikasi', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='category_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('tampil_pos', models.BooleanField(default=True)),
                ('tampil_nav_web', models.BooleanField(default=True)),
                ('default_price_type', models.CharField(choices=[('flat', 'Flat'), ('tier', 'Tier'), ('per_m2', 'Per M2')], default='flat', max_length=50)),
                ('urutan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga_jual_offline', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('harga_jual_online', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('publikasi', models.BooleanField(default=True)),
                ('periode_mulai', models.DateTimeField(blank=True, null=True)),
                ('periode_selesai', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('urutan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tipe', models.CharField(blank=True, max_length=50, null=True)),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nama_alternatif', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('satuan', models.CharField(default='pcs', max_length=50)),
                ('price_type', models.CharField(choices=[('flat', 'Flat'), ('tier', 'Tier'), ('per_m2', 'Per M2')], default='flat', max_length=50)),
                ('tiers', models.JSONField(blank=True, help_text="Format: [{'min_qty': 1, 'price': 10000}, ...]", null=True)),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('harga_jual_toko', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('harga_jual_online', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('harga_online_sama', models.BooleanField(default=True)),
                ('lacak_inventori', models.BooleanField(default=True)),
                ('qty_stok', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_variant', models.BooleanField(default=False)),
                ('tersedia_online', models.BooleanField(default=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.brand')),
                ('koleksi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.collection')),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.productcategory')),
                ('tipe_special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.specialtype')),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to', models.ManyToManyField(blank=True, related_name='addons', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='product_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.productpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_varian', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('harga', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('qty_stok', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='api.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specification')),
            ],
        ),
    ]
