# Generated by Django 5.0.14 on 2026-06-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_brand_collection_productcategory_productpackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('jam_mulai', models.TimeField()),
                ('jam_berakhir', models.TimeField()),
            ],
        ),
    ]
