# Generated by Django 5.0.14 on 2026-06-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_shifttiming'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSAntrianDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_perangkat', models.CharField(max_length=150, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
