# Generated by Django 5.0.14 on 2026-06-30 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_posantriandevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoKasHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(max_length=150)),
                ('kas_awal', models.FloatField(default=0.0)),
                ('kas_akhir', models.FloatField(blank=True, null=True)),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_kas_harian', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
