# Generated by Django 5.0.14 on 2026-07-01 00:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_saldokasharian'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingkasanShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('mulai', models.DateTimeField(default=django.utils.timezone.now)),
                ('berakhir', models.DateTimeField(blank=True, null=True)),
                ('expected', models.FloatField(default=0.0)),
                ('aktual', models.FloatField(default=0.0)),
                ('selisih', models.FloatField(default=0.0)),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ringkasan_shift', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
