# Generated by Django 5.0.14 on 2026-07-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_ringkasanshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='handover_to_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sumber',
            field=models.CharField(choices=[('wa', 'WhatsApp'), ('pos', 'POS Terminal'), ('manual', 'Input Manual')], db_index=True, default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Boss'), ('manager', 'Manager'), ('admin', 'Admin'), ('staff', 'Staff Produksi'), ('kasir', 'Kasir')], db_index=True, default='staff', max_length=20),
        ),
    ]
