# Generated by Django 5.0.14 on 2026-07-01 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_possale_possaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok_minimum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ambang batas Peringatan Sisa Stok', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('masuk', 'Stok Masuk'), ('keluar', 'Stok Keluar'), ('opname', 'Stok Opname')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, help_text="Selalu positif; arah ditentukan oleh 'tipe'", max_digits=10)),
                ('harga_beli', models.DecimalField(blank=True, decimal_places=2, help_text='Harga beli per unit saat stok masuk', max_digits=12, null=True)),
                ('stok_awal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stok_akhir', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('catatan', models.TextField(blank=True, default='')),
                ('tanggal', models.DateField(blank=True, help_text='Tanggal dokumen (boleh beda dari waktu input)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='api.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='api.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='idx_prod_stockmv_prod_time')],
            },
        ),
    ]
