# Generated by Django 5.0.14 on 2026-07-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_stockindocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockindocument',
            name='diterima_dari',
        ),
        migrations.AddField(
            model_name='stockindocument',
            name='nama_penerima',
            field=models.CharField(blank=True, default='', help_text='Nama staf yang menerima barang (Info Penerimaan di Olsera)', max_length=255),
        ),
    ]
