# Generated by Django 5.0.14 on 2026-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_stockindocument_diterima_dari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindocumentitem',
            name='rak',
            field=models.CharField(blank=True, default='', help_text="Lokasi rak/gudang (kolom 'rack' di template import Olsera)", max_length=100),
        ),
    ]
