# Generated by Django 5.0.14 on 2026-07-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_stockindocumentitem_rak'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='harga_beli',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='purchase_price', max_digits=12),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='harga_dinamis',
            field=models.BooleanField(default=False, help_text='selling_prices_stores_are_dynamic'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='harga_pasar',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='market_price', max_digits=12),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='komisi',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='commission (Rp, bukan persen)', max_digits=12),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='maksimal_pesanan',
            field=models.IntegerField(default=0, help_text='maximum_order; 0 = tidak dibatasi'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='minimal_pesanan',
            field=models.IntegerField(default=1, help_text='minimum_order'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='satuan',
            field=models.CharField(blank=True, default='', help_text='uom', max_length=50),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='periode_mulai',
            field=models.DateTimeField(blank=True, help_text='sale_start_date', null=True),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='publikasi',
            field=models.BooleanField(default=True, help_text='ready_publish_sale'),
        ),
    ]
