# Generated by Django 5.0.14 on 2026-07-01 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_stockoutdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockmovement',
            name='tipe',
            field=models.CharField(choices=[('masuk', 'Stok Masuk'), ('keluar', 'Stok Keluar'), ('opname', 'Stok Opname'), ('produksi', 'Produksi Stok')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockProductionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('catatan', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai'), ('batal', 'Batal')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_production_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productstockmovement',
            name='stock_production_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.stockproductiondocument'),
        ),
        migrations.CreateModel(
            name='StockProductionDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.stockproductiondocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_production_items', to='api.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_production_items', to='api.productvariant')),
            ],
        ),
    ]
