# Generated by Django 5.0.14 on 2026-07-02 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_productstockmovement_tipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOpnameDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('catatan', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai'), ('batal', 'Batal')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_opname_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productstockmovement',
            name='stock_opname_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.stockopnamedocument'),
        ),
        migrations.CreateModel(
            name='StockOpnameDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_opname', models.CharField(blank=True, default='', help_text='Jam hitung fisik dilakukan (dokumentasi saja)', max_length=20)),
                ('stok_sistem', models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot qty_stok saat produk ditambahkan ke opname', max_digits=10)),
                ('stok_aktual', models.DecimalField(decimal_places=2, default=0.0, help_text='Hasil hitung fisik', max_digits=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.stockopnamedocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_opname_items', to='api.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_opname_items', to='api.productvariant')),
            ],
        ),
    ]
