# Generated by Django 5.0.14 on 2026-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_stockopnamedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockopnamedocumentitem',
            name='rak',
            field=models.CharField(blank=True, default='', help_text="Lokasi rak (kolom 'rack' di template import Olsera)", max_length=100),
        ),
        migrations.AlterField(
            model_name='stockopnamedocumentitem',
            name='stok_aktual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hasil hitung fisik (per baris/rak; produk sama bisa muncul >1 baris)', max_digits=10),
        ),
    ]
