# Generated by Django 5.0.14 on 2026-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_stockopnamedocumentitem_rak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockopnamedocumentitem',
            name='tanggal_kadaluwarsa',
            field=models.DateField(blank=True, help_text='Tgl Kadaluwarsa (opsional, kolom di layar detail Olsera)', null=True),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='tipe',
            field=models.CharField(choices=[('masuk', 'Stok Masuk'), ('keluar', 'Stok Keluar'), ('opname', 'Stok Opname'), ('produksi', 'Produksi Stok'), ('penjualan', 'Penjualan'), ('pengembalian', 'Pengembalian')], max_length=20),
        ),
    ]
