# Generated by Django 5.0.14 on 2026-07-02 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_stockopnamedocumentitem_tanggal_kadaluwarsa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=12, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('tanggal_aktif', models.DateField(blank=True, null=True)),
                ('tanpa_kadaluarsa', models.BooleanField(default=True)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('min_total_pesanan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unlimited_usage', models.BooleanField(default=True)),
                ('batas_penggunaan', models.IntegerField(blank=True, null=True)),
                ('show_pos', models.BooleanField(default=True)),
                ('show_online', models.BooleanField(default=False)),
                ('once_per_customer', models.BooleanField(default=False)),
                ('daily_reuse', models.BooleanField(default=False)),
                ('dine_in', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('take_away', models.BooleanField(default=False)),
                ('reservasi', models.BooleanField(default=False)),
                ('tipe_diskon', models.CharField(choices=[('percent', 'Persen'), ('nominal', 'Nominal')], default='percent', max_length=10)),
                ('jumlah_diskon', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maksimal_jumlah_diskon', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('all_customers', models.BooleanField(default=True)),
                ('tipe_pelanggan', models.CharField(blank=True, default='', max_length=255)),
                ('pelanggan', models.CharField(blank=True, default='', max_length=255)),
                ('all_products', models.BooleanField(default=True)),
                ('grup_produk', models.CharField(blank=True, default='', max_length=255)),
                ('produk', models.CharField(blank=True, default='', max_length=255)),
                ('all_packages', models.BooleanField(default=True)),
                ('paket_produk', models.CharField(blank=True, default='', max_length=255)),
                ('all_brands', models.BooleanField(default=True)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('penggunaan_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tipe_promosi', models.CharField(choices=[('BX', 'Beli Produk Tertentu, Gratis Produk Lain'), ('DQ', 'Diskon Jika Membeli Produk dengan Kuantitas Tertentu'), ('DA', 'Diskon Jika Memenuhi Total Transaksi yang Ditentukan'), ('FI', 'Gratis Produk')], default='BX', max_length=5)),
                ('combine_qty', models.BooleanField(default=True)),
                ('combine_qty_value', models.IntegerField(default=1)),
                ('produk', models.CharField(blank=True, default='', max_length=255)),
                ('grup_produk', models.CharField(blank=True, default='', max_length=255)),
                ('paket_produk', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('berlaku_membeli', models.CharField(choices=[('salah-satu', 'Salah satu produk yang diatur'), ('semua', 'Semua produk yang diatur')], default='semua', max_length=20)),
                ('produk_gratis', models.CharField(blank=True, default='', max_length=255)),
                ('berlaku_kelipatan', models.BooleanField(default=False)),
                ('all_customers', models.BooleanField(default=True)),
                ('tipe_pelanggan', models.CharField(blank=True, default='', max_length=255)),
                ('pelanggan', models.CharField(blank=True, default='', max_length=255)),
                ('tanggal_aktif', models.DateField()),
                ('tanpa_kadaluarsa', models.BooleanField(default=True)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('jam_24', models.BooleanField(default=True)),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_berakhir', models.TimeField(blank=True, null=True)),
                ('hari', models.CharField(default='min,sen,sel,rab,kam,jum,sab', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_aktif', models.DateField()),
                ('tanpa_kadaluarsa', models.BooleanField(default=True)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('minimal_total_pesanan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipe_diskon', models.CharField(choices=[('percent', 'Persen'), ('nominal', 'Nominal')], default='percent', max_length=10)),
                ('jumlah_diskon', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipe_pelanggan', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('catatan', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
