# Generated by Django 5.0.14 on 2026-07-03 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_discountcoupon_pospromotion_salesdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('diskon_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode_pelanggan', models.CharField(blank=True, default='', max_length=50)),
                ('handphone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='', max_length=1)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('nama_perusahaan', models.CharField(blank=True, default='', max_length=255)),
                ('batas_kredit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('terima_buletin', models.BooleanField(default=False)),
                ('bekukan', models.BooleanField(default=False, help_text='Bekukan: pelanggan tidak bisa dipilih di POS')),
                ('tanggal_berakhir', models.DateField(blank=True, help_text='Masa berlaku membership, kosongkan jika tidak ada', null=True)),
                ('catatan', models.TextField(blank=True, default='')),
                ('alamat', models.TextField(blank=True, default='')),
                ('negara', models.CharField(blank=True, default='', max_length=100)),
                ('provinsi', models.CharField(blank=True, default='', max_length=100)),
                ('kota', models.CharField(blank=True, default='', max_length=100)),
                ('kecamatan', models.CharField(blank=True, default='', max_length=100)),
                ('kode_pos', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='api.customergroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', help_text='Snapshot nama saat dibuat, tetap terisi walau customer dihapus', max_length=255)),
                ('content', models.TextField()),
                ('kategori', models.CharField(choices=[('Info', 'Informasi Umum'), ('Request', 'Request Desain / Ukuran'), ('Komplain', 'Komplain Produksi')], default='Info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='api.customer')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.customer')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kontak_pic', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('catatan', models.TextField(blank=True, default='')),
                ('negara', models.CharField(blank=True, default='', max_length=100)),
                ('provinsi', models.CharField(blank=True, default='', max_length=100)),
                ('kota', models.CharField(blank=True, default='', max_length=100)),
                ('kode_pos', models.CharField(blank=True, default='', max_length=20)),
                ('alamat', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
