# Generated by Django 5.0.14 on 2026-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_customergroup_customer_customernote_customerreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Opsional — login Toko Online/Pesan Online. Disimpan ter-hash.', max_length=128),
        ),
    ]
