# Generated by Django 5.0.14 on 2026-07-03 08:09

import api.customer_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_customer_loyalty_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='content',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='kategori',
        ),
        migrations.AddField(
            model_name='customernote',
            name='jam',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customernote',
            name='judul',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customernote',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerNoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.customer_models.customer_note_document_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.customernote')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNoteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_note_entries', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.customernote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='customernote',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='api.customernotetag'),
        ),
    ]
