# Generated by Django 5.0.14 on 2026-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_customer_note_restructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='harga',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='berat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Berat barang (gram), opsional', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='harga_beli',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='harga_jual_toko',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='harga_pasar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='lacak_inventori',
            field=models.BooleanField(default=True),
        ),
    ]
