# Generated by Django 5.0.14 on 2026-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_productvariant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_fast_moving',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Ambang batas kualifikasi produk 'fast moving'", max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rack',
            field=models.CharField(blank=True, default='', help_text='Lokasi rak penyimpanan', max_length=100),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='harga_jual_online',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='nama_alternatif',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
