# Generated by Django 5.0.14 on 2026-07-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_product_rack_variant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='rack',
            field=models.CharField(blank=True, default='', help_text='Lokasi rak penyimpanan khusus varian ini', max_length=100),
        ),
    ]
