# Generated by Django 5.0.14 on 2026-07-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_productvariant_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='butuh_pengiriman',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='catatan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='harga_dinamis',
            field=models.BooleanField(default=False, help_text='Harga jual di toko bersifat dinamis (mengikuti varian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='harga_pasar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori_bahan_mentah',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori_populer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori_rilis_terbaru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori_unggulan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='klasifikasi',
            field=models.CharField(blank=True, default='Others', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='komisi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='maksimal_pesanan',
            field=models.PositiveIntegerField(default=0, help_text='0 = tidak dibatasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='minimal_pesanan',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='on_hold_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Qty stok yang sedang ditahan/dipesan', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='pesanan_no_seri',
            field=models.BooleanField(default=False, help_text='Pesanan disertai pengisian No Seri/IMEI'),
        ),
        migrations.AddField(
            model_name='product',
            name='tanggal_tersedia_online',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tidak_tersedia_offline_pos',
            field=models.BooleanField(default=False, help_text='Sembunyikan dari POS'),
        ),
    ]
