# Generated by Django 5.0.14 on 2026-07-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_product_detail_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='berat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Berat produk (kg)', max_digits=10, null=True),
        ),
    ]
