# Generated by Django 5.0.14 on 2026-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_product_berat_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bebas_biaya_layanan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='bebas_pajak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='kondisi',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Bekas', 'Bekas')], default='Baru', max_length=10),
        ),
    ]
