# Generated by Django 5.0.14 on 2026-07-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_product_kondisi_pajak_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='komisi_is_persen',
            field=models.BooleanField(default=False, help_text='True = komisi dihitung sebagai %, False = nominal IDR'),
        ),
    ]
