# Generated by Django 5.0.14 on 2026-07-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_product_komisi_persen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='variant_photos/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='habis_stok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='komisi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='komisi_is_persen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='pilihan_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='qty_fast_moving',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
