# Generated by Django 5.0.14 on 2026-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_productvariant_foto_productvariant_habis_stok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of related product IDs'),
        ),
    ]
