# Generated by Django 5.0.14 on 2026-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_product_related_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list, help_text="List of serial numbers: [{'id': '1', 'variant': 'All', 'no_seri': '1234'}]"),
        ),
    ]
