# Generated by Django 5.0.14 on 2026-07-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_product_serial_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_units',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
