# Generated by Django 5.0.14 on 2026-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_productactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='bebas_biaya_layanan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='bebas_pajak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='butuh_pengiriman',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='habis_stok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='tampil_pos',
            field=models.BooleanField(default=True),
        ),
    ]
