# Generated by Django 5.0.14 on 2026-07-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_productpackage_bebas_biaya_layanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='applies_to_categories',
            field=models.ManyToManyField(blank=True, related_name='addons', to='api.productcategory'),
        ),
        migrations.AddField(
            model_name='addon',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_stok_links', to='api.product'),
        ),
        migrations.AddField(
            model_name='addon',
            name='linked_qty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='linked_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_stok_links', to='api.productvariant'),
        ),
    ]
