# Generated by Django 5.0.14 on 2026-07-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_addon_applies_to_categories_addon_linked_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='package_photos/'),
        ),
    ]
