# Generated by Django 5.0.14 on 2026-07-06 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_productpackage_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackageitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productvariant'),
        ),
    ]
