# Generated by Django 5.0.14 on 2026-07-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_productpackageitem_variant'),
        ('hr', '0006_slipgaji'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nilai', models.DecimalField(decimal_places=2, default=0, help_text='Nilai default. Bisa ditimpa per dokumen produksi.', max_digits=12)),
                ('akun', models.ForeignKey(help_text='Akun buku besar terkait, mis. Beban Listrik.', on_delete=django.db.models.deletion.PROTECT, related_name='production_costs', to='hr.akun')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='StockProductionDocumentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(decimal_places=2, help_text='Nilai untuk dokumen ini. Awalnya disalin dari master, boleh diubah.', max_digits=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biaya', to='api.stockproductiondocument')),
                ('production_cost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_costs', to='api.productioncost')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('document', 'production_cost')},
            },
        ),
    ]
