# Generated by Django 5.0.14 on 2026-07-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_productioncost_stockproductiondocumentcost'),
        ('hr', '0006_slipgaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncost',
            name='akun',
            field=models.ForeignKey(blank=True, help_text='Akun buku besar terkait, mis. Beban Listrik. Opsional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_costs', to='hr.akun'),
        ),
    ]
