# Generated by Django 5.0.14 on 2026-07-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_productioncost_akun'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutdocument',
            name='alasan_lainnya',
            field=models.CharField(blank=True, default='', help_text="Teks bebas; wajib diisi saat alasan='lainnya', diabaikan untuk alasan lain", max_length=255),
        ),
        migrations.AlterField(
            model_name='stockoutdocument',
            name='alasan',
            field=models.CharField(choices=[('manual', 'Manual'), ('transfer', 'Transfer Toko'), ('rusak', 'Rusak'), ('kadaluarsa', 'Kadaluarsa'), ('refund', 'Pengembalian dana (refund)'), ('kelebihan_stok', 'Jumlah stock kelebihan'), ('lainnya', 'Alasan lainnya')], default='manual', max_length=20),
        ),
    ]
