# Generated by Django 5.0.14 on 2026-07-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_pospromotion_produk_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindocument',
            name='nama_penerima',
            field=models.CharField(blank=True, default='', help_text='Nama staf yang menerima barang', max_length=255),
        ),
        migrations.AlterField(
            model_name='stockindocumentitem',
            name='rak',
            field=models.CharField(blank=True, default='', help_text="Lokasi rak/gudang (kolom 'rack' di template import)", max_length=100),
        ),
        migrations.AlterField(
            model_name='stockopnamedocumentitem',
            name='rak',
            field=models.CharField(blank=True, default='', help_text="Lokasi rak (kolom 'rack' di template import)", max_length=100),
        ),
        migrations.AlterField(
            model_name='stockopnamedocumentitem',
            name='tanggal_kadaluwarsa',
            field=models.DateField(blank=True, help_text='Tgl Kadaluwarsa (opsional)', null=True),
        ),
        migrations.AlterField(
            model_name='stockoutdocument',
            name='transfer_ke',
            field=models.CharField(blank=True, default='', help_text="Tujuan transfer toko (kolom 'to_store_url_id' di template import)", max_length=255),
        ),
    ]
