# Generated by Django 5.0.14 on 2026-07-18 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_hapus_nama_pembanding_dari_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=50, unique=True)),
                ('tanggal', models.DateField(help_text='Tanggal beli / pembuatan PO')),
                ('mata_uang', models.CharField(blank=True, default='IDR', max_length=10)),
                ('catatan', models.TextField(blank=True, default='')),
                ('jatuh_tempo', models.DateField(blank=True, help_text='Jatuh tempo pembayaran (opsional)', null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('receive_status', models.CharField(choices=[('tunda', 'Tunda'), ('diterima', 'Diterima')], default='tunda', max_length=20)),
                ('tanggal_diterima', models.DateField(blank=True, null=True)),
                ('no_terima', models.CharField(blank=True, default='', max_length=100)),
                ('lanjut_tambah_stok', models.BooleanField(default=True, help_text='Bila True, penerimaan menambah stok (buat Stok Masuk)')),
                ('payment_status', models.CharField(choices=[('belum', 'Belum Bayar'), ('sebagian', 'Sebagian'), ('lunas', 'Lunas')], default='belum', max_length=20)),
                ('is_retur', models.BooleanField(default=False)),
                ('exchange_new', models.BooleanField(default=False, help_text='Retur ditukar barang baru (stok ditambah kembali)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai'), ('batal', 'Batal')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('retur_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='api.purchase')),
                ('supplier_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='api.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockindocument',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_in_documents', to='api.purchase'),
        ),
        migrations.AddField(
            model_name='stockoutdocument',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_documents', to='api.purchase'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='api.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchase')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='api.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metode', models.CharField(blank=True, default='', max_length=50)),
                ('catatan', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.purchase')),
            ],
            options={
                'ordering': ['tanggal', 'created_at'],
            },
        ),
    ]
