# Generated by Django 5.0.14 on 2026-07-18 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_purchase_stockindocument_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=50, unique=True)),
                ('arah', models.CharField(choices=[('pendapatan', 'Pendapatan'), ('pengeluaran', 'Pengeluaran')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('waktu', models.DateTimeField(help_text='Tanggal & jam transaksi')),
                ('catatan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, help_text='Staff yang melakukan transaksi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions_as_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cash_transactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='api.cashtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('pendapatan', 'Pendapatan'), ('pengeluaran', 'Pengeluaran')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transaction_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='tipe_transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.cashtransactiontype'),
        ),
    ]
