# Generated by Django 5.0.14 on 2026-07-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_orderitem_product_orderitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('Tunai', 'Tunai (Cash)'), ('QRIS', 'QRIS'), ('Debit', 'Kartu Debit'), ('Kredit', 'Kartu Kredit'), ('Transfer', 'Transfer Bank'), ('E-Wallet', 'E-Wallet')], default='Tunai', max_length=30)),
                ('nama', models.CharField(help_text="Nama yang tampil di POS, mis. 'CASH'", max_length=100)),
                ('nama_biaya', models.CharField(blank=True, default='', help_text="Mis. 'MDR'", max_length=100)),
                ('nilai_biaya', models.DecimalField(decimal_places=2, default=0, help_text='Persen biaya layanan', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('urutan', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.AddField(
            model_name='saldokasharian',
            name='catatan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='saldokasharian',
            name='waktu_buka',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saldokasharian',
            name='waktu_tutup',
            field=models.DateTimeField(blank=True, help_text='Terisi saat shift ditutup', null=True),
        ),
    ]
