# Generated by Django 5.0.14 on 2026-07-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_pospaymentmethod_saldokasharian_catatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockmovement',
            name='hpp_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HPP mutasi keluar, dihitung dari lapisan FIFO yang dikonsumsi', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='tanggal_kadaluwarsa',
            field=models.DateField(blank=True, help_text="Dipakai pada mode stok 'FIFO & Expired'", null=True),
        ),
        migrations.AddField(
            model_name='stockindocumentitem',
            name='tanggal_kadaluwarsa',
            field=models.DateField(blank=True, help_text="Dipakai pada mode stok 'FIFO & Expired'", null=True),
        ),
        migrations.CreateModel(
            name='StockLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField(db_index=True)),
                ('qty_masuk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sisa_qty', models.DecimalField(decimal_places=2, help_text='Sisa yang belum terpakai', max_digits=12)),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0.0, help_text='Biaya per unit lapisan ini', max_digits=12)),
                ('tanggal_kadaluwarsa', models.DateField(blank=True, db_index=True, null=True)),
                ('rak', models.CharField(blank=True, default='', max_length=100)),
                ('sumber_tipe', models.CharField(choices=[('saldo_awal', 'Saldo Awal (sync)'), ('stock_in', 'Stok Masuk'), ('purchase', 'Pembelian'), ('produksi', 'Produksi'), ('opname', 'Penyesuaian Opname'), ('pos_void', 'Pembatalan POS'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('sumber_nomor', models.CharField(blank=True, default='', help_text='Nomor dokumen asal, untuk laporan', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_layers', to='api.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_layers', to='api.productvariant')),
            ],
            options={
                'ordering': ['tanggal_masuk', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockLayerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_shortfall', models.BooleanField(default=False, help_text='True bila lapisan tidak mencukupi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='api.stocklayer')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_consumptions', to='api.productstockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_consumptions', to='api.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_consumptions', to='api.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocklayer',
            index=models.Index(fields=['product', 'variant', 'sisa_qty'], name='idx_layer_prod_var_sisa'),
        ),
    ]
