# Generated by Django 5.0.14 on 2026-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_productstockmovement_hpp_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possaleitem',
            name='uom_harga',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga per satuan yang dipilih', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='uom_kode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='uom_konverter',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='uom_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='uom_kode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='uom_konverter',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='uom_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Qty sesuai satuan yang dipilih', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockindocumentitem',
            name='uom_kode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stockindocumentitem',
            name='uom_konverter',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockindocumentitem',
            name='uom_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Qty sesuai satuan yang dipilih', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='harga_snapshot',
            field=models.DecimalField(decimal_places=2, help_text='Harga per satuan DASAR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, help_text='Qty dalam satuan DASAR', max_digits=10),
        ),
    ]
