# Generated by Django 5.0.14 on 2026-07-18 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_possaleitem_uom_harga_possaleitem_uom_kode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringkasanshift',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='saldokasharian',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
