# Generated by Django 5.0.14 on 2026-07-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_ringkasanshift_tanggal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutdocumentitem',
            name='uom_kode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stockoutdocumentitem',
            name='uom_konverter',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockoutdocumentitem',
            name='uom_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockoutdocumentitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, help_text='Qty dalam satuan DASAR', max_digits=10),
        ),
    ]
