# Generated by Django 5.0.14 on 2026-07-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_product_special_types_and_package_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproductiondocument',
            name='serap_biaya_ke_hpp',
            field=models.BooleanField(default=False, help_text='Bila aktif, total biaya produksi dibebankan ke HPP barang jadi secara proporsional terhadap nilai bahan tiap item saat posting.'),
        ),
    ]
