# Generated by Django 5.0.14 on 2026-07-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_stockproductiondocument_serap_biaya_ke_hpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboard',
            name='pos_sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.possaleitem'),
        ),
        migrations.AlterField(
            model_name='jobboard',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.orderitem'),
        ),
        migrations.AddIndex(
            model_name='jobboard',
            index=models.Index(fields=['pos_sale_item'], name='idx_job_possaleitem'),
        ),
        migrations.AddConstraint(
            model_name='jobboard',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order_item__isnull', False), ('pos_sale_item__isnull', True)), models.Q(('order_item__isnull', True), ('pos_sale_item__isnull', False)), _connector='OR'), name='job_tepat_satu_sumber'),
        ),
    ]
