# Generated by Django 5.2.16 on 2026-07-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_marketing_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besar_point', models.IntegerField(default=0)),
                ('tipe_diskon', models.CharField(choices=[('IDR', 'Nominal (IDR)'), ('%', 'Persen (%)')], default='%', max_length=10)),
                ('jumlah_diskon', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maksimal_jumlah_diskon', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['besar_point', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPointSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cara_mendapatkan', models.CharField(default='product', max_length=20)),
                ('min_total_pemesanan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('point_diperoleh', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('berlaku_kelipatan', models.BooleanField(default=False)),
                ('default_poin_baru', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('masa_aktif_nilai', models.IntegerField(default=0)),
                ('masa_aktif_satuan', models.CharField(default='pilih', max_length=20)),
                ('berlaku_tipe_pelanggan', models.CharField(default='Semua', max_length=255)),
                ('dapat_poin_saat_tebus', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productstockmovement',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='idx_cpnusage_kupon_plg',
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='idx_cpnusage_kupon_tgl',
        ),
        migrations.RemoveIndex(
            model_name='productstockmovement',
            name='idx_prod_stockmv_prod_time',
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='brand_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='grup_produk_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='paket_produk_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='pelanggan_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='penggunaan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='produk_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='brand_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='grup_produk_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='jumlah_diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='min_total_transaksi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='paket_produk_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='pelanggan_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='produk_gratis_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='qty_gratis',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='tipe_diskon',
            field=models.CharField(choices=[('percent', 'Persen'), ('nominal', 'Nominal')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='possale',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesdiscount',
            name='brand_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
