# Generated by Django 5.2.16 on 2026-07-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_loyaltypointredemption_loyaltypointsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Akun member untuk loyalty point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='api.customer'),
        ),
        migrations.AddField(
            model_name='possale',
            name='diskon_loyalti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='possale',
            name='loyalty_redemption',
            field=models.ForeignKey(blank=True, help_text='Opsi penukaran poin yang dipakai di transaksi ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='api.loyaltypointredemption'),
        ),
        migrations.AddField(
            model_name='possale',
            name='poin_didapat',
            field=models.IntegerField(default=0, help_text='Poin yang diperoleh dari transaksi ini'),
        ),
        migrations.AddField(
            model_name='possale',
            name='poin_ditebus',
            field=models.IntegerField(default=0, help_text='Poin yang ditukar pada transaksi ini'),
        ),
    ]
