# Generated by Django 5.2.16 on 2026-07-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_contact_customer_possale_diskon_loyalti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Poin loyalty per unit (produk tanpa varian)'),
        ),
    ]
