# Generated by Django 5.2.16 on 2026-07-23 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_product_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='dilayani_oleh',
            field=models.ForeignKey(blank=True, help_text='Karyawan yang melayani pelanggan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales_dilayani', to=settings.AUTH_USER_MODEL),
        ),
    ]
