# Generated by Django 5.2.16 on 2026-07-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_order_dilayani_oleh'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='diskon_penjualan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='possale',
            name='sales_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='api.salesdiscount'),
        ),
    ]
