# Generated by Django 5.2.16 on 2026-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_possale_diskon_penjualan_possale_sales_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metode_diskon',
            field=models.CharField(choices=[('tidak_ada', 'Tidak Ada'), ('otomatis', 'Diskon Penjualan Otomatis'), ('kupon', 'Kupon Diskon')], default='tidak_ada', max_length=20),
        ),
    ]
