# Generated by Django 5.2.16 on 2026-07-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_accountingsettings_pos_ppn_output_account_and_more'),
        ('api', '0086_settlement_status_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospaymentmethod',
            name='accounting_payment_method',
            field=models.ForeignKey(blank=True, help_text='Pemetaan ke Cara Pembayaran di modul Akuntansi Internal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_payment_methods', to='accounting.paymentmethod'),
        ),
    ]
