# Generated by Django 5.2.16 on 2026-07-27 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_pospaymentmethod_accounting_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alamat_pelanggan',
            field=models.TextField(blank=True, help_text='Alamat lengkap tujuan pengiriman', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='catatan_footer',
            field=models.TextField(blank=True, default='Terima kasih atas pesanan Anda', help_text='Catatan di bagian bawah cetakan invoice', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email_pelanggan',
            field=models.CharField(blank=True, help_text='Email pelanggan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='jatuh_tempo',
            field=models.DateField(blank=True, help_text='Tanggal jatuh tempo pembayaran invoice', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kurir_pengiriman',
            field=models.CharField(blank=True, help_text='Nama kurir pengiriman (JNE, Sicepat, dll)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='layanan_pengiriman',
            field=models.CharField(blank=True, help_text='Tipe layanan pengiriman (REG, YES, Instant, dll)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pengirim_dropship',
            field=models.CharField(blank=True, help_text='Nama pengirim dropship', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tanggal_pengiriman',
            field=models.DateField(blank=True, help_text='Tanggal rencana pengiriman', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='telepon_dropship',
            field=models.CharField(blank=True, help_text='Nomor telepon pengirim dropship', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='toko_dropship',
            field=models.CharField(blank=True, help_text='Nama toko dropshipper', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PengembalianOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal_pengembalian', models.DateField(default=django.utils.timezone.now, help_text='Tanggal pengembalian pesanan')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Tunda', 'Tunda'), ('Dikonfirmasi', 'Dikonfirmasi'), ('Batal', 'Batal')], db_index=True, default='Tunda', max_length=20)),
                ('catatan', models.TextField(blank=True, help_text='Alasan atau catatan pengembalian', null=True)),
                ('nominal_refund', models.IntegerField(default=0, help_text='Nominal pengembalian uang / refund (jika ada)')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, help_text='Pengguna yang menginput pengembalian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengembalian_dibuat', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Pesanan yang dikembalikan', on_delete=django.db.models.deletion.CASCADE, related_name='daftar_pengembalian', to='api.order')),
            ],
            options={
                'verbose_name': 'Pengembalian Order',
                'verbose_name_plural': 'Pengembalian Order',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
