# Generated by Django 5.2.16 on 2026-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_order_alamat_pelanggan_order_catatan_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referensi_pembayaran',
            field=models.CharField(blank=True, default='', help_text='Referensi pembayaran dari Paypal/Bank (opsional, diisi manual saat mencatat pembayaran)', max_length=255),
        ),
    ]
