# Generated by Django 5.2.16 on 2026-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_purchase_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='penerima_nama',
            field=models.CharField(blank=True, default='', help_text='Nama akun pengguna yang menerima barang', max_length=255),
        ),
    ]
