# Generated by Django 5.2.16 on 2026-07-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_alter_journalentry_source_type'),
        ('api', '0093_purchaseitem_retur_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='akun_debit',
            field=models.ForeignKey(blank=True, help_text='Wajib diisi sebelum posting ke jurnal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions_debit', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='akun_kredit',
            field=models.ForeignKey(blank=True, help_text='Wajib diisi sebelum posting ke jurnal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions_kredit', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai'), ('batal', 'Batal')], db_index=True, default='draft', max_length=20),
        ),
    ]
