# Generated by Django 5.2.16 on 2026-07-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_accountingsettings_komisi_penjualan_debit_account_and_more'),
        ('api', '0094_cashtransaction_akun_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='akun_hutang',
            field=models.ForeignKey(blank=True, help_text='Akun hutang default supplier ini (Pengaturan Supplier).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_akun_hutang', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='jatuh_tempo_hari',
            field=models.PositiveIntegerField(blank=True, help_text='Jatuh tempo pembayaran hutang ke supplier ini, dalam hari.', null=True),
        ),
    ]
