# Generated by Django 5.2.16 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_supplier_akun_hutang_jatuh_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringkasanshift',
            name='kas_awal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='kas_keluar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='kas_masuk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='penjualan_tunai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='rincian_tersedia',
            field=models.BooleanField(default=False),
        ),
    ]
