# Generated by Django 5.2.16 on 2026-08-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_ringkasanshift_cash_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockmovement',
            name='pos_sale',
            field=models.ForeignKey(blank=True, help_text="Transaksi POS sumber mutasi ini (tipe='penjualan'/'pengembalian') — dipakai T-107 untuk agregasi HPP per sale.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='api.possale'),
        ),
    ]
