# Generated by Django 5.2.16 on 2026-08-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_productstockmovement_pos_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='voided_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales_voided', to=settings.AUTH_USER_MODEL),
        ),
    ]
