# Generated by Django 5.0.14 on 2026-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_productstockmovement_pos_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboard',
            name='deadline',
            field=models.DateField(blank=True, help_text='Batas tanggal penyelesaian SPK', null=True),
        ),
    ]
