# Generated by Django 6.0 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0036_purchase_account_mappings"),
        ("api", "0099_jobboard_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasepayment",
            name="jenis",
            field=models.CharField(choices=[("advance", "Down Payment"), ("settlement", "Pelunasan")], default="settlement", max_length=15),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="payment_account",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="purchase_payments", to="accounting.account"),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="payment_account_code_snapshot",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="payment_account_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
