# Generated by Django 6.0 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_purchasepayment_account_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(
                choices=[('tunda', 'Tunda'), ('terkirim', 'Terkirim'), ('dikirim', 'Dikirim')],
                default='tunda',
                help_text='Tahap pengiriman sebelum barang diterima.',
                max_length=20,
            ),
        ),
    ]
