# Generated by Django 6.0 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_purchase_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_marked_paid',
            field=models.BooleanField(
                default=False,
                help_text='Penanda administratif pembayaran; tidak membuat pembayaran atau jurnal.',
            ),
        ),
    ]
