# Generated by Django 6.0 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_purchase_payment_marked_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='whatsapp_resi_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='possale',
            name='whatsapp_resi_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='possale',
            name='whatsapp_resi_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='whatsapp_resi_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Belum Dikirim'), ('sending', 'Sedang Dikirim'),
                    ('sent', 'Terkirim'), ('failed', 'Gagal Dikirim'),
                    ('skipped', 'Tidak Dikirim'),
                ],
                default='pending',
                help_text='Status pengiriman resi POS melalui WhatsApp.',
                max_length=20,
            ),
        ),
    ]
