# Generated by Django 5.0.14 on 2026-08-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_possale_void_audit_fields'),
        ('api', '0103_possale_whatsapp_resi_status'),
    ]

    operations = [
    ]
