# Generated by Django 5.0.14 on 2026-08-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_ringkasanshift_payment_method_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.productpackage'),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_items', to='api.productpackage'),
        ),
    ]
