# Generated by Django 5.0.14 on 2026-08-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_orderitem_paket_possaleitem_paket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockmovement',
            name='order',
            field=models.ForeignKey(blank=True, help_text="Order (DP dari kasir) sumber mutasi ini (tipe='penjualan'/'pengembalian').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='api.order'),
        ),
    ]
