# Generated by Django 5.0.14 on 2026-08-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_productstockmovement_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_snapshot', models.CharField(max_length=255)),
                ('harga_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Harga addon per unit qty item induk, saat dipilih', max_digits=12)),
                ('qty', models.DecimalField(decimal_places=2, default=1, help_text='Disamakan dengan qty item induk', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='harga_snapshot * qty', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_item_addons', to='api.addon')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.orderitem')),
                ('pos_sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.possaleitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='saleitemaddon',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order_item__isnull', True), ('pos_sale_item__isnull', False)), models.Q(('order_item__isnull', False), ('pos_sale_item__isnull', True)), _connector='OR'), name='saleitemaddon_tepat_satu_sumber'),
        ),
    ]
