# Generated by Django 5.0.14 on 2026-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_saleitemaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stok_dikurangi',
            field=models.BooleanField(default=False, help_text='Sudah pernah dipotong dari stok (M8/FIFO) — cegah dobel potong kalau item ini diedit ulang.'),
        ),
    ]
