# Generated by Django 5.0.14 on 2026-08-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_orderitem_stok_dikurangi'),
    ]

    operations = [
        migrations.AddField(
            model_name='possaleitem',
            name='finishing_biaya',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biaya tambahan finishing per satuan qty (mis. laminasi, mata ayam)', max_digits=12),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='lebar',
            field=models.FloatField(default=0.0, help_text='Lebar (meter) untuk produk meteran'),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='panjang',
            field=models.FloatField(default=0.0, help_text='Panjang (meter) untuk produk meteran'),
        ),
    ]
