# Generated by Django 5.0.14 on 2026-08-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_possaleitem_meteran_finishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tanggal_bergabung',
            field=models.DateField(blank=True, help_text='Tanggal pelanggan pertama bergabung — manual atau dari import data lama, beda dari created_at (kapan record dibuat di sistem ini)', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='transaksi_terakhir',
            field=models.DateField(blank=True, help_text='Tanggal transaksi terakhir tercatat — termasuk histori sebelum migrasi sistem, diisi manual/import', null=True),
        ),
    ]
