# Generated by Django 5.0.14 on 2026-08-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_customer_tanggal_bergabung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='butuh_bahan',
            field=models.BooleanField(default=True, help_text='Wajib isi Bahan/Material saat order via WA'),
        ),
        migrations.AddField(
            model_name='product',
            name='butuh_finishing',
            field=models.BooleanField(default=True, help_text='Wajib isi Finishing saat order via WA'),
        ),
    ]
