# Generated by Django 5.0.14 on 2026-08-12 12:57, hand-edited for safe data migration.
#
# BillOfMaterials.product dulu adalah OneToOneField ke ProductPrice (model
# lama). Kolom ini sekarang diubah jadi ForeignKey ke Product (katalog
# produk asli) supaya fitur "Tambah Bahan" di detail produk benar-benar
# terhubung ke Product yang dilihat user, bukan cuma dicocokkan dari string
# nama (bug ditemukan & diperbaiki 2026-08-12). Nilai `product_id` LAMA
# (menunjuk ProductPrice) WAJIB dipindah dulu ke field baru `product_price`
# SEBELUM kolom `product` diubah target-nya ke tabel Product yang berbeda —
# kalau tidak, nilai lama akan jadi FK rusak/menunjuk baris Product yang
# salah begitu constraint diganti.

import django.db.models.deletion
from django.db import migrations, models


def salin_product_lama_ke_product_price(apps, schema_editor):
    BillOfMaterials = apps.get_model('api', 'BillOfMaterials')
    # Di titik migrasi ini field `product` MASIH menunjuk ProductPrice
    # (belum di-alter) — salin nilainya ke `product_price` yang baru
    # ditambahkan, lalu kosongkan `product` supaya aman diubah target-nya.
    BillOfMaterials.objects.exclude(product__isnull=True).update(
        product_price_id=models.F('product_id'),
    )
    BillOfMaterials.objects.update(product=None)


def kembalikan_product_price_ke_product(apps, schema_editor):
    BillOfMaterials = apps.get_model('api', 'BillOfMaterials')
    BillOfMaterials.objects.exclude(product_price__isnull=True).update(
        product_id=models.F('product_price_id'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_product_butuh_bahan_product_butuh_finishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='product_price',
            field=models.OneToOneField(blank=True, help_text='[Legacy] Produk lama yang dirujuk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='api.productprice'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_list', to='api.productvariant'),
        ),
        migrations.RunPython(salin_product_lama_ke_product_price, kembalikan_product_price_ke_product),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_list', to='api.product'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', False)), fields=('product', 'variant'), name='unique_bom_per_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', True)), fields=('product',), name='unique_bom_per_product_no_variant'),
        ),
    ]
