# Generated by Django 5.0.14 on 2026-08-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_inventoryitem_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='possaleitem',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
