# Generated by Django 5.0.14 on 2026-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_seed_customer_group_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringkasanshift',
            name='keterangan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
