# Generated by Django 5.0.14 on 2026-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_ringkasanshift_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='diambil_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
