# Generated by Django 5.0.14 on 2026-08-14 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_order_void_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSVoidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('digunakan', 'Sudah Digunakan')], db_index=True, default='pending', max_length=12)),
                ('otp_code', models.CharField(blank=True, default='', max_length=6)),
                ('alasan_tolak', models.TextField(blank=True, default='')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('disetujui_pada', models.DateTimeField(blank=True, null=True)),
                ('kadaluarsa_pada', models.DateTimeField(blank=True, null=True)),
                ('digunakan_pada', models.DateTimeField(blank=True, null=True)),
                ('diminta_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_void_requests_diminta', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_void_requests_disetujui', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='void_requests', to='api.possale')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
                'indexes': [models.Index(fields=['sale', 'status'], name='idx_pvr_sale_status')],
            },
        ),
    ]
