# Generated by Django 5.2.17 on 2026-09-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_posvoidrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_photos/'),
        ),
    ]
