# Generated by Django 5.2.17 on 2026-09-07 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_order_sumber_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('docucolor', 'Fuji Xerox DocuColor'), ('cetak_banner', 'Cetak Banner'), ('printer', 'Printer')], max_length=20)),
                ('lokasi', models.CharField(blank=True, default='', max_length=100)),
                ('ambang_servis_klik', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('catatan', models.TextField(blank=True, default='')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('divisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesin_list', to='api.divisi')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('counter_saat_servis', models.PositiveIntegerField(blank=True, null=True)),
                ('jenis', models.CharField(help_text='Mis: Ganti Toner Cyan, Ganti Fuser, Servis Rutin', max_length=150)),
                ('catatan', models.TextField(blank=True, default='')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dicatat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_dicatat', to=settings.AUTH_USER_MODEL)),
                ('mesin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_maintenance', to='api.mesin')),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PenggunaanMesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('lembar_color', models.PositiveIntegerField(default=0)),
                ('lembar_mono', models.PositiveIntegerField(default=0)),
                ('ukuran_kertas', models.CharField(blank=True, default='', max_length=20)),
                ('jenis_kertas', models.CharField(blank=True, default='', max_length=100)),
                ('gramasi_kertas', models.CharField(blank=True, default='', max_length=20)),
                ('panjang_bahan_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jenis_bahan', models.CharField(blank=True, default='', max_length=100)),
                ('kondisi_hasil', models.CharField(choices=[('ok', 'OK'), ('kendala', 'Ada Kendala')], default='ok', max_length=20)),
                ('catatan_konfirmasi', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggunaan_mesin', to='api.jobboard')),
                ('mesin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_penggunaan', to='api.mesin')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggunaan_mesin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
                'indexes': [models.Index(fields=['mesin', '-waktu'], name='idx_penggunaan_mesin_waktu')],
            },
        ),
    ]
