# Generated by Django 5.2.17 on 2026-09-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_machine_usage_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembalianorder',
            name='items_json',
            field=models.TextField(blank=True, default='', help_text='Snapshot item yang diretur (JSON list: order_item_id, qty, max_qty, harga, alasan).'),
        ),
        migrations.AddField(
            model_name='pengembalianorder',
            name='tambahan_json',
            field=models.TextField(blank=True, default='', help_text='Snapshot biaya tambahan retur (JSON: deskripsi, jumlah).'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='konfirmasi_kerusakan',
            field=models.TextField(blank=True, default='', help_text='Wajib diisi kalau retur diajukan sebelum PO asal Lunas -- retur barang cacat tidak perlu menunggu lunas dulu (keputusan user 2026-09-08), tapi harus tercatat jelas apa kerusakannya. Penanggung jawab konfirmasi = dibuat_oleh.'),
        ),
        migrations.AlterField(
            model_name='pengembalianorder',
            name='nominal_refund',
            field=models.IntegerField(default=0, help_text='Nominal refund. Dihitung ulang otomatis dari items_json+tambahan_json tiap kali keduanya diisi (proporsional qty diretur vs qty asli item); hanya jatuh ke total_harga penuh order kalau items_json masih kosong (retur belum merinci item -- bug ditemukan audit 2026-09-08: field ini dulu SELALU total_harga penuh karena frontend tidak pernah mengirim nominal_refund maupun items_json tersimpan di backend).'),
        ),
    ]
