# Generated by Django 5.2.17 on 2026-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_audit_fixes_retur_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='diskon_nominal',
            field=models.IntegerField(default=0, help_text="Dipakai kalau tipe_diskon='nominal'."),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='tipe_diskon',
            field=models.CharField(choices=[('persen', 'Persentase (%)'), ('nominal', 'Nominal (Rp)')], default='persen', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='diskon_tipe_pelanggan',
            field=models.IntegerField(default=0, help_text='Potongan nominal otomatis dari Diskon Khusus Tipe Pelanggan (CustomerGroup), dihitung ulang tiap save().'),
        ),
        migrations.AddField(
            model_name='possale',
            name='diskon_tipe_pelanggan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='diskon_persen',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Dipakai kalau tipe_diskon='persen'.", max_digits=5),
        ),
    ]
