# Generated by Django 5.2.17 on 2026-09-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_customer_group_diskon_khusus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diskon_promo',
            field=models.IntegerField(default=0, help_text='Potongan nominal otomatis dari Promosi POS tipe DQ/DA (Discount Qty/Amount), dihitung ulang tiap save(). Tipe BX/FI (item gratis) TIDAK diterapkan otomatis di Order -- lihat _hitung_diskon_promo_pos().'),
        ),
    ]
