# Generated by Django 5.2.17 on 2026-09-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_order_diskon_promo_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
