# Generated by Django 5.2.17 on 2026-09-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_mesin_vendor_dan_jadwal_servis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrappeProductSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frappe_item_code', models.CharField(max_length=140)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frappe_sync', to='api.product')),
            ],
        ),
    ]
