# Generated by Django 5.2.17 on 2026-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_frappeproductsync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sumber',
            field=models.CharField(choices=[('wa', 'WhatsApp'), ('pos', 'POS Terminal'), ('manual', 'Input Manual'), ('staff', 'Dibantu Staff'), ('agent', 'AI Agent Eksternal')], db_index=True, default='manual', max_length=10),
        ),
    ]
