# Generated by Django 5.2.17 on 2026-09-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_order_sumber_agent_eksternal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitBisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='posisi',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='unit_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='api.unitbisnis'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unit_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan', to='api.unitbisnis'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.unitbisnis'),
        ),
        migrations.AddField(
            model_name='possale',
            name='unit_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='api.unitbisnis'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.unitbisnis'),
        ),
    ]
