# Generated by Django 5.2.17 on 2026-09-12 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_seed_unit_bisnis'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='atasan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bawahan_langsung', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Boss'), ('manager', 'Manager'), ('admin', 'Admin'), ('spv', 'SPV / Supervisor'), ('kordiv', 'Koordinator Divisi'), ('staff', 'Staff Produksi'), ('kasir', 'Kasir')], db_index=True, default='staff', max_length=20),
        ),
    ]
