# Generated by Django 5.2.17 on 2026-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_customuser_atasan_and_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hr_employee_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
