# Generated by Django 5.0.14 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_customuser_hr_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='synced_to_crm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
