# Generated by Django 5.2.17 on 2026-09-18 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_possale_synced_to_crm_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posvoidrequest',
            name='disetujui_kordiv_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_void_requests_kordiv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posvoidrequest',
            name='disetujui_kordiv_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posvoidrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan Kordiv'), ('menunggu_spv', 'Disetujui Kordiv, Menunggu SPV'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('digunakan', 'Sudah Digunakan')], db_index=True, default='pending', max_length=12),
        ),
    ]
