# Generated by Django 5.2.17 on 2026-09-18 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_posvoidrequest_kordiv_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='catatan_admin_finance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='diverifikasi_admin_finance_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions_diverifikasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='diverifikasi_admin_finance_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='catatan_verifikasi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='diverifikasi_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ringkasan_shift_diverifikasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='diverifikasi_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ringkasanshift',
            name='status_verifikasi',
            field=models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('diverifikasi', 'Diverifikasi'), ('dipertanyakan', 'Dipertanyakan')], db_index=True, default='menunggu', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Boss'), ('manager', 'Manager'), ('admin', 'Admin'), ('spv', 'SPV / Supervisor'), ('kordiv', 'Koordinator Divisi'), ('staff', 'Staff Produksi'), ('kasir', 'Kasir'), ('admin_finance', 'Admin Finance'), ('spv_finance', 'SPV Finance')], db_index=True, default='staff', max_length=20),
        ),
    ]
