# Generated by Django 5.2.17 on 2026-09-21 11:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_orderreturnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=50, unique=True)),
                ('keperluan', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('disiapkan', 'Disiapkan'), ('diterima', 'Diterima'), ('batal', 'Batal')], db_index=True, default='diajukan', max_length=20)),
                ('catatan_penolakan', models.TextField(blank=True, default='')),
                ('disetujui_pada', models.DateTimeField(blank=True, null=True)),
                ('disiapkan_pada', models.DateTimeField(blank=True, null=True)),
                ('diterima_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_bahan_disetujui', to=settings.AUTH_USER_MODEL)),
                ('disiapkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_bahan_disiapkan', to=settings.AUTH_USER_MODEL)),
                ('divisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_bahan', to='api.divisi')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_bahan', to='api.jobboard')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permintaan_bahan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_diminta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('qty_disetujui', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_disiapkan', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('catatan', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permintaan_bahan_items', to='api.inventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.materialrequisition')),
            ],
        ),
        migrations.AddIndex(
            model_name='materialrequisition',
            index=models.Index(fields=['status', '-created_at'], name='idx_mreq_status_waktu'),
        ),
        migrations.AddConstraint(
            model_name='materialrequisitionitem',
            constraint=models.UniqueConstraint(fields=('requisition', 'item'), name='uniq_mreq_item_per_dokumen'),
        ),
        migrations.AddConstraint(
            model_name='materialrequisitionitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_diminta__gt', Decimal('0'))), name='chk_mreq_qty_diminta_positif'),
        ),
    ]
