# Generated by Django 5.2.17 on 2026-09-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_material_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisi',
            name='unit_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisi', to='api.unitbisnis'),
        ),
    ]
