# Generated by Django 5.2.17 on 2026-09-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_divisi_unit_bisnis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockmovement',
            name='tipe',
            field=models.CharField(choices=[('masuk', 'Stok Masuk'), ('keluar', 'Stok Keluar'), ('opname', 'Stok Opname'), ('produksi', 'Produksi Stok'), ('penjualan', 'Penjualan'), ('pengembalian', 'Pengembalian'), ('saldo_awal', 'Saldo Awal')], max_length=20),
        ),
    ]
