# Generated by Django 5.2.17 on 2026-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_product_stock_movement_saldo_awal_tipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jumlah_cetak_ulang',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='terakhir_dicetak_ulang',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='jumlah_cetak_ulang',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possale',
            name='terakhir_dicetak_ulang',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
