# Generated by Django 5.2.17 on 2026-09-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_jejak_cetak_ulang_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posvoidrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('menunggu_spv', 'Disetujui Kordiv, Menunggu SPV'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('digunakan', 'Sudah Digunakan')], db_index=True, default='pending', max_length=12),
        ),
    ]
