# Generated by Django 5.2.17 on 2026-09-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_void_request_hapus_tahap_kordiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanTargetProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_tipe', models.CharField(choices=[('harian', 'Harian'), ('mingguan', 'Mingguan'), ('bulanan', 'Bulanan')], max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('target_selesai', models.PositiveIntegerField(default=0, help_text='Target jumlah job/order selesai pada periode ini.')),
                ('kendala_operasional', models.TextField(blank=True, default='')),
                ('catatan', models.TextField(blank=True, default='')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_target_produksi', to=settings.AUTH_USER_MODEL)),
                ('divisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_target_produksi', to='api.divisi')),
            ],
            options={
                'ordering': ['-tanggal_mulai', '-id'],
                'indexes': [models.Index(fields=['divisi', 'tanggal_mulai'], name='idx_ltp_divisi_tanggal'), models.Index(fields=['dibuat_oleh', 'tanggal_mulai'], name='idx_ltp_pembuat_tanggal')],
            },
        ),
    ]
