# Generated by Django 5.2.17 on 2026-09-23 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_laporan_target_produksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboard',
            name='pic_staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['staff', 'spv', 'kordiv']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
