# Generated by Django 5.2.17 on 2026-09-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_laporantargetkeuangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reorder_dari',
            field=models.ForeignKey(blank=True, help_text='Order asal kalau order ini dibuat lewat menu Reorder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_turunan', to='api.order'),
        ),
    ]
