# Generated by Django 5.2.17 on 2026-09-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_order_reorder_dari'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tampilkan_stok_pos',
            field=models.BooleanField(default=True, help_text='Tampilkan keterangan stok di kartu katalog Kasir POS Terminal'),
        ),
    ]
