# Generated by Django 5.2.17 on 2026-09-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_orderitem_paket_tandai_stok_dikurangi'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='diskon_nilai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='diskon_tipe',
            field=models.CharField(choices=[('persen', 'Persen'), ('nominal', 'Nominal')], default='persen', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pajak_nilai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pajak_tipe',
            field=models.CharField(choices=[('persen', 'Persen'), ('nominal', 'Nominal')], default='persen', max_length=10),
        ),
    ]
