# Generated by Django 5.2.17 on 2026-09-24 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_purchase_diskon_pajak'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockopnamedocument',
            name='diposting_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_opname_diposting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockopnamedocument',
            name='nilai_defisit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockopnamedocument',
            name='nilai_jurnal_defisit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockopnamedocument',
            name='nilai_jurnal_surplus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockopnamedocument',
            name='nilai_surplus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockopnamedocument',
            name='waktu_diposting',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockopnamedocumentitem',
            name='harga_beli_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga beli produk/varian saat dokumen diposting; dasar nilai selisih yang tetap walau harga beli berubah kemudian.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='StockOpnameActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tindakan', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.stockopnamedocument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
