# Generated by Django 5.2.17 on 2026-09-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_stok_opname_selisih_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sumber',
            field=models.CharField(choices=[('wa', 'WhatsApp'), ('pos', 'POS Terminal'), ('manual', 'Input Manual'), ('staff', 'Dibantu Staff'), ('agent', 'AI Agent Eksternal'), ('crm', 'CRM / Sales')], db_index=True, default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='OrderAsalCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunci', models.CharField(max_length=80, unique=True)),
                ('crm_user_id', models.IntegerField(blank=True, null=True)),
                ('crm_username', models.CharField(blank=True, default='', max_length=150)),
                ('sales_nama', models.CharField(blank=True, default='', max_length=150)),
                ('crm_opportunity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('crm_contact_id', models.IntegerField(blank=True, null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asal_crm', to='api.order')),
            ],
            options={
                'ordering': ['-dibuat'],
            },
        ),
    ]
