# Generated by Django 5.2.17 on 2026-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_order_asal_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderasalcrm',
            name='crm_won_terkirim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
