# Generated by Django 5.2.17 on 2026-09-26 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_order_asal_crm_won'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifikasiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('produk', 'Produk'), ('bahan', 'Bahan baku')], max_length=10)),
                ('ref_id', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=255)),
                ('satuan', models.CharField(blank=True, default='', max_length=30)),
                ('stok', models.DecimalField(decimal_places=2, max_digits=14)),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=14)),
                ('aktif', models.BooleanField(default=True, help_text='Masih di bawah minimum')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('dibaca_oleh', models.ManyToManyField(blank=True, related_name='notifikasi_stok_dibaca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('aktif', True)), fields=('jenis', 'ref_id'), name='uniq_notifikasi_stok_aktif')],
            },
        ),
    ]
