# Generated by Django 5.2.17 on 2026-09-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_notifikasi_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindocument',
            name='dp_diterapkan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stockindocument',
            name='nilai_bersih',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stockindocument',
            name='nilai_pajak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stockindocumentitem',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_in_items', to='api.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='receive_status',
            field=models.CharField(choices=[('tunda', 'Tunda'), ('sebagian', 'Diterima Sebagian'), ('diterima', 'Diterima')], default='tunda', max_length=20),
        ),
    ]
