# Generated by Django 5.2.17 on 2026-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_penerimaan_parsial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembalianorder',
            name='barang_layak_jual',
            field=models.BooleanField(default=True),
        ),
    ]
