# Generated by Django 5.2.17 on 2026-09-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_retur_barang_layak_jual'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='api.productvariant'),
        ),
    ]
