# Generated by Django 5.2.17 on 2026-09-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_bahan_baku_varian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospromotion',
            name='unit_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_promotions', to='api.unitbisnis'),
        ),
    ]
