# Generated by Django 5.2.17 on 2026-09-28 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_promosi_pos_unit_bisnis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanggunganReorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metode', models.CharField(choices=[('tunai', 'Tunai di kasir'), ('potong_gaji', 'Potong gaji')], max_length=20)),
                ('status', models.CharField(choices=[('lunas', 'Lunas (tunai)'), ('menunggu_potong', 'Menunggu potong gaji'), ('sudah_dipotong', 'Sudah dipotong gaji')], db_index=True, max_length=20)),
                ('alasan', models.TextField()),
                ('dibuat', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ditandai_dipotong_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ditandai_dipotong_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tanggungan_reorder', to='api.order')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanggungan_reorder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat'],
                'indexes': [models.Index(fields=['staff', 'dibuat'], name='idx_tanggungan_staff_waktu')],
            },
        ),
    ]
