# Generated by Django 5.2.17 on 2026-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_tanggungan_reorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Boss'), ('manager', 'Manager'), ('admin', 'Admin'), ('spv', 'SPV / Supervisor'), ('kordiv', 'Koordinator Divisi'), ('staff', 'Staff Produksi'), ('kasir', 'Kasir'), ('admin_finance', 'Admin Finance'), ('spv_finance', 'SPV Finance'), ('sales', 'Sales (profil CRM, tanpa login)')], db_index=True, default='staff', max_length=20),
        ),
    ]
