# Generated by Django 5.2.17 on 2026-09-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_pengembalianjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisInsentif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('nominal_default', models.PositiveIntegerField(default=0, help_text='Nominal standar (Rp) saat masuk ke SPK')),
                ('aktif', models.BooleanField(default=True)),
                ('keterangan', models.CharField(blank=True, default='', max_length=255)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('divisi', models.ManyToManyField(blank=True, related_name='jenis_insentif', to='api.divisi')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='InsentifPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('catatan', models.CharField(blank=True, default='', max_length=255)),
                ('otomatis', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_insentif', to='api.jobboard')),
                ('jenis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.jenisinsentif')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('jenis__isnull', False)), fields=('job', 'jenis'), name='uniq_insentif_job_jenis')],
            },
        ),
    ]
