# Generated by Django 5.2.17 on 2026-10-06 14:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_hr_organisasi_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspekSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveiKepuasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(blank=True, default='', max_length=255)),
                ('nomor_wa', models.CharField(blank=True, default='', max_length=20)),
                ('catatan', models.TextField(blank=True, default='')),
                ('rata_rata', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survei_kepuasan', to='api.order')),
                ('pos_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survei_kepuasan', to='api.possale')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='NilaiSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aspek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nilai', to='api.aspeksurvei')),
                ('survei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='api.surveikepuasan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='surveikepuasan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', True), ('pos_sale__isnull', False)), models.Q(('order__isnull', False), ('pos_sale__isnull', True)), _connector='OR'), name='survei_tepat_satu_transaksi'),
        ),
        migrations.AlterUniqueTogether(
            name='nilaisurvei',
            unique_together={('survei', 'aspek')},
        ),
    ]
