# Generated by Django 5.2.17 on 2026-10-06 15:45

import django.db.models.deletion
from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def ulasan_dari_survei_lama(apps, schema_editor):
    """Saran survei yang sudah masuk sebelum fitur ini ikut jadi ulasan."""
    Survei = apps.get_model('api', 'SurveiKepuasan')
    Ulasan = apps.get_model('api', 'CustomerReview')
    for s in Survei.objects.exclude(catatan='').select_related('pos_sale'):
        if not s.catatan.strip() or Ulasan.objects.filter(survei=s).exists():
            continue
        Ulasan.objects.create(
            survei=s, sumber='survei', customer_name=s.nama_pelanggan or 'Pelanggan Umum',
            rating=max(1, min(5, int(s.rata_rata.quantize(Decimal('1'), rounding=ROUND_HALF_UP)))),
            comment=s.catatan.strip(), nomor_transaksi=s.pos_sale.nomor if s.pos_sale_id else (s.order_id or ''),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_aspek_survei_bawaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='nomor_transaksi',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='sumber',
            field=models.CharField(choices=[('survei', 'Survei Struk Online'), ('google', 'Google Maps'), ('instagram', 'Instagram'), ('langsung', 'Langsung / Lisan'), ('lainnya', 'Lainnya')], default='langsung', max_length=20),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='survei',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='api.surveikepuasan'),
        ),
        migrations.RunPython(ulasan_dari_survei_lama, migrations.RunPython.noop),
    ]
