# Generated by Django 5.2.17 on 2026-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_ulasan_dari_survei'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboard',
            name='deadline_jam',
            field=models.TimeField(blank=True, help_text='Batas jam penyelesaian SPK', null=True),
        ),
    ]
